### ISSUE TITLE
Performance gap between os x and linux

### ISSUE THREAD

**Issue by jlgerber** [bevyengine/bevy#962] opened 2020-11-30 16:17 UTC
**Bevy version**
0.3

The release number or commit hash of the version you're using.
v0.3.0 (9afe196)

**Operating system & version**
OS X
catalina 10.15.6 
running on 
2019 macbook pro
2.4 ghz 8 core i9
32 gb ram

LINUX
System 76 Onyx Pro
pop os 20.10
running on
2.2 ghz 12 core i7
32 gb ram
GeForce GTX 1070 Mobile GPU

**What you did**
In the course of attempting to learn Bevy, I wrote a very simple 2d "game" which just allows you to drive a vehicle around using the mouse to control turning and acceleration. The os x version is buttery smooth, both when resizing the window and when "playing" the game.

The linux version is another story. I get periodic chop where it appears that that the vehicle will either pause its forward momentum or skip back a couple of ticks. This happens periodically, with or without changing the input. I also find resizing the main window to be janky, especially compared to os x, which exhibits no problems.

What can i do to:
 (a) verify thatIi am not doing something terribly wrong ?
 (b) help further diagnose and ameliorate this issue ?

For reference:
https://github.com/jlgerber/tanky

controls 
LMB + UP accelerate
LMB + DOWN decelerate 
LMB + LEFT Turn Left
LMB + RIGHT turn right

**Comment by amberkowalski** [comment] 2020-11-30 19:27
What GPU driver are you running on linux? Please check if you're not 110% positive.

**Comment by jlgerber** [comment] 2020-11-30 20:31
Here are the results of running nvidia-smi:
NVIDIA-SMI 455.38       Driver Version: 455.38       CUDA Version: 11.1

**Comment by cart** [comment] 2020-12-01 20:48
I regularly run Bevy on a very similar setup (linux + decent nvidia card + proprietary drivers) and I also experience that "jankiness". Fortunately (or perhaps unfortunately for us) I think the issue is largely scoped to that specific setup. 

I think there are two issues here:

1. Window resize responsiveness
    * This appears to be a general nvidia "vulkan driver" or "wgpu vulkan implementation" issue.
    * Window resizing **_isn't_** buttery smooth when I use the vulkan backend with my nvidia card, both on Windows and Linux
    * Window resizing **_is_** buttery smooth for me with basically every other configuration:
         * same Nvidia card, but using the DX12 backend on windows
         * Metal backend + Nvidia on my macbook pro (late 2013)
2. Hitching / skipping happening during the game
    * This appears to be exclusive to Linux + Nvidia + Vulkan. I haven't encountered it on any other configuration
    * Its inconsistent for me (ex: i havent been able to repro since I rebooted from testing on windows). 
    * I haven noticed this hitching on my Linux/Nvidia setup with other engine. When I was developing my game High Hat (which used Godot / OpenGL es 3.0), I also had hitching.  Notably, I _didn't_ encounter it when I ran the game in KDE Plasma (with the same nvidia driver), but I _did_ encounter it in Gnome 3. I noticed you are running Pop OS, which defaults to Gnome 3. I'd be curious to hear if you can repro on Plasma.

Obligatory @kvark ping, just so he is aware. I'm not sure yet if there is anything actionable here (other than maybe investigating the "vulkan window resize" jank).

**Comment by kvark** [comment] 2020-12-01 21:29
Thank you for pinging! I'd recommend trying out different [present modes](https://github.com/gfx-rs/wgpu/blob/2d87fd9067e6600beea494f83aa27955b0c8e100/wgpu-types/src/lib.rs).

**Comment by amberkowalski** [comment] 2020-12-01 21:42
Weirdly mailbox doesn't work on my machine :(

**Comment by cart** [comment] 2020-12-01 21:56
Yeah it doesn't work on any of my machines either / falls back to fifo:
  * Desktop: nvidia gtx 1070 (both on linux and windows)
  * MacBook: nvidia GT 750m (macos)

Heres a quick video demo of the various modes / how they affect resize performance (recorded on my desktop running linux):

1. breakout Immediate/no vsync: not much jank
2. breakout Fifo / vsync: jank
3. built in GTK3 app (with breakout still running with vsync in the background): jank
4. built in GTK3 app (with breakout closed): no jank

In order of least janky to most janky: 4, 1, 2, 3

[resize_test.zip](https://github.com/bevyengine/bevy/files/5625683/resize_test.zip)

**Comment by kvark** [comment] 2020-12-01 22:05
Is your threading predetermined? I.e. I wonder if you are hitting some locking issues, which would be seen in a CPU profile.
Also, perhaps somebody affected could try running `shadow` and `water` examples from wgpu-rs to see if there is any junk observed there.

**Comment by cart** [comment] 2020-12-01 22:23
> Is your threading predetermined?

We do single-threaded rendering right now because of this wgpu memory leak: https://github.com/gfx-rs/wgpu/issues/651.


> perhaps somebody affected could try running shadow and water examples from wgpu-rs to see if there is any junk observed there

Ok so the water example (on wgpu-rs master) doesn't have jank (with PresentMode::Fifo).

I have two theories now:
1. We are currently running everything (game logic and render logic) in winit's Event:MainEventsCleared. The water example does game logic in Event::MainEventsCleared, calls window.request_redraw(), then does rendering in Event::RedrawRequested.
2. We need to update to wgpu master :smile: (which we can't do because we need to use crates.io releases)

(1) seems like a good lead. It will require some restructuring on our part, so I can't test it quickly. Do you think that might be the cause?

**Comment by cart** [comment] 2020-12-01 22:33
I also did some CPU profiling. It does look like one thread starts hanging during resize (red lines indicate me starting/stopping a bunch of resizes):

![image](https://user-images.githubusercontent.com/2694663/100804659-21586a00-33e2-11eb-8187-f5407edfc8ca.png)

**Comment by cart** [comment] 2020-12-01 22:42
Ok this is maddening. Now i can't repro the resize jank in bevy w/ Fifo (it behaves the same as Immediate). I'm seeing the wgpu fallback warnings, so its definitely getting applied. I did run a `cargo update`. Maybe that fixed something?

@jlgerber can you run `cargo update` in your repo and see if that does anything?

**Comment by cart** [comment] 2020-12-02 05:45
Looks like the "hitching" might be coming from mutter (which gnome shell relies on)
https://gitlab.gnome.org/GNOME/mutter/-/issues/1516

**Comment by CleanCut** [comment] 2021-03-25 01:28
It looks like the fix in the linked issue was merged two weeks ago. 🎉

**Comment by zicklag** [comment] 2021-03-31 18:44
I'm getting a periodic jank in my game using Bevy with a custom OpenGL renderer on Gnome 3.36.4 ( which shouldn't be related to the linked Gnome bug above because the post said that it Gnome 3.36 ran fine ).

I'm on a high-end Linux machine with an Nvidia card, but I'm running the game on the Mesa driver ( because I've got the hybrid GPU mode that uses mesa by default unless I specifically run an app "With Dedicated GPU" ).

That seems to point maybe to the winit ` Event:MainEventsCleared` suspicion you had @cart . Or I've got an entirely different problem, I'm not sure.

**Comment by cart** [comment] 2021-03-31 21:33
Yup I still have the same problem with windowed hardware accelerated games in gnome and I have basically the same setup.

**Comment by adsick** [comment] 2023-04-06 10:36
I have crashes when resizing windows on nvidia. It resizes for a coupule of seconds, very choppy and with wide black borders on the sides, and then the whole laptop freezes and I need to force shutdown it.

OS: Fedora 37, gnome wayland (Bevy runs on x11 via xWayland as running on nvidia + wayland does not open the window)
HW: mobile Nvidia RTX 3060, Ryzen 5 5600H, 16Gb ram

when I use `PowerPreference::LowPower` it runs on integrated Vega and everything is fine (great work, Nvidia)

**Comment by alice-i-cecile** [comment] 2024-01-09 17:21
This is too old to be helpful: closing out. If you can reproduce or isolate this further, please open a new issue.

**Closed by alice-i-cecile** 2024-01-09 17:21 UTC
Labels: O-Linux, C-Performance
