### ISSUE TITLE
Regression: System schedule doesn't update (?) if a window isn't visible.

### ISSUE THREAD

**Issue by brandon-reinhart** [bevyengine/bevy#14144] opened 2024-07-05 04:27 UTC
## Bevy version

0.14

## What's Up?!?

If you run the window_settings example, you'll not see a window. The make_visible system only runs once. Ran into this in my own game. You don't get any systems updating after that first tick if the window isn't visible. This means you can't wait N frames before showing the window to avoid displaying a white screen.

**Comment by mockersf** [comment] 2024-07-05 07:29
Duplicate of https://github.com/bevyengine/bevy/issues/14135

**Closed** 2024-07-05 07:29 UTC
Labels: C-Bug, S-Needs-Triage
