### ISSUE TITLE
could not compile bevy_render

### ISSUE THREAD

**Issue by rookieWanZ** [bevyengine/bevy#5044] opened 2022-06-18 15:06 UTC
## Bevy version
0.8.0
The release number or commit hash of the version you're using.
8b27124a801d83a1e92f1136ebd2bc9752c3e9d7
## \[Optional\] Relevant system information
WIN10
Msys2
rustc 1.60.0
cargo 1.60.0

After I git the newest bevy
Then "cargo run --example breakout"

it rolls out the error info as following:
----------------------------------------------------------------------

  Compiling bevy_render v0.8.0-dev (E:\Cmder_Project\bevy\bevy\crates\bevy_render)
error[E0658]: trait bounds other than `Sized` on const fn parameters are unstable
  --> crates\bevy_render\src\render_resource\buffer_vec.rs:17:6
   |
17 | impl<T: Pod> BufferVec<T> {
   |      ^
18 |     pub const fn new(buffer_usage: BufferUsages) -> Self {
   |     ---------------------------------------------------- function declared as const here
   |
   = note: see issue #93706 <https://github.com/rust-lang/rust/issues/93706> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `bevy_render` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed

Admin@DESKTOP-3SIKCVE MINGW64 /e/Cmder_Project/bevy/bevy
# cargo run --example breakout
   Compiling bevy_render v0.8.0-dev (E:\Cmder_Project\bevy\bevy\crates\bevy_render)
error[E0658]: trait bounds other than `Sized` on const fn parameters are unstable
  --> crates\bevy_render\src\render_resource\buffer_vec.rs:17:6
   |
17 | impl<T: Pod> BufferVec<T> {
   |      ^
18 |     pub const fn new(buffer_usage: BufferUsages) -> Self {
   |     ---------------------------------------------------- function declared as const here
   |
   = note: see issue #93706 <https://github.com/rust-lang/rust/issues/93706> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `bevy_render` due to previous error

**Comment by DJMcNab** [comment] 2022-06-18 15:07
Duplicate of https://github.com/bevyengine/bevy/issues/4862

Please update your rust version using `rustup update`

**Closed** 2022-06-18 15:17 UTC
Labels: C-Bug, S-Duplicate, S-User-Error
