### ISSUE TITLE
WGPU error on switching materials with normal prepass

### ISSUE THREAD

**Issue by johnbchron** [bevyengine/bevy#9402] opened 2023-08-09 20:58 UTC
## Bevy version

v0.11.0

## \[Optional\] Relevant system information

- Rust Version: `1.73.0-nightly (d78bbf4bd 2023-08-03)`
- OS: arch-ish
- Adapter info: `AdapterInfo { name: "Intel(R) HD Graphics 520 (SKL GT2)", vendor: 32902, device: 6422, device_type: IntegratedGpu, driver: "Intel open-source Mesa driver", driver_info: "Mesa 23.0.4", backend: Vulkan }`

## What you did

To reproduce, set up a 3D camera with a `NormalPrepass` component on it. Define a custom material that uses a WGSL fragment. Spawn a scene (I'm not sure what data is important here, but it doesn't work with just a cube; might be UVs), and then set up a system to switch out the `StandardMaterial` for a `CustomMaterial` on any entity that has a `StandardMaterial`. Bevy crashes.

Minimum reproducible [here](https://github.com/johnbchron/bevy_prepass_bug).

## What went wrong

This error occurs:
```
2023-08-09T20:52:12.883651Z ERROR wgpu::backend::direct: Handling wgpu errors as fatal by default
thread 'Compute Task Pool (1)' panicked at /home/jlewis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.16.3/src/backend/direct.rs:3019:5:
wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
      note: label = `prepass_pipeline`
    Error matching ShaderStages(FRAGMENT) shader requirements against the pipeline
    Location[2] is provided by the previous stage output but is not consumed as input by this stage.


note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `bevy_render::render_resource::pipeline_cache::PipelineCache::process_pipeline_queue_system`!
thread 'Compute Task Pool (0)' panicked at /home/jlewis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_render-0.11.0/src/pipelined_rendering.rs:135:45:
called `Result::unwrap()` on an `Err` value: RecvError
```

## Additional information

Honestly no clue :(

**Comment by thebeastxdxd** [comment] 2023-10-02 15:37
hey, im thinking of working on this issue. Able to reproduce the problem on my machine with your example!

**Comment by thebeastxdxd** [comment] 2023-10-02 16:40
hey, still working on it but it looks like it specifically doesn't work with the `SceneBundle`. you can also easily recreate the behavior 
on the `load_gltf.rs` example.

**Comment by johnbchron** [comment] 2023-10-03 17:32
How interesting. Thanks for working on it!

I forgot to include this in the original comment but my workaround was to manually specify the prepass shader from the PBR implementation like so:
```rust
impl Material for CustomMaterial {
  ...

  fn prepass_fragment_shader() -> ShaderRef {
    StandardMaterial::prepass_fragment_shader()
  }
}
```

**Comment by thebeastxdxd** [comment] 2023-10-03 18:38
cool! that makes a lot of sense, @IceSentry figured out the reason! `FragmentInput` in the default `prepass.wgsl` was missing 
the `VERTEX_TANGENT`. Fixed it by using `VertexOutput` instead.

**Comment by IceSentry** [comment] 2023-10-13 19:36
This should now be fixed on main after the deferred PR.

**Closed by IceSentry** 2023-10-13 19:36 UTC
Labels: C-Bug, A-Rendering
