### ISSUE TITLE
Build failure on Windows 10 when adding `DefaultPlugins`

### ISSUE THREAD

**Issue by plof27** [bevyengine/bevy#1148] opened 2020-12-24 21:13 UTC
**Bevy version** 0.4

**Operating system & version**

Windows 10 Professional 64-bit

**What you did**

Attempted running the simple hello world app with DefaultPlugins added. Code:

```rust
use bevy::prelude::*;

fn main() {
    App::build()
        .add_plugins(DefaultPlugins)
        .run();
}
```

**What actually happened**

Project failed to compile, siting `error: linking with link.exe failed: exit code: 1120`
Full console output: [link_error.txt](https://github.com/bevyengine/bevy/files/5740525/link_error.txt)

**Additional information**

@DJMcNab Suspected an issue with [glsl-to-spirv](https://crates.io/crates/glsl-to-spirv)

**Comment by DJMcNab** [comment] 2020-12-24 21:37
Probable duplicate of https://github.com/bevyengine/bevy/issues/788

**Comment by plof27** [comment] 2020-12-24 21:54
Looks like I was able to fix my issue. The problem was that I had VS 2017 with game build tools, but VS 2019 without game build tools. The system (apparently) defaults to the newest version, but will supplement with an older version if available. However, these two versions of VS are not compatible, hence the linking error.

**Closed** 2020-12-24 21:55 UTC
