### ISSUE TITLE
2D transforms

### ISSUE THREAD

**Issue by BenjaminBrienen** [bevyengine/bevy#16438] opened 2024-11-19 22:29 UTC
> Had a sneaky bug where I calculated the distance between two sprites’ translations, which almost does what you want in 2D but can be subtly wrong if they have z values set. 2D transforms would be great!

Originally posted by @msvanberg on discord

https://discord.com/channels/691052431525675048/1203087353850364004/1307912730300383242

**Comment by alice-i-cecile** [comment] 2024-11-19 22:38
Duplicate of #2548 :) This is a long-standing request, and getting it right will require a working group.

**Closed by alice-i-cecile** 2024-11-19 22:38 UTC
Labels: C-Feature, A-Math, D-Modest
