### ISSUE TITLE
Fog crashes on certain mobile devices in WASM

### ISSUE THREAD

**Issue by oscrim** [bevyengine/bevy#8506] opened 2023-04-27 12:16 UTC
## Bevy version

670f3f0dce2ced27388b10672d30594d399434e1

## Relevant system information

```ignore
`AdapterInfo { name: "Adreno (TM) 660", vendor: 20803, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Gl }`
```

## What you did

I ran a basic 3D Shapes example on WASM on my phone. 

## What went wrong

I expected the example the example to run like it did on my computer but instead it crashes with the error
```ignore
Shader translation error for stage VERTEX | FRAGMENT | VERTEX_FRAGMENT:  log.target = "wgpu::backend::direct";log.module_path = "wgpu::backend::direct";
```
```ignore
panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
      note: label = `pbr_opaque_mesh_pipeline`
    Internal error in VERTEX | FRAGMENT | VERTEX_FRAGMENT shader: 
```

## Additional information

I first asked about it on your discord [here](https://discord.com/channels/691052431525675048/1100763202201075773).

Using `git bisect` I was able to find the commit that introduced the bug which is 1a96d820fdfd0bb303b2555169cd45a6a194195e. 

Further by removing the lines
```wgsl
    if (fog.mode != FOG_MODE_OFF && (material.flags & STANDARD_MATERIAL_FLAGS_FOG_ENABLED_BIT) != 0u) {
        output_color = apply_fog(output_color, in.world_position.xyz, view.world_position.xyz);
    }
```
in `pbr.wgsl`, in `bevy_pbr`, the example once again runs on my phone.

What is interesting however is that my colleague ran it on his phone without issue, his adapter info is the following.
```ignore
AdapterInfo { name: "Mali-G78", vendor: 5045, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Gl }
```

Furthermore I tried running it on my tablet which also crashes, I unfortunately cannot read logs from the tablet but it uses the `Adreno 619` GPU.

**Comment by oscrim** [comment] 2023-04-27 12:50
After some more testing Ive found that removing 
```ignore
scattering += pow(
                max(
                    dot(view_to_world_normalized, light.direction_to_light),
                    0.0
                ),
                fog.directional_light_exponent
            ) * light.color.rgb;
```
from `apply_fog` in `pbr_functions.wgsl` also makes the example run

**Comment by oscrim** [comment] 2023-04-27 13:19
@coreh Do you have any idea what could be the issue?

**Comment by coreh** [comment] 2023-04-28 03:51
Unfortunately, I don't... Can you try removing specific parts of that expression to see what could be tripping up the shader compiler?

Like the `dot()`, or the `pow()`, or specific terms within them?

**Comment by oscrim** [comment] 2023-04-28 06:59
I have tried it on Chrome and Firefox without success. I tried removing both without any success, still crashes when only doing
```ignore
scattering += light.color.rgb;
```

**Comment by oscrim** [comment] 2023-04-28 07:51
Also found out that after removing the scattering, transparency is also broken as shown here when running the transparency_3d example. You can see when the shadows disappear is when the object is supposed to be completely see-through. 

https://user-images.githubusercontent.com/17007091/235087632-1a2a8583-84ac-4c18-914f-4b4f3c94df96.mp4

**Comment by TotalKrill** [comment] 2023-04-28 08:15
I assume this is actually the same or similar bug as in #8047 and maybe #4582. The common theme seems to be that Adreno chipset, so I assume there is something that the adreno does differently. Looking at where they landed with the issues, it also seems that the WGSL stuff is actually the error. 

This issue has gone throught the git bisect though and has narrowed down basically the lines of wgsl code that seems to break. I dont know if the same lines would fix the other issues, or even if both issues should still be open

**Comment by TotalKrill** [comment] 2023-04-28 09:08
@coreh Since you have some more experience with WGSL than us, could you point us in a direction on how we could proceed in trying to debug this? Basically now, we are just acting like monkeys and adding removing, snippets of code from that, recompiling the bevy examples and loading them on the phone. But the only feedback we get is basically works/not works. Its, a bit suboptimal...

Can one get some debug information out from what crashes, I am working on the assumptions that the Adreno chipsets (very common it seems) are to blame. 

from the the https://github.com/gfx-rs/naga/issues/2292#issuecomment-1485202833, it seems this could be a workaround: 
```
At least some adreno compilers don't like returning an element of a UBO array that is a structure in the vertex shader. To work this around we have to copy the each of the structure fields.
```

however I do not know how to proceed in doing that

**Comment by oscrim** [comment] 2023-04-28 09:51
it turns out that changing it to 

```ignore
            //let light = lights.directional_lights[i];
            scattering += pow(
                max(
                    0.0,
                    0.0
                ),
                fog.directional_light_exponent
            ) * vec3<f32>(1.0);
```

also makes the example run

**Comment by oscrim** [comment] 2023-04-28 12:02
Another update, the shader will run without modification with the following change in `light.rs`

```rust
pub const MAX_DIRECTIONAL_LIGHTS: usize = 1;
```

A value of 2 or more will cause the crash

**Comment by coreh** [comment] 2023-04-29 19:33
Hmm. What I don't fully understand is if the problem is the amount of directional lights, and they are being read from elsewhere in the code (within the lighting code) why does only the read in the fog code cause the translation issue, and not the other one?

**Comment by gnargfu** [comment] 2023-05-10 21:56
Working with @TotalKrill I've looked into this and from what I've found is that the data seems to be mangled at some point. I have as of yet not been able to determine precisely where that is as my knowledge of shaders, wgpu, bevy, naga and the Adreno architecture is quite infantile as of yet. 

I managed to fix the issue with the transparency by moving the standard alpha blending bitflags to be lower in the u32 holding them. This tells me that there is probably something going on with how the wgsl gets the data. But were in the chain of things it happens is beyond me at this time. In the end I just added the fix that was proposed for this (limiting the directional lights) as a feature that can be added if the end user is targeting mobile webgl.

**Comment by gnargfu** [comment] 2023-05-11 18:38
It seems as though the Adreno series are alone in having an alignment of 64 bytes. According to the 'best practices' on the Qualcomm developer network each UBO should be no more than 8k. Even though they report that the maxUniformBufferRange is 65536 I've seen comments stating that the driver reports an inaccurate value and people are getting anomalies in the data much sooner. With 10 lights we are currently at 13120 bytes (aligned) which should be safe but that is the lights alone. I'm currently trying to understand the pipeline to see exactly how much is stuffed into the buffer in our examples.

**Closed** 2023-06-29 05:00 UTC
Labels: C-Bug, A-Rendering, C-Crash
