### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by caperaven** [bevyengine/bevy#4511] opened 2022-04-17 20:30 UTC
https://dev-docs.bevyengine.org/bevy/app/bevy_ecs::schedule::Schedule

gives me a 404

followed the link from this page
https://dev-docs.bevyengine.org/bevy/app/struct.ScheduleRunnerPlugin.html

**Comment by mockersf** [comment] 2022-04-17 20:37
related to https://github.com/bevyengine/bevy/issues/3654 and https://github.com/rust-lang/rust/issues/81979

**Comment by vedant-z** [comment] 2022-06-21 09:48
@caperaven how to fix this 
Can I try?

**Comment by hintron** [comment] 2022-09-29 02:23
I think this should be marked as a dup of #3654.

It appears that many (or all?) inter-crate doc links are broken in this same way. It also appears to be a rustdoc bug, so I'm not sure if there is anything we can do about it in Bevy. Rust analyzer confirms that it's a valid doc link, but rustdoc doesn't convert it properly. So it makes it a local link to the current crate, which fails with 404.

**Comment by james7132** [comment] 2024-03-23 22:34
Closing as this as a duplicate of #3654, which looks to be resolved now.

**Closed by james7132** 2024-03-23 22:34 UTC
Labels: C-Bug, C-Docs
