### ISSUE TITLE
Extending the number of system parameters

### ISSUE THREAD

**Issue by billyb2** [bevyengine/bevy#3267] opened 2021-12-06 12:56 UTC
## What problem does this solve or what need does it fill?

Currently, Bevy has a hard cap on how many queries and resources a specific system can access. Whether this is on purpose or just an arbitrary limit I don't fully know. I've been getting around this limit by splitting large systems into several smaller ones, though for a specific setup system I have created it's pretty difficult to be able to do that. Raising the cap by even 5 more queries / resources would help me significantly in having complex setups.

## What solution would you like?

Either raising the limit on Bevy systems, or maybe making a way to query several unrelated resources at once.

## What alternative(s) have you considered?

I know that breaking my systems into smaller systems is usually the way to go, it just becomes difficult with increasingly complex setups.

## Additional context

Any other information you would like to add such as related previous work,
screenshots, benchmarks, etc.

**Comment by nicopap** [comment] 2021-12-06 13:02
Using `#[derive(SystemParam)]` helps with that. It enables putting several parameters in a single struct. Though I'm not sure it works in `0.5` :V

**Comment by Davier** [comment] 2021-12-06 13:09
Tuples of system parameters are considered as system parameters, so you can have as many parameters by nesting them in tuples.

**Comment by TheRawMeatball** [comment] 2021-12-06 13:14
Fundamentally, this is caused by rust's lack of variadic tuples, and this limitation causes problems elsewhere as well, such as `Clone` only being implemented for only up to 16-tuples. Luckily, there are various ways around this limitation:
* Using `#[derive(SystemParam)]` you can implement the `SystemParam` trait for your structs. Example: 
```rs
#[derive(SystemParam)]
struct MySystemParam<'w, 's> {
    res: Res<'w, SomeResource>,
    query: Query<'w, 's, &SomeComponent>,
}

fn my_system(params: MySystemParam, alternate_res: Res<SomeOtherRes>) {}
```
You can put an unlimited amount of system parameters in the struct.
* Using nested systemparam tuples: all tuples up to 16-tuples where all fields are system parameters are also valid system parameters, and coincidentally you can put tuples inside other tuples, getting an arbitrary number of system parameters:
```rs
fn my_system(params: (Res<Something>, (Query<&Stuff>, (/* and here you can just keep going*/)))) {}
```

**Comment by billyb2** [comment] 2021-12-06 13:30
Thank you, should I close this?

**Comment by mockersf** [comment] 2021-12-06 14:09
We could run the macros on tuples to a higher number behind a feature flag, like [diesel does for large number of columns](https://github.com/diesel-rs/diesel/blob/bcd32c897e35b60b9e7d6231e98c5006b340e9ef/diesel/Cargo.toml#L50-L54). Keeping the default at 16 but allowing users to have more at the cost of increased compile time

**Comment by TheRawMeatball** [comment] 2021-12-06 15:10
Closing this issue for now, we could open a separate issue for having such a feature flag later on.

**Closed by TheRawMeatball** 2021-12-06 15:10 UTC
Labels: C-Enhancement, A-ECS

**Comment by cart** [comment] 2021-12-07 01:09
Good call. I think making this configurable might even be an anti-feature. Better to have everyone working around the same constraints than having a free for all in the ecosystem.
