### ISSUE TITLE
Mysterious crash if you run .init_state before adding DefaultPlugins now ! 

### ISSUE THREAD

**Issue by ethereumdegen** [bevyengine/bevy#14363] opened 2024-07-17 16:09 UTC
## Bevy version

The release number or commit hash of the version you're using.

0.14 

(this did not occur in 0.13 ) 

 Mysterious crash if you run .init_state before adding DefaultPlugins now ! 
 
 Caused by : 
 ```
 in main branch: https://github.com/bevyengine/bevy/blob/main/crates/bevy_state/src/app.rs#L72-L74
GitHub
[bevy/crates/bevy_state/src/app.rs at main · bevyengine/bevy](https://github.com/bevyengine/bevy/blob/main/crates/bevy_state/src/app.rs)
A refreshingly simple data-driven game engine built in Rust - bevyengine/bevy
bevy/crates/bevy_state/src/app.rs at main · bevyengine/bevy

            let schedule = self.get_schedule_mut(StateTransition).expect(
                "The `StateTransition` schedule is missing. Did you forget to add StatesPlugin or DefaultPlugins before calling init_state?"
            );
            
     ```
     
     
     RECOMMEND:  Make this error message more obvious, give users more warning of this   change in 0.14

**Comment by alice-i-cecile** [comment] 2024-07-17 16:10
Duplicate of #14154, which has already been resolved on `main`.

**Closed by alice-i-cecile** 2024-07-17 16:10 UTC
Labels: C-Bug, S-Needs-Triage
