### ISSUE TITLE
missing fields `grid_auto_columns`, `grid_auto_flow`, `grid_auto_rows` in `taffy::prelude::Style` when building bevy_ui

### ISSUE THREAD

**Issue by CPTblackadder** [bevyengine/bevy#9289] opened 2023-07-27 13:04 UTC
## Bevy version
bevy = "0.11.0"

## \[Optional\] Relevant system information

If you cannot get Bevy to build or run on your machine, please include:

- the Rust version you're using (you can get this by running `cargo --version`)
- cargo 1.71.0 (cfd3bbd8f 2023-06-08)
- the operating system or browser used, including its version
  - Windows 10

## What you did
Try to build a project with bevy as a dependency

## What went wrong
I get this error:
error[E0063]: missing fields `grid_auto_columns`, `grid_auto_flow`, `grid_auto_rows` and 5 other fields in initializer of `taffy::prelude::Style`
  --> C:\Users\rob\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ui-0.10.1\src\flex\convert.rs:99:5
   |
99 |     taffy::style::Style {
   |     ^^^^^^^^^^^^^^^^^^^ missing `grid_auto_columns`, `grid_auto_flow`, `grid_auto_rows` and 5 other fields

The taffy version I'm compiling is    `Compiling taffy v0.3.12`
I have tried all suggestions in https://bevy-cheatbook.github.io/pitfalls/build-errors.html

**Comment by alice-i-cecile** [comment] 2023-07-27 17:58
Duplicate of https://github.com/bevyengine/bevy/issues/9274; you have duplicate versions of Bevy in tree.

**Closed by alice-i-cecile** 2023-07-27 17:58 UTC
Labels: A-UI
