### ISSUE TITLE
Better error handling for systems

### ISSUE THREAD

**Issue by musjj** [bevyengine/bevy#11562] opened 2024-01-27 15:09 UTC
## What problem does this solve or what need does it fill?

Handling `Result<T, E>` inside systems currently feels a bit awkward. The few options we have right now:

- Call `.unwrap()` everywhere. This feels very unidiomatic in Rust.
- Write custom log messages everywhere. This feels very boilerplaty for what could've been a single `?`.
- Have your system return `Result<T, E>`, then `.pipe()` it into [`bevy::utils::{warn, error, ...}`](https://github.com/bevyengine/bevy/blob/main/examples/ecs/system_piping.rs).

I'm liking the third option the most. But the problem is that the log messages does not include any traceback information whatsoever, such as the name of the system where the error originated from. This makes it very hard to debug.

## What solution would you like?

The usability of `bevy::utils::{warn, error, ...}` should be improved to make it easier to work with.

Or maybe there should be a built-in support for systems that returns `Result<T, E>`.

**Comment by nicopap** [comment] 2024-01-27 15:22
Another option is to use [`bevy_mod_sysfail`](https://crates.io/crates/bevy_mod_sysfail) (disclaimer, I am the author)

**Comment by nicopap** [comment] 2024-01-27 15:30
This has been discussed extensively in the past. I'm surprised you are actually the first to open an issue regarding error handling in bevy systems.

The best you are likely to get for now are the pipe error handling systems and `bevy_mod_sysfail`.

Regarding the traceback in the pipe error handling systems, there is an open issue: #8638

**Comment by musjj** [comment] 2024-01-27 15:38
Thanks for the crate! I tried it out and the log messages now displays the module the error originated from, which is way better than the default `.pipe()`. But it still does not log the actual name of the system. Is there a way to configure this?

**Comment by nicopap** [comment] 2024-01-27 16:46
A future release will automatically add the system name to the log message. It's going to be published early next week, see https://github.com/nicopap/bevy_mod_sysfail/pull/5

**Comment by nicopap** [comment] 2024-01-28 12:28
I'm closing this as a Duplicate of #10874 since it's really just asking for the same thing.

**Closed by nicopap** 2024-01-28 12:28 UTC
Labels: C-Enhancement, A-ECS, C-Usability
