### ISSUE TITLE
Many Foxes shadows vibrate

### ISSUE THREAD

**Issue by hymm** [bevyengine/bevy#7393] opened 2023-01-28 05:49 UTC
## Bevy version

happens after the cascaded shadow map pr c3a46822e14003970e2de0ea20ca09839a64d913

## Relevant system information

```text
AdapterInfo { name: "NVIDIA GeForce RTX 3070 Ti Laptop GPU", vendor: 4318, device: 9376, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "517.63", backend: Vulkan }
SystemInfo { os: "Windows 11 Pro", kernel: "22621", cpu: "AMD Ryzen 9 6900HS with Radeon Graphics", core_count: "8", memory: "31.3 GiB" }
```

## What you did

ran the `many_foxes` example

## What went wrong

The shadows feel like they are vibrating. Looking at a freeze frame the shadows seem to be much lower resolution than before.

After CSM
<img width="963" alt="image" src="https://user-images.githubusercontent.com/2180432/215248559-0daadc13-fc96-47df-93ed-46add7624a85.png">

Before CSM
<img width="962" alt="image" src="https://user-images.githubusercontent.com/2180432/215248611-8672454d-c436-466a-aa07-255f54415d8c.png">

**Comment by alice-i-cecile** [comment] 2023-01-28 07:20
Is this fixed by #7383? I fixed an ambiguity there that is very plausibly responsible.

**Comment by djeedai** [comment] 2023-01-28 08:01
I think this might be fixed by #7339 no?

**Comment by rparrett** [comment] 2023-01-28 14:01
Not sure if this is related, but I am seeing an intermittent error in `many_foxes` only in a CI/lavapipe environment:

```rust
2023-01-28T05:30:58.278983Z ERROR wgpu::backend::direct: Handling wgpu errors as fatal by default    
thread '<unnamed>' panicked at 'wgpu error: Validation Error

Caused by:
    In a RenderPass
      note: encoder = `<CommandBuffer-(0, 2, Vulkan)>`
    In a draw command, indexed:false indirect:false
      note: render pipeline = `shadow_pipeline`
    the pipeline layout, associated with the current render pipeline, contains a bind group layout at index 1 which is incompatible with the bind group layout associated with the bind group at 1

', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.14.2/src/backend/direct.rs:2403:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', crates/bevy_render/src/pipelined_rendering.rs:144:45
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/runner/work/prototype_bevy_example_runner/prototype_bevy_example_runner/bevy/crates/bevy_tasks/src/task_pool.rs:354:49
```

So far I can't reproduce on real hardware, but thought I'd mention it here in case it's related.

**Comment by superdump** [comment] 2023-01-28 16:13
I looked at this the other day - I got the feeling they weren’t vibrating, it’s just ‘aliasing’ (it visually looks like something other than it is) because the shadows are low resolution, the positions of the shadow map texels are stable, and the foxes cast shadows that move across a small number of these texels so the texels pop in and out of shadow. I may very well be wrong but that is my guess.

@danchia would you be up for looking into this with respect to #7362 ?

**Comment by hymm** [comment] 2023-01-28 17:43
> so the texels pop in and out of shadow

This is what it looks like to me.

**Comment by danchia** [comment] 2023-01-31 04:56
I tweaked the cascades settings, and things look much better.
Will send PR soon, but I'm starting to think that we probably need to change the docs to nudge users to consider their needs. The current default settings _work_ in that there are shadows, but definitely are not one size fits all w.r.t to hugely varying scene sizes.

**Comment by superdump** [comment] 2023-01-31 07:43
@danchia on Discord, @JMS55 had the idea that we could perhaps calculate the screen space aabb of the visible objects in the view frustum and then build cascades covering that.

I’ve seen ideas previously about cascade distribution and things don’t stop at implementing ’basic’ CSM. :) I don’t remember the papers right now as I haven’t thought about post-CSM for a long time.

I feel like a quality slider bounding the worst screen/shadow texel size ratio or something could be useful… or at least to start with understanding the distribution of shadow map resolution over view distances, could be a useful approach to thinking about the shadow quality.

Plus implementing the Witness PCF. :)

**Comment by superdump** [comment] 2023-01-31 14:16
Now I remember - Sample Distribution Shadow Maps: https://github.com/bevyengine/bevy/issues/4253

**Closed** 2023-02-05 08:23 UTC
Labels: C-Bug, A-Rendering
