### ISSUE TITLE
error: linking with `cc` failed: exit status: 1

### ISSUE THREAD

**Issue by nixon-voxell** [bevyengine/bevy#15334] opened 2024-09-20 11:36 UTC
## Bevy version

0.14.2

## What you did

Describe how you arrived at the problem. If you can, consider providing a code snippet or link.

GitHub action failed on bevy_dylib
https://github.com/nixon-voxell/lumina/actions/runs/10958198016/job/30427921562

## What went wrong

```
error: linking with `cc` failed: exit status: 1

  = note: /usr/bin/ld: __rust_realloc: undefined version: 
          /usr/bin/ld: __rust_no_alloc_shim_is_unstable: undefined version: 
          /usr/bin/ld: __rust_dealloc: undefined version: 
          /usr/bin/ld: __rust_alloc_zeroed: undefined version: 
          /usr/bin/ld: __rust_alloc_error_handler_should_panic: undefined version: 
          /usr/bin/ld: __rust_alloc_error_handler: undefined version: 
          /usr/bin/ld: __rust_alloc: undefined version: 
          /usr/bin/ld: failed to set dynamic section sizes: bad value
          collect2: error: ld returned 1 exit status
          
error: could not compile `bevy_dylib` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
```

**Comment by nixon-voxell** [comment] 2024-09-20 12:11
I see, the weird thing is that it works on windows on my machine, it just fails on github actions, which makes it hard to troubleshoot.

**Comment by mockersf** [comment] 2024-09-20 17:11
while ideally it should work, enabling dynamic linking in CI can only lead to problems...

**Comment by nixon-voxell** [comment] 2024-09-22 02:16
I see. I have turned it off for now in my CI. (Tho the original CI from TheBevyFlock/bevy_quickstart enables it). Turning defaul features off makes the CI test works for now.

**Comment by BenjaminBrienen** [comment] 2024-09-25 09:54
Closing as duplicate of #14117

**Closed** 2024-09-25 09:55 UTC
Labels: C-Bug, S-Needs-Triage
