### ISSUE TITLE
Systems running after a conditional system do not follow the condition

### ISSUE THREAD

**Issue by hxYuki** [bevyengine/bevy#8013] opened 2023-03-10 06:11 UTC
## Bevy version

0.10.0

## What you did

Add a system with `run_if`, add another system `after` the system.

e.g.

```rust
.add_systems(
    (
        snake_movement
            .in_schedule(CoreSchedule::FixedUpdate)
            .run_if(on_fixed_timer(Duration::from_secs_f32(0.25))),
        snake_eating
            .after(snake_movement)
            .in_schedule(CoreSchedule::FixedUpdate),
    ),
)
```

## What went wrong

Instinctively, `snake_eating` will not run before `snake_movement` running.
But it was not, 

![image](https://user-images.githubusercontent.com/15306248/224229210-ba9a13aa-dcb5-4425-9733-515ca5a75ebf.png)

## Additional Information

`run_if` on `SystemSet` also tried, it doesn't work with `on_fixed_timer`.

**Comment by james7132** [comment] 2023-03-10 08:44
IMO this is expected behavior. Run conditions are local to the systems/sets they're applied to, and systems should be able to run if their dependencies didn't (i.e. if `A` depends on `B` to run, and `B` only runs if resource `C` has changed, `A` may want to run even if `C` hasn't changed).

The solution here might be to make a system set, apply it to both/all systems that are in that group and apply the run condition to the set instead.

**Comment by hxYuki** [comment] 2023-03-10 09:24
> 

As I said in additional, SystemSet didn't work with on_fixed_timer.

```rust
#[derive(SystemSet, Debug, Hash, PartialEq, Eq, Clone)]
enum FixedStepSet {
    Tick,
}
// .... 
.add_systems(
    (snake_movement, snake_eating)
    .chain()
    .in_set(FixedStepSet::Tick)
    .in_schedule(CoreSchedule::FixedUpdate),
)
.configure_set(
    FixedStepSet::Tick
        .in_base_set(CoreSet::FixedUpdate)
        .run_if(on_fixed_timer(Duration::from_secs_f32(0.25))),
)
```
![image](https://user-images.githubusercontent.com/15306248/224274843-f4b81cc5-61de-4e56-9996-367a01bbc27b.png)

Or is there something wrong? It seems I have to handle timer myself and send event for these systems.

Do we have a way more handy?

**Comment by devil-ira** [comment] 2023-03-10 10:37
You're missing an `in_schedule` call in `configure_set`, but I just realized that API is completely missing. Oops.

For now you can do this instead:
```rust
.edit_schedule(CoreSchedule::FixedUpdate, |schedule| {
    schedule
        .add_systems(
            (snake_movement, snake_eating)
                .chain()
                .in_set(FixedStepSet::Tick),
        )
        .configure_set(
            FixedStepSet::Tick.run_if(on_fixed_timer(Duration::from_secs_f32(0.25))),
        );
})
```

PS: `.in_base_set(CoreSet::FixedUpdate)` is not needed. That set doesn't exist inside `CoreSchedule::FixedUpdate`.

**Comment by hxYuki** [comment] 2023-03-10 11:28
That makes sense. I was confused quite a bit.

**Comment by alice-i-cecile** [comment] 2023-03-10 12:17
Yep, this is expected behavior: run conditions *only* control the systems they're attached to, not any dependencies.

This is required, as under the current model you can get both configurations of later systems. Under the proposed model, you'd *never* be able to opt-out of the run conditions of your predecessors. And worse, it would cascade throughout your app.

Closing as intended behavior, but this is still useful to have around for others to be able to search for and see :)

**Closed by alice-i-cecile** 2023-03-10 12:17 UTC
Labels: C-Bug, A-ECS
