### ISSUE TITLE
Panic when minimizing a window (Handling wgpu errors as fatal by default)

### ISSUE THREAD

**Issue by simensgreen** [bevyengine/bevy#1882] opened 2021-04-11 09:53 UTC
## Bevy version
0.5.0
## Operating system & version
Windows 10
## What you did
```rust
use bevy::prelude::*;

fn main() {
    App::build()
        .add_plugins(DefaultPlugins)
        .run();
}
```
- stable rust
> cargo run --color=always --package bevy_test --bin bevy_test
- try to minimize the window

![image](https://user-images.githubusercontent.com/34134129/114299485-26ca6d00-9ac4-11eb-8155-81befe2b6332.png)

## What you expected to happen
The window is minimized

## What actually happened
Panic with: 
```
wgpu error: Validation Error

Caused by:
    In Device::create_texture
    Dimension X is zero


thread 'main' panicked at 'Handling wgpu errors as fatal by default'
```

## Additional information
None

**Comment by simensgreen** [comment] 2021-04-11 10:03
I tried repeating with bevy 0.4.0. The application panics, but in a different way:
```extent state Extent { width: 1, height: 1, depth: 1 } must match extent from view Extent { width: 0, height: 0, depth: 1 }```

**Comment by mockersf** [comment] 2021-04-11 10:15
related to #899 and #170

**Comment by DJMcNab** [comment] 2021-04-11 10:20
#634 was closed as a duplicate of #170. I'd advise following the same path here, although #899 is the better duplicate now.

@simensgreen my understanding of this is that it's a known issue, and we know that it should be easy to solve and isn't revealing a key architectural limitation, so it will get fixed, but noone has fixed it yet.

**Comment by OhhhZenix** [comment] 2021-05-10 21:55
I seem to have the same issue as well when minimizing my app with a similar error message of:
`wgpu error: Validation Error

Caused by:
    In Device::create_texture
    Dimension X is zero


thread 'main' panicked at 'Handling wgpu errors as fatal by default', C:\Users\zenix\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.7.1\src\backend\direct.rs:1896:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

Leaving this comment to hopefully get notified when it is fixed as stated by @DJMcNab.

**Comment by NathanSWard** [comment] 2021-06-03 06:56
Closing as this is a duplicate of 
#170 
#899 
#2018

**Closed by NathanSWard** 2021-06-03 06:56 UTC
Labels: crash, duplicate, windowing
