### ISSUE TITLE
Show warning/prevent calling app .run() in Plugin build method 

### ISSUE THREAD

**Issue by Lucidus115** [bevyengine/bevy#6145] opened 2022-10-02 18:10 UTC
## What problem does this solve or what need does it fill?

Accidentally calling .run() in a plugin's build method prevents other plugins from running correctly. This is because .run() `Finalizes the [App] configuration.` Sometimes one might call this method by mistake and spend hours trying to figure out why most of their app isn't running.

## What solution would you like?

Either a warning informing users of an accidental .run() call or an alternative App struct for plugins to use where .run() is not present. The App's .run() method should only be possible to call in the main app configuration as is intended.

## What alternative(s) have you considered?

- Not accidentally calling .run() in a plugin's build method

**Comment by bjorn3** [comment] 2022-10-02 18:38
Duplicate of https://github.com/bevyengine/bevy/issues/4231 (open PR: https://github.com/bevyengine/bevy/pull/4241)

**Closed by bjorn3** 2022-10-02 18:38 UTC
Labels: C-Enhancement, S-Needs-Triage
