### ISSUE TITLE
Wireframe plugin causes segmentation violation

### ISSUE THREAD

**Issue by bonsairobo** [bevyengine/bevy#1717] opened 2021-03-21 14:27 UTC
## Bevy version

rev = d9fb61d4

## Operating system & version

Arch Linux

```
$ cat /etc/lsb-release 
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=21.0
DISTRIB_CODENAME=Ornara
DISTRIB_DESCRIPTION="Manjaro Linux"
```

## What you did

I have an example running on top of bevy here: https://github.com/bonsairobo/building-blocks/tree/main/examples/lod_terrain

If you go to `lod_terrain.rs` and uncomment the wireframe stuff, then run the example, it will occasionally crash with a segfault.

## What you expected to happen

Not crashing. And it does occasionally run without error. This is a nondeterministic bug.

## What actually happened

Crashed with error:

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/duncan/.cargo/git/checkouts/bevy-f7ffde730c324c74/d9fb61d/crates/bevy_wgpu/src/renderer/wgpu_render_resource_context.rs:560:68
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Mar 21 06:45:18.377 ERROR gpu_descriptor::allocator: `DescriptorAllocator` is dropped while some descriptor sets were not deallocated
Segmentation fault (core dumped)
```

## Additional information

<details><summary>STACK TRACE</summary>
<p>

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/duncan/.cargo/git/checkouts/bevy-f7ffde730c324c74/d9fb61d/crates/bevy_wgpu/src/renderer/wgpu_render_resource_context.rs:560:68
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:50:5
   3: core::option::Option<T>::unwrap
             at /home/duncan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:386:21
   4: <bevy_wgpu::renderer::wgpu_render_resource_context::WgpuRenderResourceContext as bevy_render::renderer::render_resource_context::RenderResourceContext>::create_bind_group::{{closure}}
             at /home/duncan/.cargo/git/checkouts/bevy-f7ffde730c324c74/d9fb61d/crates/bevy_wgpu/src/renderer/wgpu_render_resource_context.rs:560:47
   5: core::iter::adapters::map::map_fold::{{closure}}
             at /home/duncan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/map.rs:80:28
   6: core::iter::traits::iterator::Iterator::fold
             at /home/duncan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:2023:21
   7: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /home/duncan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/map.rs:120:9
   8: core::iter::traits::iterator::Iterator::for_each
             at /home/duncan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:678:9
   9: <alloc::vec::Vec<T,A> as alloc::vec::SpecExtend<T,I>>::spec_extend
             at /home/duncan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec.rs:2568:17
  10: <alloc::vec::Vec<T> as alloc::vec::SpecFromIterNested<T,I>>::from_iter
             at /home/duncan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec.rs:2336:9
  11: <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter
             at /home/duncan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec.rs:2346:9
  12: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /home/duncan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec.rs:2181:9
  13: core::iter::traits::iterator::Iterator::collect
             at /home/duncan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:1670:9
  14: <bevy_wgpu::renderer::wgpu_render_resource_context::WgpuRenderResourceContext as bevy_render::renderer::render_resource_context::RenderResourceContext>::create_bind_group
             at /home/duncan/.cargo/git/checkouts/bevy-f7ffde730c324c74/d9fb61d/crates/bevy_wgpu/src/renderer/wgpu_render_resource_context.rs:544:27
  15: bevy_render::renderer::render_resource::render_resource_bindings::RenderResourceBindings::update_bind_group
  16: bevy_render::draw::DrawContext::set_bind_groups_from_bindings_internal
             at /home/duncan/.cargo/git/checkouts/bevy-f7ffde730c324c74/d9fb61d/crates/bevy_render/src/draw.rs:270:21
  17: bevy_render::draw::DrawContext::set_bind_groups_from_bindings
             at /home/duncan/.cargo/git/checkouts/bevy-f7ffde730c324c74/d9fb61d/crates/bevy_render/src/draw.rs:242:9
  18: bevy_render::wireframe::draw_wireframes_system::{{closure}}
             at /home/duncan/.cargo/git/checkouts/bevy-f7ffde730c324c74/d9fb61d/crates/bevy_render/src/wireframe/mod.rs:103:9
  19: core::iter::traits::iterator::Iterator::for_each::call::{{closure}}
             at /home/duncan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:675:29
  20: core::iter::traits::iterator::Iterator::fold
             at /home/duncan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:2023:21
  21: core::iter::traits::iterator::Iterator::for_each
             at /home/duncan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:678:9
  22: bevy_render::wireframe::draw_wireframes_system
             at /home/duncan/.cargo/git/checkouts/bevy-f7ffde730c324c74/d9fb61d/crates/bevy_render/src/wireframe/mod.rs:118:9
  23: core::ops::function::Fn::call
             at /home/duncan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:70:5
  24: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &F>::call_mut
             at /home/duncan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:247:13
  25: <Func as bevy_ecs::system::into_system::IntoSystem<(A,B,C,D,E),bevy_ecs::system::into_system::FuncSystem<Out>>>::system::{{closure}}
             at /home/duncan/.cargo/git/checkouts/bevy-f7ffde730c324c74/d9fb61d/crates/bevy_ecs/src/system/into_system.rs:259:38
  26: bevy_ecs::schedule::executor_parallel::ParallelExecutor::prepare_systems::{{closure}}
             at /home/duncan/.cargo/git/checkouts/bevy-f7ffde730c324c74/d9fb61d/crates/bevy_ecs/src/schedule/executor_parallel.rs:244:30
  27: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/duncan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  28: async_executor::Executor::spawn::{{closure}}
             at /home/duncan/.cargo/registry/src/github.com-1ecc6299db9ec823/async-executor-1.4.0/src/lib.rs:138:13
  29: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/duncan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  30: async_task::raw::RawTask<F,T,S>::run
             at /home/duncan/.cargo/registry/src/github.com-1ecc6299db9ec823/async-task-4.0.3/src/raw.rs:489:20
  31: async_executor::Executor::try_tick
             at /home/duncan/.cargo/registry/src/github.com-1ecc6299db9ec823/async-executor-1.4.0/src/lib.rs:175:17
  32: bevy_tasks::task_pool::TaskPool::scope::{{closure}}
             at /home/duncan/.cargo/git/checkouts/bevy-f7ffde730c324c74/d9fb61d/crates/bevy_tasks/src/task_pool.rs:221:21
  33: std::thread::local::LocalKey<T>::try_with
             at /home/duncan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:272:16
  34: std::thread::local::LocalKey<T>::with
             at /home/duncan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:248:9
  35: bevy_tasks::task_pool::TaskPool::scope
             at /home/duncan/.cargo/git/checkouts/bevy-f7ffde730c324c74/d9fb61d/crates/bevy_tasks/src/task_pool.rs:169:9
  36: <bevy_ecs::schedule::executor_parallel::ParallelExecutor as bevy_ecs::schedule::executor::ParallelSystemExecutor>::run_systems
             at /home/duncan/.cargo/git/checkouts/bevy-f7ffde730c324c74/d9fb61d/crates/bevy_ecs/src/schedule/executor_parallel.rs:169:9
  37: <bevy_ecs::schedule::stage::SystemStage as bevy_ecs::schedule::stage::Stage>::run
             at /home/duncan/.cargo/git/checkouts/bevy-f7ffde730c324c74/d9fb61d/crates/bevy_ecs/src/schedule/stage.rs:592:13
  38: bevy_ecs::schedule::Schedule::run_once
             at /home/duncan/.cargo/git/checkouts/bevy-f7ffde730c324c74/d9fb61d/crates/bevy_ecs/src/schedule/mod.rs:198:13
  39: <bevy_ecs::schedule::Schedule as bevy_ecs::schedule::stage::Stage>::run
             at /home/duncan/.cargo/git/checkouts/bevy-f7ffde730c324c74/d9fb61d/crates/bevy_ecs/src/schedule/mod.rs:209:21
  40: bevy_winit::winit_runner_with::{{closure}}
             at /home/duncan/.cargo/git/checkouts/bevy-f7ffde730c324c74/d9fb61d/crates/bevy_winit/src/lib.rs:486:17
  41: winit::platform_impl::platform::sticky_exit_callback
             at /home/duncan/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/mod.rs:736:5
  42: winit::platform_impl::platform::x11::EventLoop<T>::run_return
             at /home/duncan/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/x11/mod.rs:303:17
  43: winit::platform_impl::platform::x11::EventLoop<T>::run
             at /home/duncan/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/x11/mod.rs:398:9
  44: winit::platform_impl::platform::EventLoop<T>::run
             at /home/duncan/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/mod.rs:652:56
  45: winit::event_loop::EventLoop<T>::run
             at /home/duncan/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/event_loop.rs:154:9
  46: bevy_winit::run
             at /home/duncan/.cargo/git/checkouts/bevy-f7ffde730c324c74/d9fb61d/crates/bevy_winit/src/lib.rs:170:5
  47: bevy_winit::winit_runner_with
             at /home/duncan/.cargo/git/checkouts/bevy-f7ffde730c324c74/d9fb61d/crates/bevy_winit/src/lib.rs:494:9
  48: bevy_winit::winit_runner
             at /home/duncan/.cargo/git/checkouts/bevy-f7ffde730c324c74/d9fb61d/crates/bevy_winit/src/lib.rs:210:5
  49: core::ops::function::Fn::call
             at /home/duncan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:70:5
  50: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /home/duncan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:1342:9
  51: bevy_app::app::App::run
             at /home/duncan/.cargo/git/checkouts/bevy-f7ffde730c324c74/d9fb61d/crates/bevy_app/src/app.rs:66:9
  52: bevy_app::app_builder::AppBuilder::run
             at /home/duncan/.cargo/git/checkouts/bevy-f7ffde730c324c74/d9fb61d/crates/bevy_app/src/app_builder.rs:50:9
  53: lod_terrain::main
             at ./examples/lod_terrain/lod_terrain.rs:27:5
  54: core::ops::function::FnOnce::call_once
             at /home/duncan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
```

</p>
</details>

**Comment by alice-i-cecile** [comment] 2021-03-21 16:22
Given the nondeterminism, I wonder if this is a system ordering issue.

**Comment by mockersf** [comment] 2021-03-21 16:38
I also have this issue.

Related to #1609 that should have been fixed by #1623

**Comment by bonsairobo** [comment] 2021-03-21 16:43
@mockersf Awesome! Sorry I did not see this. I will try updating to that fix revision and see how it goes.

**Comment by bonsairobo** [comment] 2021-03-21 17:13
OK I updated to 785aad92 and now I'm getting a different stack:

```
thread 'main' panicked at 'Requested resource does not exist', /Users/duncan/.cargo/git/checkouts/bevy-f7ffde730c324c74/785aad9/crates/bevy_ecs/src/system/system_param.rs:374:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   2: core::option::expect_failed
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/option.rs:1260:5
   3: <(P0,P1,P2,P3) as bevy_ecs::system::system_param::SystemParamFetch>::get_param
   4: <Func as bevy_ecs::system::into_system::SystemParamFunction<(),Out,(F0,F1,F2,F3),()>>::run
             at /Users/duncan/.cargo/git/checkouts/bevy-f7ffde730c324c74/785aad9/crates/bevy_ecs/src/system/into_system.rs:188:41
   5: <bevy_ecs::system::into_system::FunctionSystem<In,Out,Param,Marker,F> as bevy_ecs::system::system::System>::run_unsafe
             at /Users/duncan/.cargo/git/checkouts/bevy-f7ffde730c324c74/785aad9/crates/bevy_ecs/src/system/into_system.rs:142:9
   6: bevy_ecs::schedule::executor_parallel::ParallelExecutor::prepare_systems::{{closure}}
             at /Users/duncan/.cargo/git/checkouts/bevy-f7ffde730c324c74/785aad9/crates/bevy_ecs/src/schedule/executor_parallel.rs:200:30
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /Users/duncan/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
   8: async_executor::Executor::spawn::{{closure}}
             at /Users/duncan/.cargo/registry/src/github.com-1ecc6299db9ec823/async-executor-1.4.0/src/lib.rs:138:13
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /Users/duncan/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  10: async_task::raw::RawTask<F,T,S>::run
             at /Users/duncan/.cargo/registry/src/github.com-1ecc6299db9ec823/async-task-4.0.3/src/raw.rs:489:20
  11: async_executor::Executor::try_tick
             at /Users/duncan/.cargo/registry/src/github.com-1ecc6299db9ec823/async-executor-1.4.0/src/lib.rs:175:17
  12: bevy_tasks::task_pool::TaskPool::scope::{{closure}}
             at /Users/duncan/.cargo/git/checkouts/bevy-f7ffde730c324c74/785aad9/crates/bevy_tasks/src/task_pool.rs:222:21
  13: std::thread::local::LocalKey<T>::try_with
             at /Users/duncan/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/thread/local.rs:272:16
  14: std::thread::local::LocalKey<T>::with
             at /Users/duncan/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/thread/local.rs:248:9
  15: bevy_tasks::task_pool::TaskPool::scope
             at /Users/duncan/.cargo/git/checkouts/bevy-f7ffde730c324c74/785aad9/crates/bevy_tasks/src/task_pool.rs:169:9
  16: <bevy_ecs::schedule::executor_parallel::ParallelExecutor as bevy_ecs::schedule::executor::ParallelSystemExecutor>::run_systems
             at /Users/duncan/.cargo/git/checkouts/bevy-f7ffde730c324c74/785aad9/crates/bevy_ecs/src/schedule/executor_parallel.rs:121:9
  17: <bevy_ecs::schedule::stage::SystemStage as bevy_ecs::schedule::stage::Stage>::run
             at /Users/duncan/.cargo/git/checkouts/bevy-f7ffde730c324c74/785aad9/crates/bevy_ecs/src/schedule/stage.rs:602:13
  18: bevy_ecs::schedule::Schedule::run_once
             at /Users/duncan/.cargo/git/checkouts/bevy-f7ffde730c324c74/785aad9/crates/bevy_ecs/src/schedule/mod.rs:201:13
  19: <bevy_ecs::schedule::Schedule as bevy_ecs::schedule::stage::Stage>::run
             at /Users/duncan/.cargo/git/checkouts/bevy-f7ffde730c324c74/785aad9/crates/bevy_ecs/src/schedule/mod.rs:212:21
  20: bevy_ecs::schedule::Schedule::run_once
             at /Users/duncan/.cargo/git/checkouts/bevy-f7ffde730c324c74/785aad9/crates/bevy_ecs/src/schedule/mod.rs:201:13
  21: <bevy_ecs::schedule::Schedule as bevy_ecs::schedule::stage::Stage>::run
             at /Users/duncan/.cargo/git/checkouts/bevy-f7ffde730c324c74/785aad9/crates/bevy_ecs/src/schedule/mod.rs:212:21
  22: bevy_winit::winit_runner_with::{{closure}}
             at /Users/duncan/.cargo/git/checkouts/bevy-f7ffde730c324c74/785aad9/crates/bevy_winit/src/lib.rs:485:17
  23: <alloc::boxed::Box<F,A> as core::ops::function::FnMut<Args>>::call_mut
             at /Users/duncan/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/alloc/src/boxed.rs:1335:9
  24: <winit::platform_impl::platform::app_state::EventLoopHandler<T> as winit::platform_impl::platform::app_state::EventHandler>::handle_nonuser_event
             at /Users/duncan/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/macos/app_state.rs:71:9
  25: winit::platform_impl::platform::app_state::Handler::handle_nonuser_event
             at /Users/duncan/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/macos/app_state.rs:173:21
  26: winit::platform_impl::platform::app_state::AppState::cleared
             at /Users/duncan/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/macos/app_state.rs:331:13
  27: ____CFXPCCreateCFObjectFromXPCObject_block_invoke
  28: ___CFRunLoopObserverCancel
  29: ___CFRunLoopRun
  30: ___CFTSRToDispatchTime
  31: _RunCurrentEventLoopInMode
  32: _ReceiveNextEventCommon
  33: __BlockUntilNextEventMatchingListInModeWithFilter
  34: __DPSNextEvent
  35: -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]
  36: -[NSApplication run]
  37: <() as objc::message::MessageArguments>::invoke
             at /Users/duncan/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/mod.rs:128:17
  38: objc::message::platform::send_unverified
             at /Users/duncan/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/apple/mod.rs:27:9
  39: objc::message::send_message
             at /Users/duncan/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/mod.rs:178:5
  40: winit::platform_impl::platform::event_loop::EventLoop<T>::run_return
             at /Users/duncan/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/macos/event_loop.rs:106:25
  41: winit::platform_impl::platform::event_loop::EventLoop<T>::run
             at /Users/duncan/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/macos/event_loop.rs:93:9
  42: winit::event_loop::EventLoop<T>::run
             at /Users/duncan/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/event_loop.rs:154:9
  43: bevy_winit::run
             at /Users/duncan/.cargo/git/checkouts/bevy-f7ffde730c324c74/785aad9/crates/bevy_winit/src/lib.rs:171:5
  44: bevy_winit::winit_runner_with
             at /Users/duncan/.cargo/git/checkouts/bevy-f7ffde730c324c74/785aad9/crates/bevy_winit/src/lib.rs:493:9
  45: bevy_winit::winit_runner
             at /Users/duncan/.cargo/git/checkouts/bevy-f7ffde730c324c74/785aad9/crates/bevy_winit/src/lib.rs:211:5
  46: core::ops::function::Fn::call
             at /Users/duncan/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:70:5
  47: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /Users/duncan/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/alloc/src/boxed.rs:1342:9
  48: bevy_app::app::App::run
             at /Users/duncan/.cargo/git/checkouts/bevy-f7ffde730c324c74/785aad9/crates/bevy_app/src/app.rs:68:9
  49: bevy_app::app_builder::AppBuilder::run
             at /Users/duncan/.cargo/git/checkouts/bevy-f7ffde730c324c74/785aad9/crates/bevy_app/src/app_builder.rs:48:9
  50: lod_terrain::main
             at ./examples/lod_terrain/lod_terrain.rs:28:5
  51: core::ops::function::FnOnce::call_once
             at /Users/duncan/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
```

**Comment by Neo-Zhixing** [comment] 2021-03-23 18:55
@bonsairobo  I wasn't able to compile the example - I will try again later, but can you put some `println!` in [draw_wireframes_system](https://github.com/bevyengine/bevy/blob/47004dfcb415a049e4c6e68fdf56c26de72f51a1/crates/bevy_render/src/wireframe/mod.rs#L64) and in [draw_render_pipelines_system](https://github.com/bevyengine/bevy/blob/47004dfcb415a049e4c6e68fdf56c26de72f51a1/crates/bevy_render/src/pipeline/render_pipelines.rs#L91)? We might be able to find some relationships between "if it's going to crash" and "does the draw_wireframe_system run before the main pipeline or after"

**Comment by bonsairobo** [comment] 2021-03-23 19:40
Oh yea I guess there is a broken dependency in bevy right now. I will do a little debugging later today hopefully when I can build bevy again.

**Comment by bonsairobo** [comment] 2021-03-28 00:03
Sorry I had a busy end of my week. But I just did a little debugging.

There does not appear to be a correlation between the system ordering and the crash.

When it crashes:

```
draw_wireframes_system
draw_render_pipelines_system
draw_wireframes_system
draw_render_pipelines_system
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value'
```

When it succeeds:

```
draw_wireframes_system
draw_render_pipelines_system
draw_wireframes_system
draw_render_pipelines_system
draw_wireframes_system
draw_render_pipelines_system
draw_wireframes_system
draw_render_pipelines_system
...
```

**Comment by mockersf** [comment] 2021-04-09 23:37
While trying to remove parts of my game to reach a minimum reproducer, here is what I found:
```rust
use bevy::{
    prelude::*,
    render::wireframe::{Wireframe, WireframePlugin},
    wgpu::{WgpuFeature, WgpuFeatures, WgpuOptions},
};

fn main() {
    App::build()
        .insert_resource(Msaa { samples: 4 })
        .insert_resource(WgpuOptions {
            features: WgpuFeatures {
                features: vec![WgpuFeature::NonFillPolygonMode],
            },
            ..Default::default()
        })
        .add_plugins(DefaultPlugins)
        .add_plugin(WireframePlugin)
        .add_startup_system(setup.system())
        .run();
}

fn setup(mut commands: Commands, mut meshes: ResMut<Assets<Mesh>>, asset_server: Res<AssetServer>) {
    commands.spawn_scene(asset_server.load("models/AlienCake/cakeBirthday.glb#Scene0"));

    commands
        .spawn_bundle(PbrBundle {
            mesh: meshes.add(Mesh::from(shape::Cube { size: 1.0 })),
            transform: Transform::from_xyz(0.0, 0.5, 0.0),
            ..Default::default()
        })
        .insert(Wireframe);

    commands.spawn_bundle(PerspectiveCameraBundle {
        transform: Transform::from_xyz(-2.0, 2.5, 5.0).looking_at(Vec3::ZERO, Vec3::Y),
        ..Default::default()
    });
}
```
This code crashes almost every time for me.
* If I don't spawn the scene, it won't crash
* If I don't add the `Wireframe` component, it won't crash

**Comment by wdcocq** [comment] 2021-05-21 14:13
I ran into this issue as well and what i gathered so far is that after a resize of the buffer array it sometimes still tried to use the old buffer, which causes the panic.

The order of the draw systems (after the buffer resize) doesn't matter. I've seen it crash either way.

when I comment out this line in : [render_resource_bindings#L146](https://github.com/bevyengine/bevy/blob/653c10371e546176059bb779844c0569c0190b6b/crates/bevy_render/src/renderer/render_resource/render_resource_bindings.rs#L146) I don't get the panic anymore.
So it seems that it sometimes gets removed from the dirty bindings before actually being rebuild. Probably because of the two pipelines reusing the same resource? I'm not too familiar with the whole rendering back-end stuff, so I don't know exactly what's going one. I just hope this helps..

**Comment by james7132** [comment] 2022-03-21 01:01
@bonsairobo: Is this still an issue? This was before the 0.6 render rework was done. If it isn't reproducible, please close this issue.

**Comment by mockersf** [comment] 2022-03-21 08:59
not reproducible for me 🎉

**Closed** 2022-03-21 16:14 UTC
Labels: A-Rendering, C-Crash
