### ISSUE TITLE
PBR broken on HEAD on macOS (metal)

### ISSUE THREAD

**Issue by djeedai** [bevyengine/bevy#3434] opened 2021-12-25 19:41 UTC
## Bevy version

HEAD (22c665fa)

## Operating system & version

macOS 10.13 High Sierra

## What you did

- clone repo
- `cargo run --example 3d_scene`

## What you expected to happen

Example runs.

## What actually happened

Example panics at first frame.

## Additional information

```
     Running `target/debug/examples/3d_scene`
2021-12-25T18:39:06.582187Z  INFO bevy_render::renderer: AdapterInfo { name: "NVIDIA GeForce GT 750M", vendor: 0, device: 0, device_type: DiscreteGpu, backend: Metal }
2021-12-25T18:39:06.987290Z ERROR wgpu::backend::direct: Handling wgpu errors as fatal by default    
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
      note: label = `pbr_opaque_mesh_pipeline`
    Internal error in VERTEX shader: Metal: Compilation failed: 

program_source:18:5: error: unknown type name 'packed_float3'
    packed_float3 world_position;
    ^
program_source:35:5: error: unknown type name 'packed_float3'
    packed_float3 direction_to_light;
    ^
program_source:101:3: error: type 'const constant View &' is not valid for attribute 'buffer'
, constant View& view [[buffer(0)]]
  ^                     ~~~~~~~~~
program_source:101:12: note: type 'View' cannot be used in buffer pointee type
, constant View& view [[buffer(0)]]
           ^
program_source:134:25: warning: unused variable 'in'
    const FragmentInput in = { is_front, varyings_1.world_position, varyings_1.world_normal, varyings_1.uv };
                        ^


', .cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.12.0/src/backend/direct.rs:2273:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by djeedai** [comment] 2021-12-25 19:43
I said "PBR broken" because it seems other features work (I was writing a custom pipeline converted from the Sprite one, and that seemed to work). But as soon as I add some `PbrBundle` things fall over.

Ping @cart for visibility since you asked for new renderer feedback before 0.6.

**Comment by cart** [comment] 2021-12-25 19:44
Hmmm I have that exact GPU on my macbook. Lets see if I can repro.

**Comment by cart** [comment] 2021-12-25 19:54
It works for me on Big Sur. Maybe the problem is that you're using a four-year-old version of macos? (high sierra)

**Comment by djeedai** [comment] 2021-12-25 20:45
Yes I thought about it but couldn't find any info about Metal version support nor any min-spec for naga or bevy.

There's a very similar naga issue here : https://github.com/gfx-rs/naga/issues/999
But it's closed as no-repro after updating, though we're using a more recent version in bevy. I've left a comment anyway, in case there was a mistake and this is indeed a naga bug. It certainly looks like it since other types are prefixed with `metal::` but `packed_float3` isn't.

**Comment by cart** [comment] 2022-02-16 05:50
Closing because this was resolved on the naga side.

**Closed by cart** 2022-02-16 05:50 UTC
Labels: C-Bug, A-Rendering, O-MacOS, S-Needs-Investigation
