### ISSUE TITLE
did_propagate test is flaky

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#6036] opened 2022-09-20 18:23 UTC
Example failure: https://github.com/bevyengine/bevy/actions/runs/3092436459/jobs/5003700386

Output:

> failures:
>
> ---- systems::test::did_propagate stdout ----
> thread 'systems::test::did_propagate' panicked at 'assertion failed: `(left == right)`
>   left: `0v0`,
>  right: `2v0`: Malformed hierarchy. This probably means that your hierarchy has been improperly maintained, or contains a cycle', crates/bevy_transform/src/systems.rs:69:9
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> 
> 
> failures:
>     systems::test::did_propagate

This is a recurrence of https://github.com/bevyengine/bevy/issues/4996, caused by the sibling test that panics.

**Comment by mockersf** [comment] 2022-09-20 18:42
Duplicate of #5285

**Comment by targrub** [comment] 2022-10-05 13:24
CI fail https://github.com/bevyengine/bevy/actions/runs/3189837176/jobs/5204126980 likely the same issue.  https://github.com/bevyengine/bevy/commit/2a6b544a0aa3471b0abb185a367cb25b98042912

**Comment by mockersf** [comment] 2022-10-05 13:32
closing for https://github.com/bevyengine/bevy/issues/5285

**Closed as completed by mockersf** 2022-10-05 13:32 UTC
Labels: C-Bug, A-Build-System, C-Code-Quality, A-Tasks
