### ISSUE TITLE
`Camera::viewport_to_world` docs do not explain optionality behavior

### ISSUE THREAD

**Issue by xJinyoung** [bevyengine/bevy#8048] opened 2023-03-11 21:43 UTC
## How can Bevy's documentation be improved?

The docs for [`Camera::viewport_to_world`](https://docs.rs/bevy/latest/bevy/render/camera/struct.Camera.html#method.viewport_to_world) shows that the function has return type `Option<Ray>` but does not explain when the function call can fail.

Bevy 0.9 release has usage [examples](https://bevyengine.org/news/bevy-0-9/#camera-viewport-to-world) but does not express when it is safe to `unwrap`.

Documentation should explain when the function call can fail.

**Comment by alice-i-cecile** [comment] 2023-03-11 21:56
Here's the current link to the source code: https://github.com/bevyengine/bevy/blob/abcb0661e3cc546434450f2ace1578078451ae43/crates/bevy_render/src/camera/camera.rs#L247

It appears that this is `None` when any of:

1.  The `logical_viewport_size` is `None`.
2. The near plane cannot be computed.
3. The far plane cannot be computed.

Generally speaking I would use an `if let Some` pattern here rather than unwrapping: I would expect unwrapping to panic when the window is minimized or in pathological camera positions.

**Comment by devil-ira** [comment] 2023-03-11 22:19
This is a duplicate of #7171

**Closed** 2023-03-11 23:41 UTC
Labels: C-Docs, D-Good-First-Issue, A-Rendering
