### ISSUE TITLE
Pixel wide gaps between adjacent UI nodes 

### ISSUE THREAD

**Issue by ickshonpe** [bevyengine/bevy#7712] opened 2023-02-16 20:33 UTC
## Bevy version

main

## What you did

<img width="539" alt="gap" src="https://user-images.githubusercontent.com/27962798/219480483-da1a19c0-af62-48ad-9cae-5d2ca84785b8.PNG">

```rust
use bevy::prelude::*;

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_startup_system(setup)
        .run();
}

fn setup(mut commands: Commands) {
    let w = 100.3;
    commands.spawn(Camera2dBundle::default());
    commands.spawn(NodeBundle {
        style: Style {          
            flex_direction: FlexDirection::Column,  
            align_items: AlignItems::Center,
            size: Size::new(Val::Px(963.3333), Val::Percent(100.)),
            ..Default::default()
        },
        background_color: BackgroundColor(Color::WHITE),
        ..Default::default()
    })
    .with_children(|parent| {
        parent.spawn(NodeBundle {
            style: Style {
                justify_content: JustifyContent::Center,
                size: Size::new(Val::Percent(100.), Val::Percent(50.)),
                ..Default::default()
            },
            ..Default::default()
        })
        .with_children(|commands| {
            commands.spawn(
                NodeBundle {
                    style: Style {
                        size: Size::width(Val::Px(w)),
                        ..Default::default()
                    },
                    background_color: BackgroundColor(Color::NAVY),
                    ..Default::default()
                },
            );
            commands.spawn(
                NodeBundle {
                    style: Style {
                        size: Size::width(Val::Px(w)),
                        ..Default::default()
                    },
                    background_color: BackgroundColor(Color::DARK_GRAY),
                    ..Default::default()
                },
            );
        });
        parent.spawn(NodeBundle {
            style: Style {            
                justify_content: JustifyContent::Center,
                size: Size::new(Val::Px(w * 2.), Val::Percent(25.)),
                ..Default::default()
            },
            background_color: BackgroundColor(Color::RED),
            ..Default::default()
        });
    });    
}
```

A pixel-wide gap appears between adjacent nodes at certain node sizes.

The same gap appears vertically if you modify the example to reverse the flex-direction.

**Comment by ickshonpe** [comment] 2023-02-17 11:23
I think this is probably Taffy related. It seems to round the length of certain nodes but not others.
There are subtle problems with Bevy UI Text that are the same

What I think is happening is that you ask for a width of x pixels for your text with the MeasureFunc, but then Taffy rounds it down a pixel and so the Text no longer fits the width, so the last word of the text gets pushed down to a new line. But the Node itself stays at a height of only one line of text, so the text renderer doesn't draw the second line of text and it just looks there are missing words at the end of sentences with certain text layouts.

**Comment by nicoburns** [comment] 2023-02-17 17:30
Hmm... I feel like the text renderer probably shouldn't count a glyph as fitting if it requires a partial pixel.

>  I think this is probably Taffy related. It seems to round the length of certain nodes but not others.

Taffy's rouding is pretty simple. It computes the entire layout using floats, and then rounds everything at the end.

**Comment by ickshonpe** [comment] 2023-02-17 17:45
I haven't really looked at this deeply yet, so I might be completely off. The scale factor code is all over the place, it might be something there. I'll recreate some of my examples just in Taffy and see what happens.

**Comment by ickshonpe** [comment] 2023-02-18 12:34
```rust
use taffy::prelude::*;

fn main() {
    for width in [963.3333, 1000.] {
        example(width);
    }
}

fn example(width: f32) {
    let root_style = Style {
        flex_direction: FlexDirection::Column,
        align_items: AlignItems::Center,
        size: Size { width: Dimension::Points(width), height: Dimension::Points(100.) },
        ..Default::default()
    };

    let parent_style = Style {
        flex_direction: FlexDirection::Row,
        justify_content: JustifyContent::Center,
        size: Size { width: Dimension::Percent(1.), height: Dimension::Points(100.) },
        ..Default::default()
    };

    let child_style = Style {
        size: Size { width: Dimension::Points(100.3), height: Dimension::Auto },
        ..Default::default()
    };
    
    let mut taffy = Taffy::new();
    let children = [
        taffy.new_leaf(child_style).unwrap(),
        taffy.new_leaf(child_style).unwrap(),
    ];
    let parent = taffy.new_with_children(parent_style, &children).unwrap();
    let root = taffy.new_with_children(root_style, &[parent]).unwrap();

    taffy.compute_layout(root, Size::MAX_CONTENT).ok();

    println!("Width = {width}");
    println!("root size: {:#?}", taffy.layout(root).unwrap().size);
    println!("parent size: {:#?}", taffy.layout(parent).unwrap().size);
    for child in children {
        println!("child layout: {:#?}", taffy.layout(child).unwrap());
    }
    println!();
}
```

Output:
```
Width = 963.3333
root size: Size {
    width: 963.0,
    height: 100.0,
}
parent size: Size {
    width: 963.0,
    height: 100.0,
}
child layout: Layout {
    order: 0,
    size: Size {
        width: 100.0,
        height: 100.0,
    },
    location: Point {
        x: 381.0,
        y: 0.0,
    },
}
child layout: Layout {
    order: 1,
    size: Size {
        width: 100.0,
        height: 100.0,
    },
    location: Point {
        x: 482.0,
        y: 0.0,
    },
}

Width = 1000
root size: Size {
    width: 1000.0,
    height: 100.0,
}
parent size: Size {
    width: 1000.0,
    height: 100.0,
}
child layout: Layout {
    order: 0,
    size: Size {
        width: 100.0,
        height: 100.0,
    },
    location: Point {
        x: 400.0,
        y: 0.0,
    },
}
child layout: Layout {
    order: 1,
    size: Size {
        width: 100.0,
        height: 100.0,
    },
    location: Point {
        x: 500.0,
        y: 0.0,
    },
}
```

There is a one-unit gap with a width of 963.3333 that vanishes at a width of 1000.

**Comment by A-Walrus** [comment] 2023-02-18 12:50
I was able to reproduce in Taffy 0.3.2 as well:
```rust
use taffy::prelude::*;

fn main() {
    // First create an instance of Taffy
    let mut taffy = Taffy::new();

    let w = 100.3;

    let w_square = Size {
        width: points(w),
        height: points(w),
    };
    let child_a = taffy
        .new_leaf(Style {
            size: w_square,
            ..Default::default()
        })
        .unwrap();

    let child_b = taffy
        .new_leaf(Style {
            size: w_square,
            ..Default::default()
        })
        .unwrap();

    let root_node = taffy
        .new_with_children(
            Style {
                size: Size {
                    width: points(963.3333),
                    height: points(1000.),
                },
                justify_content: Some(JustifyContent::Center),
                ..Default::default()
            },
            &[child_a, child_b],
        )
        .unwrap();

    taffy.compute_layout(root_node, Size::MAX_CONTENT).unwrap();

    let layout_a = taffy.layout(child_a).unwrap();
    let layout_b = taffy.layout(child_b).unwrap();
    assert_eq!(
        layout_a.location.x + layout_a.size.width,
        layout_b.location.x
    );
}

```

**Comment by nicoburns** [comment] 2023-02-19 21:28
I can see why this is happening. Unrounded results for @A-Walrus's test:

```
TREE
└──  FLEX [x: 0    y: 0    width: 963.3333 height: 1000] (3v1)
    ├──  LEAF [x: 381.36664 y: 0    width: 100.3 height: 100.3] (1v1)
    └──  LEAF [x: 481.66663 y: 0    width: 100.3 height: 100.3] (2v1)
```

child_a's x position is going to get rounded down. child_b's x position is going to get rounded up. It's not immediately obvious to me what the correct solution is though. Especially as I suspect the ideal solution would take into account the `devicePixelRatio` and round based on the size of physical pixels rather than logical ones, and perhaps even do subpixel rendering.

This quote quite neatly sums up the problem:

>  We’re trying to meet a bunch of constraints that can’t all be satisfied at the same time (the proof is left as an exercise to the reader, though I may have actually written it out once in a Bugzilla comment):
> 1. 4 adjacent objects of width/height 25% (for example) starting at one edge of a container should end exactly at the other edge; there should never be an extra pixel in the container and they should never be wrapped due to being a pixel to wide
> 2. objects that are logically adjacent should always touch visually; there should never be a pixel gap or a pixel of overlap due to rounding error
> 3. objects given the same width should occupy the same number of pixels
> 4. object boundaries should always (visually) be aliased to a specific pixel boundary in the display (they should never be blurred)
> 
> The one [Mozilla] sacrifices is typically (3), except for borders where we sacrifice (1) by rounding the widths to pixel boundaries much earlier.

(https://johnresig.com/blog/sub-pixel-problems-in-css/)

I tried looking into what browsers do, but there seems to be no easy way to tell because they won't give you programatic access to the values used for rendering (`getBoundingClientRect` will give you the unrounded floats, and `offsetLeft`/`offsetWidth` will give you values Taffy is already computing with the 1 pixel gap even though there isn't actually a 1px gap in the final render).

**Comment by ickshonpe** [comment] 2023-02-19 22:58
Yep, I understand now I think, the size of the root node doesn't matter. If you add another node to the example that wraps the two nodes it will be 201 pixels wide, it just depends on how it is aligned as to whether the extra pixel either ends up between or on the side of the two nodes.

**Comment by nicoburns** [comment] 2023-02-25 17:05
This is issue is now fixed in Taffy and can be fixed in Bevy by upgrading to the latest Taffy (`v0.3.3`). This will require https://github.com/bevyengine/bevy/pull/7485 to be merged either first, or as part of the upgrade. The approach in [this branch](https://github.com/bevyengine/bevy/commit/84ac898128bfabb65fe4c814fc7f2f9542e9a84e#diff-ea54819d071882d7cad0d6bca53085597dfbdad16d95080d4f052bed2b332506R33) of disabling the `grid` feature for the initial upgrade is probably a sensible one.

**Closed** 2023-03-04 14:31 UTC
Labels: C-Bug, A-UI
