### ISSUE TITLE
memory leak in keyboard_input_events example

### ISSUE THREAD

**Issue by adsick** [bevyengine/bevy#1804] opened 2021-04-02 20:01 UTC
## Operating system & version

Windows 10

## What you did

run keyboard_input_events example

## What you expected to happen

just working example (it works but memory leaks and then crash)

## What actually happened

memory usage goes beyond imaginable and both acceptable and then it fails, this process takes some time before the actual crash

## Additional information

![image](https://user-images.githubusercontent.com/24528839/113449540-bc9c3300-9406-11eb-9dec-08414951b6af.png)
sorry for russian version of the profiler, but I hope you understand what does it means

also I don't know if it useful, but the console said this
```thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `-2005270523`', C:\Users\vadim\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-backend-dx12-0.7.0\src\device.rs:1032:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\release\examples\keyboard_input_events.exe` (exit code: 1)```
not sure when exactly and why but yeah that's it. 
**hope there are no leaks in Rust code or I don't know what can I rely on then...**

**Comment by alice-i-cecile** [comment] 2021-04-02 20:05
Can you reproduce this using the latest main? We've touched the event code quite a bit, and I would like to see if this is going to occur for 0.5 too.

**Comment by adsick** [comment] 2021-04-02 20:16
sorry if sounds a bit dumb, but I can't figure out how to get the latest main. I did a ```gh repo clone bevyengine/bevy``` yesterday and that is what I have for now. I don't know how to distinct between different branches or versions of a repo (my exp with git is small)

**Comment by alice-i-cecile** [comment] 2021-04-02 20:26
Ah, no worries :) Git is an obtuse tool. When you're using Bevy in your own project, you can add the following line to your cargo.toml

```rs
bevy = { git="https://github.com/bevyengine/bevy" , branch = "main"} 

# For using a specific named version.
# bevy = 0.4
```

A basic clone (like what you seem to have done) on the repo itself will end up cloning the default branch: in this case, main.

Following these [instructions](https://www.techiedelight.com/clone-specific-tag-with-git/), you should be able to do:

```
git clone https://github.com/bevyengine/bevy
git checkout tags/v0.4.0
```

Personally, I use [GitKraken](https://www.gitkraken.com/), which provides a very nice free GUI for working with Git. You might find it easier to visualize what's happening and discover new options and tools :)

**Comment by DJMcNab** [comment] 2021-04-02 22:28
We think this will be fixed by https://github.com/gfx-rs/wgpu/pull/1267, but that isn't in a `wgpu` release. Since we are right on the doorstep of 0.5, basically we'll have to say that the dx12 backend can't reasonably be used on some hardware in bevy 0.5 programs. This might be fixed in a 0.5.1 or some later update which updates to wgpu 0.8, whenever that is released.

**Comment by adsick** [comment] 2021-04-07 07:39
> We think this will be fixed by [gfx-rs/wgpu#1267](https://github.com/gfx-rs/wgpu/pull/1267), but that isn't in a `wgpu` release. Since we are right on the doorstep of 0.5, basically we'll have to say that the dx12 backend can't reasonably be used on some hardware in bevy 0.5 programs. This might be fixed in a 0.5.1 or some later update which updates to wgpu 0.8, whenever that is released.

yeah, but can I switch to Vulkan backend on Windows? if so, how to do it?

**Comment by mockersf** [comment] 2021-04-18 15:24
this should have been fixed after a dependency update, could you check after a `cargo update`?

**Comment by adsick** [comment] 2021-04-18 15:31
Compiling...

**Comment by adsick** [comment] 2021-04-18 15:40
So I did cargo update and I see that memory usage is ok (or growths, but slowly, yt is what I see in load_gltf example)) the bad thing is artifacts are the same

**Comment by mockersf** [comment] 2021-04-18 16:32
thanks for checking!

**Comment by alice-i-cecile** [comment] 2021-04-18 18:32
I'm going to close this now :) We can open up a new issue for the artifacts if there isn't one already.

**Closed by alice-i-cecile** 2021-04-18 18:32 UTC
Labels: bug, needs-triage
