### ISSUE TITLE
State systems with FixedTimestep

### ISSUE THREAD

**Issue by lufog** [bevyengine/bevy#3700] opened 2022-01-16 16:48 UTC
## Bevy version
0.6.0 (crates.io)

## Operating system & version
Windows 11 21H2

## What you did
I'm new to Bevy and ESC, so maybe I'm doing something wrong. I'm trying to figure out how to work with states, so I created several, and added systems to each of them.

<details>
  <summary>Code (spoiler)</summary>
 
```Rust
use bevy::prelude::*;

#[derive(Debug, Clone, Eq, PartialEq, Hash)]
enum GlobalState {
    FirstState,
    SecondState,
}

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        // Init state
        .add_state(GlobalState::FirstState)
        // First state systems
        .add_system_set(
            SystemSet::on_enter(GlobalState::FirstState).with_system(first_state::enter_system),
        )
        .add_system_set(
            SystemSet::on_update(GlobalState::FirstState).with_system(first_state::update_system),
        )
        // Second state systems
        .add_system_set(
            SystemSet::on_enter(GlobalState::SecondState).with_system(second_state::enter_system),
        )
        .add_system_set(
            SystemSet::on_update(GlobalState::SecondState).with_system(second_state::update_system),
        )
        .run()
}

mod first_state {
    pub fn enter_system() {
        println!("First state: Enter");
    }

    pub fn update_system() {
        println!("First state: Update");
    }
}

mod second_state {
    pub fn enter_system() {
        println!("Second state: Enter");
    }

    pub fn update_system() {
        println!("Second state: Update");
    }
}
```

</details>

The output looks normal, each system only runs when its associated state is active.

```
First state: Enter
First state: Update
...
First state: Update
```

But if I add `FixedTimestep` run criteria to systems.

<details>
  <summary>Code (spoiler)</summary>
 
```Rust
use bevy::{core::FixedTimestep, prelude::*};

#[derive(Debug, Clone, Eq, PartialEq, Hash)]
enum GlobalState {
    FirstState,
    SecondState,
}

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        // Init state
        .add_state(GlobalState::FirstState)
        // First state systems
        .add_system_set(
            SystemSet::on_enter(GlobalState::FirstState)
                .with_system(first_state::enter_system)
                .with_run_criteria(FixedTimestep::step(1.0)),
        )
        .add_system_set(
            SystemSet::on_update(GlobalState::FirstState)
                .with_system(first_state::update_system)
                .with_run_criteria(FixedTimestep::step(1.0)),
        )
        // Second state systems
        .add_system_set(
            SystemSet::on_enter(GlobalState::SecondState)
                .with_system(second_state::enter_system)
                .with_run_criteria(FixedTimestep::step(1.0)),
        )
        .add_system_set(
            SystemSet::on_update(GlobalState::SecondState)
                .with_system(second_state::update_system)
                .with_run_criteria(FixedTimestep::step(1.0)),
        )
        .run()
}

mod first_state {
    pub fn enter_system() {
        println!("First state: Enter");
    }

    pub fn update_system() {
        println!("First state: Update");
    }
}

mod second_state {
    pub fn enter_system() {
        println!("Second state: Enter");
    }

    pub fn update_system() {
        println!("Second state: Update");
    }
}
```

</details>

Systems are run even if their state is not active.

```
Second state: Update
First state: Enter
First state: Update
Second state: Enter
Second state: Update
First state: Enter
First state: Update
Second state: Enter
Second state: Update
First state: Enter
Second state: Enter
First state: Update
Second state: Update
First state: Enter
Second state: Enter
First state: Update
```

Is this normal behavior? And if yes, how to run systems from some state with fixed time step?

**Comment by alice-i-cecile** [comment] 2022-01-16 16:53
Thanks for making this issue <3

This is a known bug; you haven't done anything wrong, this is a serious, frustrating limitation, and fixing it is such a pain that we're planning to rework our entire scheduling infrastructure and how both states and fixed time steps work to fix it.

To read more, check out https://github.com/bevyengine/rfcs/pull/45 :)

I'm going to close this out as a duplicate of #2233 (but it's hard to discover).

**Closed by alice-i-cecile** 2022-01-16 16:53 UTC
Labels: C-Bug, S-Needs-Triage

**Comment by lufog** [comment] 2022-01-16 17:42
Ok, thanks.
