### ISSUE TITLE
window: (minimize, 0 size, oom) crashes

### ISSUE THREAD

**Issue by NathanSWard** [bevyengine/bevy#2299] opened 2021-06-03 07:06 UTC
There are a set of issues:
#170 
#899
#1664 
#1882
#2018

That all deal with a window crash when either a window is minimized or the size is set the zero. 
All of these issues are related so I'm coalescing them into this issue to centralize discussion here :)

There's been talk that the issue lies withing wgpu, so bevy is unable to do anyting currently about it. 
However, if there is more information please feel free to post here and update the progress of this crash.

**Comment by trolleyman** [comment] 2021-06-03 08:02
The resizing the window to 0-width/height is fixed by https://github.com/bevyengine/bevy/pull/1409, however minimizing the window still causes a crash on Windows, caused by requesting a 0-width/height texture.

Looks like this can be fixed by this comment I left a while back: https://github.com/bevyengine/bevy/issues/170#issuecomment-780186140. I can look at creating a PR with those changes.

**Comment by trolleyman** [comment] 2021-06-03 08:12
Opened https://github.com/bevyengine/bevy/pull/2300 to fix, please review if you can.

**Comment by kotx** [comment] 2021-08-10 17:19
I seem to have the same issue despite the fix.

**Comment by theisen1337** [comment] 2021-12-24 05:51
Is there anyway to catch wgpu errors and resize the window on error? This only happens after I try to reopen a bevy minimized window. So catching the error and increasing the size of the window might work?

**Comment by Ratysz** [comment] 2022-01-25 20:20
This seems to be still happening on 0.6.

**Comment by JulianRuiseco** [comment] 2022-01-25 20:24
Confirmed

`wgpu::backend::direct: Handling wgpu errors as fatal by default    
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In a RenderPass
      note: encoder = `<CommandBuffer-(0, 96372, Vulkan)>`
    In a set_scissor_rect command
    Invalid ScissorRect parameters`

**Comment by Ratysz** [comment] 2022-01-25 21:10
What we're ran into appears to be cause by something downstream from Bevy, so I'll close this again. Sorry for the ruckus.

**Closed by Ratysz** 2022-01-25 21:10 UTC
Labels: C-Bug, A-Window, C-Crash

**Comment by confessore** [comment] 2022-03-01 16:46
experiencing this or similar on window minimize

```
`thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_texture
      note: label = `sampled_color_attachment_texture`
    Dimension X is zero`
```
