### ISSUE TITLE
Wasm file size

### ISSUE THREAD

**Issue by caperaven** [bevyengine/bevy#3978] opened 2022-02-18 09:29 UTC
## What problem does this solve or what need does it fill?

I had a look at the bevy examples on the web and it seems like the wasm file is rather bit.
I was wondering if there is a way / pattern to reduce the binary.
I am still in the evaluation phase, but bevy shows a lot of promise for, just need to trim that wasm file.

## What solution would you like?

Documentation on how to best optimize for the web.

**Comment by jakobhellermann** [comment] 2022-02-18 10:55
There are some tips about optimizing wasm size in the [unofficial bevy cheatbook](https://bevy-cheatbook.github.io/platforms/wasm/size-opt.html).
The short version:
- use some options to optimize more in release mode (`opt-level = 's', lto = 'thin')
- use `wasm-opt` to optimize further (and remove debug info if you want that)
- serve the file compressed (this makes a huge difference!)

```sh
# default options
17M	3d_scene.wasm
12M	3d_scene.wasm.strip
9,9M	3d_scene.wasm.strip.wasm-opt
2,7M	3d_scene.wasm.strip.wasm-opt.gzip
1,7M	3d_scene.wasm.strip.wasm-opt.brotli

# lto = "thin", opt-level = "s"
15M	3d_scene_lto+s.wasm
9,6M	3d_scene_lto+s.wasm.strip
7,6M	3d_scene_lto+s.wasm.strip.wasm-opt
2,1M	3d_scene_lto+s.wasm.strip.wasm-opt.gzip
1,4M	3d_scene_lto+s.wasm.strip.wasm-opt.brotli
```

**Comment by alice-i-cecile** [comment] 2022-04-29 07:30
Closing as a duplicate of #3800.

**Closed by alice-i-cecile** 2022-04-29 07:30 UTC
Labels: C-Docs, C-Performance, O-Web
