### ISSUE TITLE
Some gltf files are immediatly unloaded after being loaded, despite a strong handle stored in a resource

### ISSUE THREAD

**Issue by kaosat-dev** [bevyengine/bevy#10244] opened 2023-10-24 08:33 UTC
## Bevy version
0.11.3

## What you did

I have recurring issues with a lot of gltf files being unloaded immediately after being loaded (checking with ```asset_server.get_load_state```), despite having strong handles stored in a ```Resource```.

- I tried a lot of different gltf & glb files of various sizes, some load, others don't, I haven't found a clear pattern yet
- the issues seem more prevalent with larger glb files, but not 100% consistent
- there is a slight element of randomness, as for some files, on some occasions, will load despite not working most of the time
- I removed all my custom code to only retain the most basic loading scenario, and it still fails

```rust 
use bevy::{gltf::Gltf, prelude::*};

fn main() {
    App::new()
        .add_plugins((
            DefaultPlugins.set(AssetPlugin {
                ..default()
            }),
        ))
        .add_systems(Startup, setup)
        .add_systems(Update, track_creation)
        .add_systems(Update, track_loadstate)
        .run();
}

#[derive(Resource)]
pub struct MyGltf ( pub Handle<Gltf> );

fn setup(mut commands: Commands, asset_server: Res<AssetServer>) {
    // does not work
    commands.insert_resource(MyGltf(asset_server.load("missiletower_building002.glb#Scene0")));
    // works
    // commands.insert_resource(MyGltf(asset_server.load("Wheelbot.glb#Scene0")));
}

fn track_creation(
    mut events: EventReader<AssetEvent<Gltf>>,
    bla: ResMut<MyGltf>
) {
    for event in events.iter() {
        if let AssetEvent::Created { handle } = event {
            info!("gltf created {:?}", bla.0);
        }
    }
}

fn track_loadstate(
    asset_server: Res<AssetServer>,
    bla: ResMut<MyGltf>
){
    info!(
        "checking for loaded gltfs {:?}",
        asset_server.get_load_state(&bla.0)
    );
}
```

## What went wrong

> - what were you expecting?

   that the gltf files stay loaded
   
> - what actually happened?

  the gltf files get unloaded 

## Additional information

I created a repo with a minimal reproduction of the issue & the gltf files (one that loads, one that does not)
https://github.com/kaosat-dev/bevy_gltf_unloading_issue

It might be something I am doing wrong, but I am honestly baffled.
Thanks in advance :)

**Comment by devil-ira** [comment] 2023-10-24 09:22
I can reproduce with your repo. The issue appears to be fixed on main.

PS: You shouldn't add `#Scene0` if you're trying to load the whole `Gltf` (This logs an error on main).

**Comment by kaosat-dev** [comment] 2023-10-24 09:41
Thanks a lot for the very quick check @devil-ira !
I'll start porting my code to main/v0.12.
Also thanks for the tip about ```#Scene0``` :)

**Comment by alice-i-cecile** [comment] 2023-10-24 12:15
Going to close this as fixed since it doesn't seem to reproduce on main :) Feel free to reopen it if your migration doesn't resolve things.

And thanks so much for providing a high quality reproduction!

**Closed by alice-i-cecile** 2023-10-24 12:15 UTC
Labels: C-Bug, A-Assets
