### ISSUE TITLE
Adding proc_macro `#[required(TransformComponent, ...)]` for Component.

### ISSUE THREAD

**Issue by Jerrody** [bevyengine/bevy#14737] opened 2024-08-13 21:20 UTC
## What problem does this solve or what need does it fill?

A `required` proc_macro will add automatically specified components along with component that has this proc_macro.

## What solution would you like?

Don't know.

## What alternative(s) have you considered?

None.

## Additional context

This is similiar to the Unity's `RequieredComponent` attribute. If we specify this attribute, then, with adding component to the GameObject, will be also added specified components (by components I mean `MonoBehaviour`s).

**Comment by MrGVSV** [comment] 2024-08-13 21:35
This is actually being discussed/designed over in https://github.com/bevyengine/bevy/discussions/14437! 😄

**Comment by Jerrody** [comment] 2024-08-13 22:05
> This is actually being discussed/designed over in #14437! 😄

Oh, thanks. Didn't see it.

**Comment by alice-i-cecile** [comment] 2024-08-17 01:35
Closing as a duplicate of https://github.com/bevyengine/bevy/issues/7272. Being added in https://github.com/bevyengine/bevy/pull/14791.

**Closed by alice-i-cecile** 2024-08-17 01:35 UTC
Labels: C-Enhancement, A-ECS, X-Controversial
