### ISSUE TITLE
Normals for StandardMaterial when using prepass don't match without prepass.

### ISSUE THREAD

**Issue by DGriffin91** [bevyengine/bevy#8746] opened 2023-06-03 03:20 UTC
## Bevy version
d1158288d5977ccea8c87adf80359ff9e21a852e

Normals for the StandardMaterial when the prepass is used don't have the same values as when the prepass is not used.

Without prepass:
![no prepass](https://github.com/bevyengine/bevy/assets/33357138/699cd8c7-7187-4e09-bc30-ac21f5c895ce)

With prepass:
![prepass](https://github.com/bevyengine/bevy/assets/33357138/e78a8d73-7ccb-49f2-82f1-934258895979)

Without prepass:
![just normals no prepass](https://github.com/bevyengine/bevy/assets/33357138/3d4e1396-80c4-4a02-b4b4-3a1497c229fa)

With prepass:
![just normals prepass](https://github.com/bevyengine/bevy/assets/33357138/8e6fc6d4-0d9f-48b5-bf9d-dfd253f2c8ee)

**Comment by DGriffin91** [comment] 2023-06-03 08:31
Parallax mapping is also broken with the prepass. I'm guessing the issue is related.

Without Prepass:
![parallax_forward](https://github.com/bevyengine/bevy/assets/33357138/aa93ed62-9f56-42ca-822a-cf896155d8db)

With Prepass:
![image](https://github.com/bevyengine/bevy/assets/33357138/c0c61cd1-8a71-4365-acbb-12080083a4f8)

**Comment by JMS55** [comment] 2023-06-03 14:55
The parallax mapping issue at least seems to be caused by the normal prepass not account for parallax mapping. Same for the depth prepass https://github.com/bevyengine/bevy/pull/8486, as well as motion vectors. Skinning has the same issue.

While the prepass output isn't matching the main pass, the reason it affects the main pass is due to https://github.com/bevyengine/bevy/pull/8231.

**Comment by JMS55** [comment] 2023-06-19 01:21
I believe the issue is that the [prepass vertex layout](https://github.com/bevyengine/bevy/blob/main/crates/bevy_pbr/src/prepass/prepass.wgsl#L6-L24) does not match the [actual layout of the vertex buffer](https://github.com/bevyengine/bevy/blob/main/crates/bevy_pbr/src/render/mesh.wgsl#L7-L27).

I'm not sure why the prepass has a different vertex layout to begin with, but we need to fix both the shader struct, and the vertex layout as declared in the pipeline.

**Comment by alice-i-cecile** [comment] 2023-06-21 17:29
Fixed by #8890.

**Closed by alice-i-cecile** 2023-06-21 17:29 UTC
Labels: C-Bug, A-Rendering
