### ISSUE TITLE
Disable "function is never used" lints when function is a system.

### ISSUE THREAD

**Issue by iMplode-nZ** [bevyengine/bevy#652] opened 2020-10-09 03:10 UTC
I get these annoying 

```
warning: function is never used: `log_system`
```

messages whenever I only use the function as a system. It would be nice if this could be disabled (maybe have a seperate lint that fixes this issue and disable the original lint?)

**Comment by memoryruins** [comment] 2020-10-09 03:18
It's rustc that emits these lints, not bevy, so there isn't much that can be done about on bevy's end. Still, that is odd. When I use a function as a system, rustc considers it used. Could you post code that recreates this? What prints when you do `rustc --version`?

**Comment by iMplode-nZ** [comment] 2020-10-09 03:52
I use nightly (`rustc 1.48.0-nightly (154f1f544 2020-10-02)`).

**Comment by memoryruins** [comment] 2020-10-09 04:11
For sure. I tried the nightly I had installed, `rustc 1.49.0-nightly (3525087ad 2020-10-08)`, and was unable to reproduce the issue, and I'm not finding any recent regressions for the lint on rustc's repo. If you post the code that creates this warning, I would be happy to help minimize it, then we can narrow down where its coming from / where we should direct the report.

It's also possible that the warnings are stale in your editor. Be sure to try in `cargo check` and see if it emits the warnings at those times too. For example, if rust-analyzer hasn't re-run cargo check, it might be showing a stale/out-of-date warning.

**Comment by iMplode-nZ** [comment] 2020-10-09 19:09
I'm using `cargo fmt` to get these warnings, not rust-analyzer.

**Comment by cart** [comment] 2020-10-09 19:19
This also goes against my understanding of how these warnings work. Can you please provide example code that reproduces this warning? Unfortunately if we don't have a way to repro, I'm just going to assume that this is user error.

**Comment by memoryruins** [comment] 2020-10-11 12:37
Closing since this is either user error or a bug in rust tooling.

**Closed by memoryruins** 2020-10-11 12:37 UTC
