### ISSUE TITLE
"called `Option::unwrap()` on a `None` value" when calling init_state before StatesPlugin is set?

### ISSUE THREAD

**Issue by ShadowMitia** [bevyengine/bevy#14154] opened 2024-07-05 15:16 UTC
## Bevy version

0.14.0

## What you did

Minimal example, I try to call init_state before calling add_plugins.

```rust
use bevy::prelude::*;

#[derive(States, Clone, PartialEq, Eq, Hash, Debug, Default)]
enum AppState {
    GameOver,
    Win,
    #[default]
    InGame,
}

fn main() -> AppExit {
    App::new()
        .init_state::<AppState>()
        .add_plugins(DefaultPlugins)
        .run()
}
```

## What went wrong

Instant panic before even getting a window open.

```
thread 'main' panicked at /home/dimitri/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_state-0.14.0/src/app.rs:74:67:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## Additional information

Calling init_state AFTER add_plugins (which has StatesPlugin) everything works fine.

```rust
use bevy::prelude::*;

#[derive(States, Clone, PartialEq, Eq, Hash, Debug, Default)]
enum AppState {
    GameOver,
    Win,
    #[default]
    InGame,
}

fn main() -> AppExit {
    App::new()
        .add_plugins(DefaultPlugins)
        .init_state::<AppState>()
        .run()
}
```

Possibly related to #14151

**Comment by ShadowMitia** [comment] 2024-07-05 15:41
I dived a bit in the code, I saw there was a warn_if_no_states_plugin_installed function, but it never gets called...

**Comment by ShadowMitia** [comment] 2024-07-05 16:13
Never mind, it's working fine, but because I'm calling the method before LogPlugin is setup, I don't get any error messages...

**Comment by cBournhonesque** [comment] 2024-07-05 16:50
Changing the unwrap to an expect is a good minimum change I think: https://github.com/bevyengine/bevy/issues/14154

**Comment by alice-i-cecile** [comment] 2024-07-07 13:06
Closing as a duplicate of #14110 :)

**Closed by alice-i-cecile** 2024-07-07 13:06 UTC
Labels: C-Bug, S-Needs-Triage
