### ISSUE TITLE
No shadows when camera is added later

### ISSUE THREAD

**Issue by jonri** [bevyengine/bevy#5203] opened 2022-07-04 18:53 UTC
## Bevy version

0.7

## Relevant system information
```AdapterInfo { name: "AMD Radeon RX 570 Series", vendor: 4098, device: 26591, device_type: DiscreteGpu, backend: Vulkan }```

## What you did
Added geometry and PointLight with shadows in an initial stage, and then added a camera in a later stage.

## What went wrong
Everything rendered as expected except there were no shadows.

## Additional information
If the camera is instead added at the same time, shadows will work as expected.

## Minimal reproduction project
Note the two alternatives that add the `make_camera` in different states.  One will work, the other will cause the issue.
[shadowtest.zip](https://github.com/bevyengine/bevy/files/9041609/shadowtest.zip)

**Comment by afpatmin** [comment] 2022-07-04 19:15
I can confirm this happened to me also, specifically when using point lights - shadows from directional lights seems to work in both cases

**Comment by superdump** [comment] 2022-07-04 19:17
Can you retest with `main`? There have been lots of changes relating to point lights since 0.7.

**Comment by afpatmin** [comment] 2022-07-04 19:48
I tested now, the issue seems to be resolved on `main`

**Comment by superdump** [comment] 2022-07-04 22:03
Great, thanks!

**Comment by alice-i-cecile** [comment] 2022-07-04 23:24
Closing as fixed :)

**Closed by alice-i-cecile** 2022-07-04 23:24 UTC
Labels: C-Bug, A-Rendering
