### ISSUE TITLE
Wrong url for error 'b0001'

### ISSUE THREAD

**Issue by BackupMiles** [bevyengine/bevy#14495] opened 2024-07-27 12:10 UTC
## Bevy version

0.14.0

## What you did

I have encountered an error while trying to access a Query, with a broken URL

## What went wrong

The console error tells me to check out the following URL: https://bevyengine.org/learn/errors/#b0001
Clicking on it will not bring me to the relative page, because of the unnecessary '#'
Removing it would lead correctly to the error page

**Comment by mrec** [comment] 2024-07-27 14:16
Dupe of #14248 ?

**Closed** 2024-07-28 15:09 UTC
Labels: C-Bug, C-Docs, S-Duplicate
