### ISSUE TITLE
Bevy crashes when I spawn a Camera2dBundle

### ISSUE THREAD

**Issue by ameknite** [bevyengine/bevy#8176] opened 2023-03-23 04:42 UTC
## Bevy version

main 4f16d6e0dc14c12ab29b72880d5d3d22003eed72

## Relevant system information

cargo 1.68.0 (115f34552 2023-02-26)
```
SystemInfo { os: "MacOS 13.2.1 ", kernel: "22.3.0", cpu: "Apple M1", core_count: "8", memory: "8.0 GiB" }
```

## What you did

I tried to spawn a Camera2dBundle.

```
use bevy::prelude::*;

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_systems(Startup, setup)
        .run();
}

fn setup(mut commands: Commands) {
    commands.spawn(Camera3dBundle::default());
}
```

## What went wrong

The app crashes.

## Additional information

 - Works fine in 0.10
 - Works fine when I spawn a Camera3DBundle

**Comment by rparrett** [comment] 2023-03-23 05:05
I believe this is a duplicate of #8144

**Closed by rparrett** 2023-03-23 05:05 UTC
Labels: C-Bug, S-Needs-Triage
