### ISSUE TITLE
Runtime panick because of "regex parse error" in Naga OIL comment_strip_iter

### ISSUE THREAD

**Issue by benjamin-godon** [bevyengine/bevy#9693] opened 2023-09-04 18:40 UTC
Hello,

I'm new to Rust and Bevy, just trying to run Bevy's breakout example:
cargo run --example breakout

It panicks in Naga OIL comment_strip_iter.rs line 6:

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Syntax(
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
regex parse error:
    (\/\/|\/\*|\*\/)
     ^^
error: unrecognized escape sequence
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
)', /home/benjamin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/naga_oil-0.8.2/src/compose/comment_strip_iter.rs:6:67

Please help ;-)

**Comment by benjamin-godon** [comment] 2023-09-04 18:41
I've got cargo/rust 1.72.0 and Bevy 0.11.0.

**Comment by alice-i-cecile** [comment] 2023-09-04 18:45
Duplicate of: https://github.com/bevyengine/bevy/issues/9690

Upstream: 
https://github.com/bevyengine/naga_oil/issues/50

**Comment by alice-i-cecile** [comment] 2023-09-07 02:54
Appears to be fixed upstream now: I'm going to close this out :)

**Closed by alice-i-cecile** 2023-09-07 02:54 UTC
Labels: C-Bug, A-Rendering, S-Blocked
