### ISSUE TITLE
Errors getting spammed in debug mode when using bloom

### ISSUE THREAD

**Issue by soupslurpr** [bevyengine/bevy#10830] opened 2023-12-01 18:00 UTC
## Bevy version

0.12.1

## \[Optional\] Relevant system information

Toolchain is nightly-2023-12-01, but I also tested with 1.74.0.
I'm using Windows 11 23H2

If your bug is rendering-related, copy the adapter info that appears when you run Bevy.

Not sure if it counts as rendering-related, but:
`AdapterInfo { name: "AMD Radeon(TM) 760M", vendor: 4098, device: 5567, device_type: IntegratedGpu, driver: "AMD proprietary driver", driver_info: "22.40.80.03 (LLPC)", backend: Vulkan }`

You should also consider testing the examples of our upstream dependencies to help isolate any setup-specific issue:

- [`wgpu`](https://github.com/gfx-rs/wgpu) for rendering problems
- [`winit`](https://github.com/rust-windowing/winit) for input and window management
- [`gilrs`](https://docs.rs/gilrs/latest/gilrs/) for gamepad inputs

## What you did

Enabled bloom.

Code:

main.rs:
```
mod components;

use bevy::core_pipeline::bloom::BloomCompositeMode;
use bevy::core_pipeline::bloom::BloomPrefilterSettings;
use bevy::core_pipeline::bloom::BloomSettings;
use bevy::core_pipeline::tonemapping::Tonemapping;
use bevy::prelude::*;
use bevy::sprite::MaterialMesh2dBundle;
use bevy::window::close_on_esc;
use components::Player;

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_systems(Startup, setup)
        .add_systems(FixedUpdate, movement)
        .add_systems(Update, close_on_esc)
        .run();
}

fn setup(
    mut commands: Commands,
    mut meshes: ResMut<Assets<Mesh>>,
    mut materials: ResMut<Assets<ColorMaterial>>,
) {
    commands.spawn((
        Camera2dBundle {
            camera: Camera {
                hdr: true,
                ..default()
            },
            tonemapping: Tonemapping::TonyMcMapface,
            ..default()
        },
        BloomSettings {
            intensity: 0.05,
            low_frequency_boost: 0.5,
            low_frequency_boost_curvature: 0.75,
            high_pass_frequency: 1.0,
            prefilter_settings: BloomPrefilterSettings::default(),
            composite_mode: BloomCompositeMode::Additive,
        },
    ));

    let player_radius = 15.0;
    commands
        .spawn((
            Player,
            MaterialMesh2dBundle {
                mesh: meshes.add(shape::Circle::new(player_radius).into()).into(),
                material: materials.add(ColorMaterial::from(Color::rgb(6.0, 11.0, 9.0))),
                ..default()
            },
        ))
        .insert(TransformBundle::from_transform(
            Transform::from_translation(Vec3::new(0., 0., 0.)),
        ));
}

fn movement(mut query: Query<&mut Transform, With<Player>>, key: Res<Input<ScanCode>>) {
    query.for_each_mut(|mut transform| {
        let mut final_translation = Vec3::new(0.0, 0.0, 0.0);

        // LEFT
        if key.pressed(ScanCode(30)) {
            final_translation.x -= 1.0
        }
        // RIGHT
        if key.pressed(ScanCode(32)) {
            final_translation.x += 1.0
        }
        // JUMP
        if key.pressed(ScanCode(17)) {
            todo!()
        }
        // DOWN
        if key.pressed(ScanCode(31)) {
            todo!()
        }

        transform.translation += final_translation
    })
}
```

components.rs:
```
use bevy::prelude::*;

#[derive(Component)]
pub struct Player;
```

## What went wrong

If it's not clear, break this out into:

- what were you expecting?
- To not get spammed with errors in debug
- what actually happened?
- Continuously got spammed with a ton of errors but otherwise the game seems to be running fine.

## Additional information

Other information that can be used to further reproduce or isolate the problem.
This commonly includes:

The errors are like this and constantly appear. It does not appear in release.

```
2023-12-01T17:42:59.671785Z ERROR log: ID3D12CommandQueue::ExecuteCommandLists: Using ClearRenderTargetView on Command List (0x00000167F5CE8FA0:'Unnamed ID3D12GraphicsCommandList Object'): Resource state (0x7C4FEA00: D3D12_RESOURCE_STATE_[COMMON|PRESENT]) of resource (0x00000167F5F46E10:'Unnamed ID3D12Resource Object') (subresource: 0) is invalid for use as a render target.  Expected State Bits (all): 0x7C4FE9E0: D3D12_RESOURCE_STATE_RENDER_TARGET, Actual State: 0x7C4FE9C0: D3D12_RESOURCE_STATE_[COMMON|PRESENT], Missing State: 0x4: D3D12_RESOURCE_STATE_RENDER_TARGET. [ EXECUTION ERROR #538: INVALID_SUBRESOURCE_STATE]
2023-12-01T17:42:59.727469Z ERROR log: ID3D12CommandQueue::ExecuteCommandLists: Using IDXGISwapChain::Present on Command List (0x00000167F5F02090:'Internal DXGI CommandList'): Resource state (0x7C4FEA00: D3D12_RESOURCE_STATE_RENDER_TARGET) of resource (0x00000167F5F46E10:'Unnamed ID3D12Resource Object') (subresource: 0) is invalid for use as a PRESENT_SOURCE.  Expected State Bits (all): 0x7C4FE9E0: D3D12_RESOURCE_STATE_[COMMON|PRESENT], Actual State: 0x7C4FE9C0: D3D12_RESOURCE_STATE_RENDER_TARGET, Missing State: 0x0: D3D12_RESOURCE_STATE_[COMMON|PRESENT]. [ EXECUTION ERROR #538: INVALID_SUBRESOURCE_STATE]
2023-12-01T17:42:59.731368Z ERROR log: ID3D12CommandQueue::ExecuteCommandLists: Using ClearRenderTargetView on Command List (0x00000167F5D58B20:'Unnamed ID3D12GraphicsCommandList Object'): Resource state (0x7C4FEA00: D3D12_RESOURCE_STATE_[COMMON|PRESENT]) of resource (0x00000167F5F48E80:'Unnamed ID3D12Resource Object') (subresource: 0) is invalid for use as a render target.  Expected State Bits (all): 0x7C4FE9E0: D3D12_RESOURCE_STATE_RENDER_TARGET, Actual State: 0x7C4FE9C0: D3D12_RESOURCE_STATE_[COMMON|PRESENT], Missing State: 0x4: D3D12_RESOURCE_STATE_RENDER_TARGET. [ EXECUTION ERROR #538: INVALID_SUBRESOURCE_STATE]
2023-12-01T17:42:59.785931Z ERROR log: ID3D12CommandQueue::ExecuteCommandLists: Using IDXGISwapChain::Present on Command List (0x00000167F5F02090:'Internal DXGI CommandList'): Resource state (0x7C4FEA00: D3D12_RESOURCE_STATE_RENDER_TARGET) of resource (0x00000167F5F48E80:'Unnamed ID3D12Resource Object') (subresource: 0) is invalid for use as a PRESENT_SOURCE.  Expected State Bits (all): 0x7C4FE9E0: D3D12_RESOURCE_STATE_[COMMON|PRESENT], Actual State: 0x7C4FE9C0: D3D12_RESOURCE_STATE_RENDER_TARGET, Missing State: 0x0: D3D12_RESOURCE_STATE_[COMMON|PRESENT]. [ EXECUTION ERROR #538: INVALID_SUBRESOURCE_STATE]
2023-12-01T17:42:59.798365Z ERROR log: ID3D12CommandQueue::ExecuteCommandLists: Using ClearRenderTargetView on Command List (0x00000167F5C7DF50:'Unnamed ID3D12GraphicsCommandList Object'): Resource state (0x7C4FEA00: D3D12_RESOURCE_STATE_[COMMON|PRESENT]) of resource (0x00000167F5F44DA0:'Unnamed ID3D12Resource Object') (subresource: 0) is invalid for use as a render target.  Expected State Bits (all): 0x7C4FE9E0: D3D12_RESOURCE_STATE_RENDER_TARGET, Actual State: 0x7C4FE9C0: D3D12_RESOURCE_STATE_[COMMON|PRESENT], Missing State: 0x4: D3D12_RESOURCE_STATE_RENDER_TARGET. [ EXECUTION ERROR #538: INVALID_SUBRESOURCE_STATE]
2023-12-01T17:42:59.845216Z ERROR log: ID3D12CommandQueue::ExecuteCommandLists: Using IDXGISwapChain::Present on Command List (0x00000167F5F02090:'Internal DXGI CommandList'): Resource state (0x7C4FEA00: D3D12_RESOURCE_STATE_RENDER_TARGET) of resource (0x00000167F5F44DA0:'Unnamed ID3D12Resource Object') (subresource: 0) is invalid for use as a PRESENT_SOURCE.  Expected State Bits (all): 0x7C4FE9E0: D3D12_RESOURCE_STATE_[COMMON|PRESENT], Actual State: 0x7C4FE9C0: D3D12_RESOURCE_STATE_RENDER_TARGET, Missing State: 0x0: D3D12_RESOURCE_STATE_[COMMON|PRESENT]. [ EXECUTION ERROR #538: INVALID_SUBRESOURCE_STATE]
2023-12-01T17:42:59.845935Z ERROR log: ID3D12CommandQueue::ExecuteCommandLists: Using ClearRenderTargetView on Command List (0x00000167F5CE8FA0:'Unnamed ID3D12GraphicsCommandList Object'): Resource state (0x7C4FEA00: D3D12_RESOURCE_STATE_[COMMON|PRESENT]) of resource (0x00000167F5F46E10:'Unnamed ID3D12Resource Object') (subresource: 0) is invalid for use as a render target.  Expected State Bits (all): 0x7C4FE9E0: D3D12_RESOURCE_STATE_RENDER_TARGET, Actual State: 0x7C4FE9C0: D3D12_RESOURCE_STATE_[COMMON|PRESENT], Missing State: 0x4: D3D12_RESOURCE_STATE_RENDER_TARGET. [ EXECUTION ERROR #538: INVALID_SUBRESOURCE_STATE]
2023-12-01T17:42:59.875332Z ERROR log: ID3D12CommandQueue::ExecuteCommandLists: Using IDXGISwapChain::Present on Command List (0x00000167F5F02090:'Internal DXGI CommandList'): Resource state (0x7C4FEA00: D3D12_RESOURCE_STATE_RENDER_TARGET) of resource (0x00000167F5F46E10:'Unnamed ID3D12Resource Object') (subresource: 0) is invalid for use as a PRESENT_SOURCE.  Expected State Bits (all): 0x7C4FE9E0: D3D12_RESOURCE_STATE_[COMMON|PRESENT], Actual State: 0x7C4FE9C0: D3D12_RESOURCE_STATE_RENDER_TARGET, Missing State: 0x0: D3D12_RESOURCE_STATE_[COMMON|PRESENT]. [ EXECUTION ERROR #538: INVALID_SUBRESOURCE_STATE]
2023-12-01T17:42:59.895482Z ERROR log: ID3D12CommandQueue::ExecuteCommandLists: Using ClearRenderTargetView on Command List (0x00000167F5D58B20:'Unnamed ID3D12GraphicsCommandList Object'): Resource state (0x7C4FEA00: D3D12_RESOURCE_STATE_[COMMON|PRESENT]) of resource (0x00000167F5F48E80:'Unnamed ID3D12Resource Object') (subresource: 0) is invalid for use as a render target.  Expected State Bits (all): 0x7C4FE9E0: D3D12_RESOURCE_STATE_RENDER_TARGET, Actual State: 0x7C4FE9C0: D3D12_RESOURCE_STATE_[COMMON|PRESENT], Missing State: 0x4: D3D12_RESOURCE_STATE_RENDER_TARGET. [ EXECUTION ERROR #538: INVALID_SUBRESOURCE_STATE]
2023-12-01T17:42:59.939168Z ERROR log: ID3D12CommandQueue::ExecuteCommandLists: Using IDXGISwapChain::Present on Command List (0x00000167F5F02090:'Internal DXGI CommandList'): Resource state (0x7C4FEA00: D3D12_RESOURCE_STATE_RENDER_TARGET) of resource (0x00000167F5F48E80:'Unnamed ID3D12Resource Object') (subresource: 0) is invalid for use as a PRESENT_SOURCE.  Expected State Bits (all): 0x7C4FE9E0: D3D12_RESOURCE_STATE_[COMMON|PRESENT], Actual State: 0x7C4FE9C0: D3D12_RESOURCE_STATE_RENDER_TARGET, Missing State: 0x0: D3D12_RESOURCE_STATE_[COMMON|PRESENT]. [ EXECUTION ERROR #538: INVALID_SUBRESOURCE_STATE]
2023-12-01T17:42:59.950211Z ERROR log: ID3D12CommandQueue::ExecuteCommandLists: Using ClearRenderTargetView on Command List (0x00000167F5C7DF50:'Unnamed ID3D12GraphicsCommandList Object'): Resource state (0x7C4FEA00: D3D12_RESOURCE_STATE_[COMMON|PRESENT]) of resource (0x00000167F5F44DA0:'Unnamed ID3D12Resource Object') (subresource: 0) is invalid for use as a render target.  Expected State Bits (all): 0x7C4FE9E0: D3D12_RESOURCE_STATE_RENDER_TARGET, Actual State: 0x7C4FE9C0: D3D12_RESOURCE_STATE_[COMMON|PRESENT], Missing State: 0x4: D3D12_RESOURCE_STATE_RENDER_TARGET. [ EXECUTION ERROR #538: INVALID_SUBRESOURCE_STATE]
2023-12-01T17:42:59.973606Z ERROR log: ID3D12CommandQueue::ExecuteCommandLists: Using IDXGISwapChain::Present on Command List (0x00000167F5F02090:'Internal DXGI CommandList'): Resource state (0x7C4FEA00: D3D12_RESOURCE_STATE_RENDER_TARGET) of resource (0x00000167F5F44DA0:'Unnamed ID3D12Resource Object') (subresource: 0) is invalid for use as a PRESENT_SOURCE.  Expected State Bits (all): 0x7C4FE9E0: D3D12_RESOURCE_STATE_[COMMON|PRESENT], Actual State: 0x7C4FE9C0: D3D12_RESOURCE_STATE_RENDER_TARGET, Missing State: 0x0: D3D12_RESOURCE_STATE_[COMMON|PRESENT]. [ EXECUTION ERROR #538: INVALID_SUBRESOURCE_STATE]
2023-12-01T17:42:59.986578Z ERROR log: ID3D12CommandQueue::ExecuteCommandLists: Using ClearRenderTargetView on Command List (0x00000167F5CE8FA0:'Unnamed ID3D12GraphicsCommandList Object'): Resource state (0x7C4FEA00: D3D12_RESOURCE_STATE_[COMMON|PRESENT]) of resource (0x00000167F5F46E10:'Unnamed ID3D12Resource Object') (subresource: 0) is invalid for use as a render target.  Expected State Bits (all): 0x7C4FE9E0: D3D12_RESOURCE_STATE_RENDER_TARGET, Actual State: 0x7C4FE9C0: D3D12_RESOURCE_STATE_[COMMON|PRESENT], Missing State: 0x4: D3D12_RESOURCE_STATE_RENDER_TARGET. [ EXECUTION ERROR #538: INVALID_SUBRESOURCE_STATE]
2023-12-01T17:43:00.051415Z ERROR log: ID3D12CommandQueue::ExecuteCommandLists: Using IDXGISwapChain::Present on Command List (0x00000167F5F02090:'Internal DXGI CommandList'): Resource state (0x7C4FEA00: D3D12_RESOURCE_STATE_RENDER_TARGET) of resource (0x00000167F5F46E10:'Unnamed ID3D12Resource Object') (subresource: 0) is invalid for use as a PRESENT_SOURCE.  Expected State Bits (all): 0x7C4FE9E0: D3D12_RESOURCE_STATE_[COMMON|PRESENT], Actual State: 0x7C4FE9C0: D3D12_RESOURCE_STATE_RENDER_TARGET, Missing State: 0x0: D3D12_RESOURCE_STATE_[COMMON|PRESENT]. [ EXECUTION ERROR #538: INVALID_SUBRESOURCE_STATE]
```

**Comment by JMS55** [comment] 2023-12-01 21:05
This is an upstream issue https://github.com/gfx-rs/wgpu/issues/4247

**Comment by JMS55** [comment] 2023-12-01 21:05
Also looks like a dupe of https://github.com/bevyengine/bevy/issues/9975

**Closed** 2023-12-02 07:15 UTC
Labels: C-Bug, A-Rendering
