### ISSUE TITLE
ReportExecutionOrderAmbiguities doesn't understand query filters

### ISSUE THREAD

**Issue by SUPERCILEX** [bevyengine/bevy#4877] opened 2022-05-31 01:27 UTC
## Bevy version

e543941fb9ffed652f99f96301e28d3d7f6e3e6f and 0.7.0

## What you did

```patch
Index: examples/ecs/ecs_guide.rs
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/examples/ecs/ecs_guide.rs b/examples/ecs/ecs_guide.rs
--- a/examples/ecs/ecs_guide.rs	(revision 314e1b7ed6ceff35dd26f90c66b59d5f908e121f)
+++ b/examples/ecs/ecs_guide.rs	(date 1653960365357)
@@ -336,5 +336,17 @@
         .add_plugin(LogPlugin::default())
         .init_resource::<ReportExecutionOrderAmbiguities>()
         // This call to run() starts the app we just built!
+        .add_system(a)
+        .add_system(b)
         .run();
 }
+
+#[derive(Component)]
+struct A;
+
+#[derive(Component)]
+struct B;
+
+fn a(_q: Query<&mut Transform, (With<A>, Without<B>)>) {}
+
+fn b(_q: Query<&mut Transform, (With<B>, Without<A>)>) {}
```

## What went wrong

A conflict is incorrect reported.

**Comment by DJMcNab** [comment] 2022-05-31 06:02
`master` is a significantly outdated branch, which might only be available on really old forks  - `main` should be used instead. Could you mention the exact commit you're testing with?

**Comment by SUPERCILEX** [comment] 2022-05-31 06:04
Sorry, I meant main.

**Comment by SUPERCILEX** [comment] 2022-05-31 06:05
Specifically e543941fb9ffed652f99f96301e28d3d7f6e3e6f

**Comment by alice-i-cecile** [comment] 2022-05-31 15:41
I discovered this in #4299 as well. My feeling is that we need to do a cleanup pass on our `Access` code to unify this.

**Comment by rparrett** [comment] 2022-09-16 16:59
Is this a duplicate of #4381?

**Comment by alice-i-cecile** [comment] 2022-09-16 17:27
Yep; closing as duplicate.

**Closed by alice-i-cecile** 2022-09-16 17:27 UTC
Labels: C-Bug, A-ECS
