### ISSUE TITLE
Unintuitive ability to change WindowDescriptor

### ISSUE THREAD

**Issue by SUPERCILEX** [bevyengine/bevy#3787] opened 2022-01-27 22:49 UTC
## Bevy version

0.6

## What you did

```rust
fn full_screen_toggle(mut window: ResMut<WindowDescriptor>, keyboard_input: Res<Input<KeyCode>>) {
    if keyboard_input.just_released(KeyCode::F) {
        window.mode = if window.mode == WindowMode::Windowed {
            WindowMode::BorderlessFullscreen
        } else {
            WindowMode::Windowed
        };
    }
}
```

## What you expected to happen

I thought the window mode would change.

## What actually happened

Nothing. I would have expected this to fail to compile or panic so I'd know that's not the API to use.

## Additional information

This is the right way to do it:

```rust
fn full_screen_toggle(mut windows: ResMut<Windows>, keyboard_input: Res<Input<KeyCode>>) {
    if keyboard_input.just_released(KeyCode::F) {
        let window = windows.get_primary_mut().unwrap();
        window.set_mode(if window.mode() == WindowMode::Windowed {
            WindowMode::BorderlessFullscreen
        } else {
            WindowMode::Windowed
        });
    }
}
```

**Comment by DJMcNab** [comment] 2022-01-27 23:11
Duplicate of #2879

**Closed** 2022-01-28 00:31 UTC
Labels: C-Bug, S-Duplicate, A-Window
