### ISSUE TITLE
Online "Button Example" has the target centered below where it should be

### ISSUE THREAD

**Issue by Ryder17z** [bevyengine/bevy#5336] opened 2022-07-16 06:09 UTC
## Bevy version
Unknown.

## Relevant system information
Running Firefox 102.0.1

## What you did
Run online demo: https://bevyengine.org/examples/ui/button/

## What went wrong
Target area is offset downwards

## Additional information
![image](https://user-images.githubusercontent.com/2000703/179342398-4c2b1b13-9357-4577-bd67-dac381c9cf9c.png)
(I couldn't get the cursor to show up in the screenshot, so I painted one onto the picture)

**Comment by Weibye** [comment] 2022-07-17 08:13
Just tested on Chrome 103.0.5060.114, same issue. 

Seems the size is correct but the hover area is offset down and to the right like so:

![image](https://user-images.githubusercontent.com/13300393/179389755-6bc4a922-164c-489c-9adf-21099f78c7b9.png)

**Comment by Weibye** [comment] 2022-07-17 08:25
Closing as duplicate of #4963, it _should_ be fixed on `main,` meaning the example should get fixed once bevy 0.8 is released.

If the issue persists after that we should reopen #4963

**Closed by Weibye** 2022-07-17 08:25 UTC
Labels: C-Bug, A-UI

**Comment by Ryder17z** [comment] 2022-07-17 10:37
Ah. I didn't find the earlier bug report.
