### ISSUE TITLE
Better user-facing compile-time errors using `#[diagnostic]`

### ISSUE THREAD

**Issue by Adamkob12** [bevyengine/bevy#13204] opened 2024-05-03 13:29 UTC
## What problem does this solve or what need does it fill?
Currently, due to the heavy use of `all_tuples` (Bundling up generic types in tuples) in traits like `Bundle`, `SystemParam`, `IntoSystemConfig`, user-facing compile time errors can get very messy and uninformative. 

For example (the actual problem was caused when forgetting to implement `Component` for some type):

![Screenshot from 2024-05-03 09-18-42](https://github.com/bevyengine/bevy/assets/46227443/3a6bc215-a37b-4d6a-b30d-db339a0dc379)

But it's gonna be very hard for inexperienced users to understand what the problem is, and how to fix it.

## What solution would you like?
Version [`1.78`](https://blog.rust-lang.org/2024/05/02/Rust-1.78.0.html) introduced `#[diagnostic]` attributes. We can use `#[diagnostic::on_unimplemented]` to make those errors more informative and readable.

**Comment by alice-i-cecile** [comment] 2024-05-03 13:31
Duplicate of https://github.com/bevyengine/bevy/issues/12377 :) Strongly desired though!

**Closed** 2024-05-03 13:32 UTC
Labels: S-Duplicate, A-ECS, C-Usability
