### ISSUE TITLE
Bevy Tracy profiling error: failed to select a version for the requirement `profiling-procmacros = "^1.0.15"

### ISSUE THREAD

**Issue by Veliladon** [bevyengine/bevy#14294] opened 2024-07-13 16:28 UTC
## Bevy version

0.14

## \[Optional\] Relevant system information

If you cannot get Bevy to build or run on your machine, please include:

Rust 1.79.0
Windows 11 22635

## What you did

Made a new blank Bevy project and tried to profile it. Ran cargo run --release --features bevy/trace_chrome

## What went wrong

error: failed to select a version for the requirement `profiling-procmacros = "^1.0.15"`
candidate versions found which didn't match: 1.0.11, 1.0.10, 1.0.9, ...
location searched: crates.io index
required by package `profiling v1.0.15`
    ... which satisfies dependency `profiling = "^1"` (locked to 1.0.15) of package `bevy_render v0.14.0`
    ... which satisfies dependency `bevy_render = "^0.14.0"` (locked to 0.14.0) of package `bevy_internal v0.14.0`
    ... which satisfies dependency `bevy_internal = "^0.14.0"` (locked to 0.14.0) of package `bevy v0.14.0`
    ... which satisfies dependency `bevy = "^0.14.0"` (locked to 0.14.0) of package `yyy v0.1.0 (C:\Users\xxx\yyy)`
perhaps a crate was updated and forgotten to be re-vendored?

**Comment by kirillsurkov** [comment] 2024-07-13 21:04
Duplicate of https://github.com/bevyengine/bevy/issues/11365

**Closed** 2024-07-14 14:19 UTC
Labels: S-Duplicate, A-Diagnostics, P-Compile-Failure
