### ISSUE TITLE
It seems that the shadow in 3d_scene is wrong

### ISSUE THREAD

**Issue by piaoger** [bevyengine/bevy#3423] opened 2021-12-23 19:09 UTC
## Bevy version

Latest change in main branch

## Operating system & version

macOS BigSur

## What you did

Drop the latest change in main branch and found the shadow in 3d_scene is wrong

## What you expected to happen

correct shadow

## What actually happened

It seems that the shadow in 3d_scene is wrong

## Additional information

 
<img width="501" alt="image" src="https://user-images.githubusercontent.com/179429/147282547-c3c77cb6-ac6e-4ca7-89ae-90eb99cae85d.png">

**Comment by mockersf** [comment] 2021-12-23 21:00
it works fine for me on macOS Monterey... what is the gpu of your Mac?

**Comment by piaoger** [comment] 2021-12-24 06:21
@mockersf 

debug info:
```
INFO bevy_render::renderer: AdapterInfo { name: "Intel Iris Pro Graphics", vendor: 0, device: 0, device_type: IntegratedGpu, backend: Metal }
```
![image](https://user-images.githubusercontent.com/179429/147324189-e4701bfe-fe46-4d61-8552-d9e67cce2ca4.png)

**Comment by piaoger** [comment] 2021-12-24 06:29
I remember the shadow is fine a few days ago, maybe a couple of days right before renaming *-piped stuffs. Please let me know if you need any more information.

**Comment by superdump** [comment] 2022-01-23 22:03
This looks like a duplicate of https://github.com/bevyengine/bevy/issues/3315 right @mockersf ?

**Comment by mockersf** [comment] 2022-01-23 22:27
Yup!

**Comment by alice-i-cecile** [comment] 2022-08-29 15:28
Closing to collect discusssion :)

**Closed by alice-i-cecile** 2022-08-29 15:28 UTC
Labels: C-Bug, A-Rendering, S-Needs-Investigation
