### ISSUE TITLE
Async-Executor v1.9.0 Selected by Cargo Locks up the engine

### ISSUE THREAD

**Issue by dt665m** [bevyengine/bevy#12044] opened 2024-02-22 08:40 UTC
## Bevy version

Bevy 0.12.1

## \[Optional\] Relevant system information

macOs Sonoma

## What you did

Shared a Project without Cargo.lock checked in.  A new Cargo.lock resolved by cargo Resolves to Async-Executor 1.9.0, which locks up the game at the very start.  This is very hard to bisect when many things are different in Cargo.lock

## Additional information

Either something changed with async-executor that is more than a small bump (not exactly MINOR in semver) or perhaps there is a bug.  Maybe bevy can lock the dependency.

## Temporary Fix
For those who might also run into this, we are explicitly pinning async-executor to 1.8.0 in our own Cargo.

**Comment by james7132** [comment] 2024-02-22 09:35
async-executor 1.9.0 has been yanked for now. New builds shouldn't be pulling it anymore. Going to continue to investigate why this happened, as this was a bug. In retrospect, having been working on both projects, I should have validated changes to async-executor worked with Bevy.

**Comment by james7132** [comment] 2024-03-23 09:10
Closing this out for now as async_executor has yet to publish a new version, but the issue has been fixed upstream. A new version has not been published due to a major regression in performance due to higher contention.

**Closed by james7132** 2024-03-23 09:10 UTC
Labels: C-Dependencies, A-Tasks
