### ISSUE TITLE
Unable to Close Window and Exit Program on Application Shutdown

### ISSUE THREAD

**Issue by LTstrange** [bevyengine/bevy#12106] opened 2024-02-25 07:28 UTC
## Bevy version

Bevy version: 0.13.0

## \[Optional\] Relevant system information

Operating System: Windows 11

## What you did

```rust
use bevy::prelude::*;

fn main() {
    App::new().add_plugins(DefaultPlugins).run();
}

```

## What went wrong

I encountered an issue where, upon attempting to close the window (either by clicking the close button or using ESC to exit the program), the window and program failed to close properly. Windows eventually displays a "Program not responding" message.

## Additional information

The log messages indicate a discrepancy in the sequence of events during shutdown:
```
2024-02-25T07:09:19.165215Z  INFO bevy_window::system: No windows are open, exiting
2024-02-25T07:09:19.165963Z  INFO bevy_winit::system: Closing window 0v1
```
The first message suggests that no windows are open, while the second message indicates an attempt to close a window. This discrepancy may prevent the window and program from closing correctly.

Here is the full log:
```
2024-02-25T07:09:15.624801Z  INFO bevy_winit::system: Creating new window "App" (0v1)
2024-02-25T07:09:16.176184Z  INFO bevy_render::renderer: AdapterInfo { name: "NVIDIA GeForce RTX 2070 Super", vendor: 4318, device: 7825, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "551.61", backend: Vulkan }
2024-02-25T07:09:19.165215Z  INFO bevy_window::system: No windows are open, exiting
2024-02-25T07:09:19.165963Z  INFO bevy_winit::system: Closing window 0v1
```

**Comment by LTstrange** [comment] 2024-02-25 07:50
I tested it several times. It happens frequently, but sometimes not.

**Comment by Selene-Amanita** [comment] 2024-03-03 04:33
Happens to me to.

The order discrepency is not a big deal I think because the `Window` entity is despawned when the window is closed (not sure by which process, doesn't matter), and `exit_on_all_closed` and `despawn_windows` (which print the messages) both react to that, the first one sends the `AppExit` event, the second one just tells winit to actually close the window, the order shouldn't matter.

After some testing, `event_loop.exit()` never seems to be called, and actually the `handle_winit_event` function is never called again by the event loop as soon as there is no window, which ironically prevents it from exiting. If you comment out the line `winit_windows.remove_window(window);` of `despawn_windows` then it exits normally.

A "hotfix" could be to somehow wait a bit before telling winit to actually close the window, but there might be a deeper issue here.

**Comment by Selene-Amanita** [comment] 2024-03-03 05:08
When changing `WinitWindows::remove_window`'s body to:
```rust
        let winit_id = self.entity_to_winit.remove(&entity).unwrap();
        self.winit_to_entity.remove(&winit_id);
        //self.windows.remove(&winit_id)
 ```
 this seems to fix it.

Since the function had an outdated "// Don't remove from `winit_to_window_id` so we know the window used to exist." comment (`winit_to_window_id` doesn't exist anymore) there might be a logic error here.

But I'm not sure, I don't understand the exact process by which a window is actually closed.

**Comment by inact1v1ty** [comment] 2024-03-09 12:11
This happens on macOS too. Also, it doesn't matter how the application is closed - it hangs if the window is closed, if the `AppExit` is fired manually, if `Control + C` pressed in the console, and even if game crashes because of a panic.

**Comment by alice-i-cecile** [comment] 2024-05-16 15:20
I can no longer reproduce on https://github.com/bevyengine/bevy/commit/65e62ba5eb5b08bbd1cb94b4b48a5d55c152c59b on Windows 11 :) Closing as fixed.

**Closed by alice-i-cecile** 2024-05-16 15:20 UTC
Labels: C-Bug, A-Windowing, C-Regression
