### ISSUE TITLE
Warnings in event_viewer

### ISSUE THREAD

**Issue by Jupp56** [bevyengine/bevy#6631] opened 2022-11-15 14:25 UTC
## Bevy version

688f13cd838efb1c0c44f2aa20ed844b45d6115f

## Relevant system information

rustc 1.65.0 (897e37553 2022-11-02)

Windows 10 10.0.19044

## What you did

Run the scene_viewer example without a file specified.

## What went wrong

A warning concerning unused mouse events each time I click the left mouse button.

## Additional information

The warning: 
```
WARN bevy_ecs::event: Missed 32 `bevy_input::mouse::MouseMotion` events. Consider reading from the `EventReader` more often (generally the best solution) or calling Events::update() less frequently (normally this is called once per frame). This problem is most likely due to run criteria/fixed timesteps or consuming events conditionally. See the Events documentation for more information.
```

A PR to fix that is following.

**Comment by rparrett** [comment] 2022-11-15 14:28
Related: https://github.com/bevyengine/bevy/issues/6596

**Comment by nicopap** [comment] 2022-11-15 14:28
Duplicate of #6596

**Closed** 2022-11-15 14:28 UTC
Labels: C-Bug, S-Duplicate
