### ISSUE TITLE
Lightning stops aprubtly

### ISSUE THREAD

**Issue by matthis-k** [bevyengine/bevy#4448] opened 2022-04-10 12:03 UTC
## Bevy version
0.6.1

## Operating system & version
Archlinux

## What you did

```use std::f32::consts::PI;

use bevy::{input::mouse::MouseMotion, prelude::*, window::WindowMode};
use bevy_inspector_egui::{Inspectable, WorldInspectorPlugin};
use heron::prelude::*;

#[derive(Component, Inspectable, Default)]
struct Sphere;

#[derive(Component, Copy, Clone, Default)]
struct FpsCamera {
    y_rot: f32,
    x_rot: f32,
}

impl FpsCamera {
    fn update(&mut self, m: &MouseMotion, sensitifity: f32) {
        let factor = sensitifity / 200.0;
        let mut new_y_rot = self.y_rot - m.delta.x * factor;
        if new_y_rot < -PI {
            new_y_rot += 2.0 * PI;
        } else if new_y_rot > PI {
            new_y_rot -= 2.0 * PI;
        }
        self.y_rot = new_y_rot;
        self.x_rot = (self.x_rot - m.delta.y * factor).clamp(-PI, PI);
    }

    fn calc_quat(&self) -> Quat {
        Quat::from_euler(EulerRot::YXZ, self.y_rot, self.x_rot, 0.0)
    }
}

fn spawn_sphere(
    mut commands: Commands,
    mut meshes: ResMut<Assets<Mesh>>,
    mut mats: ResMut<Assets<StandardMaterial>>,
) {
    let mat = mats.add(StandardMaterial {
        base_color: Color::RED,
        //emissive: Color::GREEN,
        reflectance: 0.0,
        metallic: 0.0,
        ..Default::default()
    });

    for i in 0..6 {
        commands
            .spawn_bundle(PbrBundle {
                mesh: meshes.add(Mesh::from(shape::Icosphere {
                    radius: 1.0,
                    subdivisions: i,
                })),
                material: mat.clone(),
                transform: Transform::from_xyz(-9.0 + (i as f32 * 3.0), 0.0, 0.0),
                ..Default::default()
            })
            .insert(Velocity::default())
            .insert(Acceleration::default())
            .insert(CollisionShape::Sphere { radius: 1.0 })
            .insert(PhysicMaterial::default())
            .insert(RotationConstraints::lock())
            .insert(RigidBody::Static);
    }
    commands.spawn_bundle(PointLightBundle {
        transform: Transform::from_xyz(0.0, 5.0, 0.0),
        ..Default::default()
    });
}

#[derive(Component)]
struct Player;

fn spawn_camera(mut commands: Commands) {
    commands
        .spawn_bundle(PerspectiveCameraBundle {
            transform: Transform::from_xyz(0.0, 0.0, 5.0).looking_at(Vec3::ZERO, Vec3::Y),
            perspective_projection: PerspectiveProjection {
                fov: PI / 2.0,
                aspect_ratio: 16.0 / 9.0,
                near: 0.1,
                far: 100.0,
            },
            ..Default::default()
        })
        .insert(Player)
        .insert(FpsCamera::default())
        .insert(Velocity::default())
        .insert(Acceleration::default())
        .insert(CollisionShape::Sphere { radius: 0.3 })
        .insert(PhysicMaterial::default())
        .insert(RotationConstraints::lock())
        .insert(RigidBody::Dynamic);
}

fn camera_movement(
    mut player: Query<(&mut Velocity, &mut Transform), With<Player>>,
    keys: Res<Input<KeyCode>>,
) {
    let (v, t) = player
        .get_single_mut()
        .expect("there is only one camera with the fps tag");
    let v = v.into_inner();
    let t = t.into_inner();
    if keys.any_just_released([KeyCode::W, KeyCode::A, KeyCode::S, KeyCode::D]) {
        *v = Velocity::default();
    }
    if keys.pressed(KeyCode::W) {
        *v = Velocity::from_linear(t.forward());
    }
    if keys.pressed(KeyCode::S) {
        *v = Velocity::from_linear(t.back());
    }

    if keys.pressed(KeyCode::A) {
        *v = Velocity::from_linear(t.left());
    }
    if keys.pressed(KeyCode::D) {
        *v = Velocity::from_linear(t.right());
    }
}

fn camera_orientation(
    mut player: Query<(&mut Transform, &mut FpsCamera), With<Player>>,
    keys: Res<Input<KeyCode>>,
    mouse: Res<Input<MouseButton>>,
    mut motion: EventReader<MouseMotion>,
    mut windows: ResMut<Windows>,
) {
    let (t, rot) = player
        .get_single_mut()
        .expect("there is only one camera with the fps tag");
    let t = t.into_inner();
    let rot = rot.into_inner();
    let window = windows.get_primary_mut().unwrap();
    if window.cursor_locked() {
        for m in motion.iter() {
            rot.update(&m, 1.0);
        }
        t.rotation = rot.calc_quat();
    }

    if mouse.just_pressed(MouseButton::Left) {
        window.set_cursor_lock_mode(true);
        window.set_cursor_visibility(false);
    }

    if keys.just_pressed(KeyCode::Escape) {
        window.set_cursor_lock_mode(false);
        window.set_cursor_visibility(true);
    }
}

fn main() {
    let app = App::new()
        .insert_resource(WindowDescriptor {
            title: "BEVY".into(),
            vsync: true,
            mode: WindowMode::BorderlessFullscreen,
            ..Default::default()
        })
        .insert_resource(Msaa { samples: 4 })
        .add_plugins(DefaultPlugins)
        .add_plugin(WorldInspectorPlugin::new())
        .add_plugin(PhysicsPlugin::default())
        .add_startup_system(spawn_camera)
        .add_startup_system(spawn_sphere)
        .add_system(camera_movement)
        .add_system(camera_orientation)
        .run();
}
```

## What you expected to happen
Smooth lightning, but it just cuts it of (the cut moves with the camera).

![screenshot_2022-04-09_21-49-58_858074264](https://user-images.githubusercontent.com/69082876/162617019-8ee661a2-180b-4537-a35f-905e395054ba.png)

**Comment by devil-ira** [comment] 2022-04-10 12:48
This issue is fixed on the main branch. And bevy 0.7 will be releasing soon:tm: 
In the mean time lowering your `fov` will at least hide the issue.

Duplicate of #4395

**Closed** 2022-04-10 16:00 UTC
Labels: C-Bug, S-Needs-Triage
