### ISSUE TITLE
`WindowDescriptor` has no effect if resource is inserted after `.add_plugins(DefaultPlugins)` is called during app construction

### ISSUE THREAD

**Issue by colepoirier** [bevyengine/bevy#4386] opened 2022-04-01 03:37 UTC
## Bevy version

main as of date of filing (648544faf1c50dd1599ea9409e265fe4b3bf40c3)

## Operating system & version

Linux Mint 20.3, X11

## What you did

Inserted `WindowDescriptor` resource after calling `.add_plugins(DefaultPlugins)`.

## What you expected to happen

`WindowDescriptor` to take effect regardless of order of method calls during app construction.

## What actually happened

App construction ordering where `WindowDescriptor` works like you would expect:

```rust
use bevy::prelude::*;

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .insert_resource(WindowDescriptor {
            title: "Test Title".to_string(),
            width: 1920.0,
            height: 1080.0,
            ..Default::default()
        })
        .run();
}
```

App construction ordering where `WindowDescriptor` does not work like you would expect:

```rust
use bevy::prelude::*;

fn main() {
    App::new()
        .insert_resource(WindowDescriptor {
            title: "Test Title".to_string(),
            width: 1920.0,
            height: 1080.0,
            ..Default::default()
        })
        .add_plugins(DefaultPlugins)
        .run();
}
```

## Additional information

Repro repo <https://github.com/colepoirier/bevy_app_construction_bug_repro.git>, first commit is the working version, second commit is the repro of this app construction ordering bug.

Related to #1255

**Comment by ickk** [comment] 2022-04-01 04:01
related to: https://github.com/bevyengine/bevy/issues/2879

**Comment by colepoirier** [comment] 2022-04-01 05:09
> related to: #2879

Ah fantastic! Thanks for pointing this out @ickk!

For quick reference it is first mentioned in this comment IIUC: <https://github.com/bevyengine/bevy/issues/2879#issuecomment-931207648>.

**Comment by alice-i-cecile** [comment] 2022-04-03 00:39
Another cursed bug caused by #1255.

**Comment by rparrett** [comment] 2022-11-01 13:50
I believe this was fixed by https://github.com/bevyengine/bevy/pull/6336

**Closed by rparrett** 2022-11-01 13:50 UTC
Labels: C-Bug, A-Windowing
