### ISSUE TITLE
Adding a run criterium to a system set overrides the phase that it's meant to run in.

### ISSUE THREAD

**Issue by Victov** [bevyengine/bevy#5379] opened 2022-07-19 15:05 UTC
## Bevy version
release 0.7

## What you did

I created a system set with 
```rust
app.add_system_set(
       SystemSet::on_enter(GameState::Game)
       .with_run_criteria(some_criterion_here)
       .with_system(some_startup_system)
)
```

## What went wrong

Since adding the run criterion, the `some_startup_system` started ticking every frame. It seems that adding a run criterion to a system set overrides the "phase" it is meant to run in. I'm expecting the SystemSet to respect its designated phase (begin, not update) while also respecting my run criterion. The additional run criterion should not be an override, but rather treated additively.

edit: grammar

**Comment by Nilirad** [comment] 2022-07-19 15:39
Possible duplicate of  #1839.

This is a very known bug that will be resolved by the now-in-design, stageless schedule (bevyengine/rfcs#45).

**Closed** 2022-12-04 08:05 UTC
Labels: C-Bug, S-Duplicate, A-ECS
