### ISSUE TITLE
SystemSet::on_in_stack_update doesn't work as expected

### ISSUE THREAD

**Issue by nadejin** [bevyengine/bevy#3179] opened 2021-11-24 18:13 UTC
## Bevy version

Both 0.5 and the latest version from the repository.

## Operating system & version

Windows 10.

## What you did

Tried to implement pause/resume feature by pushing a state on top of the main state, and a "background" system that should work while the main state is both active/inactive.
Background system is set up using `SystemSet::on_in_stack_update(MyState)`.

## What you expected to happen

Assuming to `on_in_stack_update` method name, I expected that the system should run while the state is anywhere on the stack, no matter if it's currently on top or not.

## What actually happened

The system is running only when the mentioned state is on top of the stack.
When I push another state, the system stops running.
So, `on_in_stack_update` works no different to plain `on_update`.

## Additional information

Here is a code snippet to reproduce this behavior.
The background system stops logging when the second state is pushed.

```
use bevy::prelude::*;

#[derive(Debug, Clone, Eq, PartialEq, Hash)]
enum AppState {
    Game,
    Paused,
}

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_state(AppState::Game)
        .add_system_set(SystemSet::on_update(AppState::Game).with_system(game.system()))
        .add_system_set(SystemSet::on_in_stack_update(AppState::Game).with_system(game_background.system()))
        .add_system_set(SystemSet::on_update(AppState::Paused).with_system(paused.system()))
        .run();
}

fn game(mut keys: ResMut<Input<KeyCode>>, mut state: ResMut<State<AppState>>) {
    info!("Running game system, current state: {:?}", *state);
    if keys.just_released(KeyCode::Space) {
        keys.reset(KeyCode::Space);
        state.push(AppState::Paused).unwrap();
    }
}

fn game_background() {
    info!("BACKGROUND GAME SYSTEM IS RUNNING!!");
}

fn paused(mut keys: ResMut<Input<KeyCode>>, mut state: ResMut<State<AppState>>) {
    info!("Running paused system, current state: {:?}", *state);
    if keys.just_released(KeyCode::Space) {
        keys.reset(KeyCode::Space);
        state.pop().unwrap();
    }
}
```

**Comment by 2ne1ugly** [comment] 2021-11-28 07:09
It seems like the PR already exists #2211
Just not merged yet...

**Comment by Teajey** [comment] 2022-06-04 11:09
Finding similar problems in 0.7.0. Just wanna leave this here instead of creating a duplicate issue.

## Bevy version

0.7.0

## What you did

Whittled this minimal reproduction down from my game project:

```rs
use bevy::prelude::*;

#[derive(Clone, PartialEq, Eq, Debug, Hash)]
pub enum SomeState {
    AnimateBackground,
    AnimateTitle,
}

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_state(SomeState::AnimateBackground)
        .add_system_set(SystemSet::on_enter(SomeState::AnimateBackground).with_system(setup))
        .add_system_set(
            SystemSet::on_in_stack_update(SomeState::AnimateTitle).with_system(animate_title),
        )
        .add_system_set(
            SystemSet::on_in_stack_update(SomeState::AnimateBackground)
                .with_system(animate_background),
        )
        .run();
}

fn setup(mut scene_state: ResMut<State<SomeState>>) {
    scene_state.push(SomeState::AnimateTitle).unwrap();
}

fn animate_title() {
    info!("animate_title");
}

fn animate_background() {
    info!("animate_background");
}
```

## What went wrong

`animate_title` and `animate_background` do not run even though `SomeState::AnimateBackground` and `SomeState::AnimateTitle` are both in the stack.

## Expected behaviour

That `animate_title` and `animate_background` both run because they are declared to run when their respective states are in the stack.

## Additional information

Making this change, `animate_background` does run, but `animate_title` doesn't, which is also quite confusing.

```diff
     App::new()
         .add_plugins(DefaultPlugins)
         .add_state(SomeState::AnimateBackground)
-        .add_system_set(SystemSet::on_enter(SomeState::AnimateBackground).with_system(setup))
+        .add_startup_system(setup)
         .add_system_set(
             SystemSet::on_in_stack_update(SomeState::AnimateTitle).with_system(animate_title),
         )
```

**Comment by james7132** [comment] 2023-02-16 20:55
With stageless merged, SystemSets no longer exist in the form they're used in this issue, and the state API has shifted significantly and no longer includes a stack. Closing this issue.

**Closed by james7132** 2023-02-16 20:55 UTC
Labels: C-Bug, A-ECS
