### ISSUE TITLE
Panic when ambiguous_with's argument is a system not in the schedule

### ISSUE THREAD

**Issue by RedBreadcat** [bevyengine/bevy#8038] opened 2023-03-11 07:26 UTC
## Bevy version
0.10.0

## What you did
Attempting to run the app panics when ambiguous_with has a system not in the schedule.
```
use bevy::prelude::*;

fn system1() {}

fn system2() {}

fn main() {
    let mut app = App::new();
    app.add_system(system1.ambiguous_with(system2));

    app.run(); // panic here
}
```

## What went wrong
The `app.run()` line panicked deep inside with the message:
`thread main panicked at called Option::unwrap() on a one value, C:\Users\Foo\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_ecs-0.10.0\src\schedule\schedule.rs:1146:56`.
Although I personally don't mind it panicking, the issue is that it's not clear which system is missing from the schedule. With dozens of systems, it becomes quite difficult to know how the system dependencies were incorrectly configured.

**Comment by alice-i-cecile** [comment] 2023-03-11 15:54
Duplicate of #7949, fixed by #7950.

**Closed by alice-i-cecile** 2023-03-11 15:54 UTC
Labels: C-Bug, A-ECS
