### ISSUE TITLE
UI scaling example crashes

### ISSUE THREAD

**Issue by darthdeus** [bevyengine/bevy#6466] opened 2022-11-04 17:13 UTC
## Bevy version

3a14ae40eea1d430c56ae6cdd3b9bdc1037656a6

## What you did

- Run `cargo run --example ui_scaling`
- Press up arrow to scale up the UI
- Press down arrow to scale it back down, immediate crash here

Pressing down first and up second also crashes

## What went wrong

```
thread 'main' panicked at 'Fatal error when processing text: exceeded 16 available TextAltases for font. This can be caused by using an excessive number of font sizes. If you are changing font sizes dynamically consider using Transform::scale to modify the size. If you need more font sizes modify TextSettings.max_font_atlases..', crates/bevy_ui/src/widget/text.rs:138:21
```

**Comment by alice-i-cecile** [comment] 2022-11-04 17:23
Broken by https://github.com/bevyengine/bevy/pull/5708, ping @xtr3m3nerd :)

**Comment by xtr3m3nerd** [comment] 2022-11-04 20:04
So this here is an example of what would have caused a memory leak before, which is what the error introduced in my change is intending to protect against. This is happening because the scale_factor in pipeline.queue_text (which is what the UiScale resource modifies) will modify the the font_size, ultimately growing the FontAtlasSet. In this example the scale is being modified dynamically on a frame by frame basis, which I  cant imaging is a typical usecase for UiScale, which I see as primarily being used for setting up UI based on screen and game settings. 

Now considering this usecase and wanting to demonstrate dynamically changing the UI the example can easily be fixed by adding:

`        .insert_resource(TextSettings { allow_dynamic_font_size: true, ..default() })`

to the example. 

In this situation the panic error text in the https://github.com/bevyengine/bevy/pull/5708 fix seems confusing. I was thinking that we should modify it to also mention that dynamically modifying the scale could also be the cause of the issue.

**Comment by alice-i-cecile** [comment] 2022-11-04 21:32
Great analysis. I think we should improve the error message, and fix the example by configuring that resource.

**Closed** 2022-11-05 14:11 UTC
Labels: C-Bug, D-Good-First-Issue, C-Examples, A-UI
