### ISSUE TITLE
Several frames of input lag for breakout example

### ISSUE THREAD

**Issue by sullyj3** [bevyengine/bevy#2871] opened 2021-09-26 08:24 UTC
## Bevy version
`main` (d158e0893ea88b6acf523a4264f076d6e0b540c6)

## Operating system & version

Windows 10

## What you did

On main branch, `cargo run --example breakout --release`
Press left and right

## What you expected to happen

Low latency input

## What actually happened

Several frames pass before response

## Additional information

[Video](https://drive.google.com/file/d/1P7_Gdzkeh3HFLeDtIcoWB87esNoUdu0J/view?usp=sharing)

**Comment by cart** [comment] 2021-09-27 23:47
This seems like a duplicate of #760. If you [disable vsync](https://github.com/bevyengine/bevy/blob/main/examples/window/window_settings.rs#L10), does the lag get any better. Last time we investigated this, it was caused by wgpu's "fifo" vsync mode. "Mailbox" vsync doesn't suffer from that, but it also doesn't do any sort of frame limiting, so we can't enable it by default (and it also isn't available on all machines).

Other people have reproed this (including myself), so you aren't alone.

I do think this is something we need to fix. Mailbox vsync isn't a general-purpose solution, nor is disabling vsync entirely. I have a feeling this will either require:
1. Changing how we process input
2. Changing how / where we draw (MainEventsCleared vs OnRedrawRequested)
3. _Maybe_ changing something in upstream wgpu (but i doubt this is an issue on their end).

My bet is that (2) is the issue. The issue is that it required splitting out render logic from app logic. We did this as part of the renderer rework ( #2535). I'm planning on reworking how winit interacts with the new bevy_render in the very near future (before the next Bevy release).  

Relevant discord conversations:
* https://discord.com/channels/691052431525675048/742884593551802431/756650479899115561
* https://discord.com/channels/691052431525675048/692572690833473578/778678729793601568

**Comment by sullyj3** [comment] 2021-09-28 02:48
Yep, disabling vsync definitely seems to improve things. Good to know it's not just me.

**Comment by sullyj3** [comment] 2021-09-28 02:48
I'm happy for you to close this if it's a dupe

**Comment by cart** [comment] 2021-09-28 20:30
Cool yeah I think that makes the most sense.

**Closed by cart** 2021-09-28 20:30 UTC
Labels: C-Bug, A-Input, S-Needs-Investigation
