### ISSUE TITLE
Unify RenderLayers and TargetCamera

### ISSUE THREAD

**Issue by UkoeHB** [bevyengine/bevy#12485] opened 2024-03-14 23:48 UTC
## What problem does this solve or what need does it fill?

Currently there are four ways to group entities so they will be incorporated into a given `Camera's` view:

**Default**
- A 'plain' entity has no `RenderLayers` component OR has the default `RenderLayers` component (layer 0).
- *Grouping 1*: Plain cameras can see plain entities if they are in-frustum and not `Visibility::Hidden`.

**RenderLayers**
- A 'layer' entity has a non-default `RenderLayers` component.
- *Grouping 2*: Layer cameras can see a layer entity if the camera's and entity's `RenderLayer` components intersect (and if the entity is visible).

**TargetCamera**
- A 'target' entity has a `TargetCamera` component. Note that `TargetCamera` is propagated from cameras (where it must be manually inserted) to UI nodes automatically.
- *Grouping 3*: Plain-target cameras can see plain-target `Node` entities (if visible).
- *Grouping 4*: Layer-target cameras can see layer-target `Node` entities (if visible).

Within these groupings there are several limitations:
- A camera cannot see both plain and layer entities. This is because `!RenderLayers::layer(0).intersects(RenderLayers::layer(0).with(1))`.
- There are only 32 `RenderLayers` for efficiency reasons.
- `TargetCamera` is limited to UI nodes, but you can have near-unlimited `TargetCameras` (as far as I understand it).

## What solution would you like?

Unify the grouping logic:

```rust
enum RenderGroup {
    Default,
    Layers {
        default: bool,
        layers: RenderLayers,
    },
    Camera(Entity)
}
```

This replaces `RenderLayers` and `TargetCamera`. `TargetCamera` should instead be a marker component that identifies UI camera root nodes, and the UI code should force all `Node` children of the camera to have `RenderGroup::Camera`. Then UI cameras can be given a `RenderGroup` component to add *additional* grouping visibility (in addition to its inherent self-visibility).

I include the `RenderGroup::Layers::default` field so you can view 'plain' entities in addition to layer entities. Adding this field does not increase space consumption in the enum, since the `Camera` variant requires 8 bytes while `RenderLayers` is 4 bytes.

## What alternative(s) have you considered?

- Leave it as-is.

## Additional context

In the abstract it would be nice to allow multiple camera groupings on an entity. However that would probably require a perf regression. Note that this proposal increases entity storage from 4 bytes with `RenderLayers` and 8 bytes with `TargetCamera` to 10 bytes with `RenderGroup` (2 bytes for the variant index + 8 bytes for the camera entity).

**Comment by james7132** [comment] 2024-03-14 23:50
This looks like a duplicate of #12468 to me.

**Closed as completed** 2024-03-14 23:52 UTC
Labels: A-Rendering, A-UI, C-Usability
