### ISSUE TITLE
Adding another camera with RenderTarget::Image seemingly causes UiImage to disobey render layers

### ISSUE THREAD

**Issue by yamgent** [bevyengine/bevy#5594] opened 2022-08-06 14:55 UTC
## Bevy version

[c27cc59](https://github.com/bevyengine/bevy/commit/c27cc59e0d1e305b0ab42b07455c3550ed671740) - latest main branch commit at the time of this writing.

## What you did

I spawned 2 cameras. The 1st camera renders to an image, while the 2nd camera renders to the window. The image rendered by the 1st camera is **not** used by the 2nd camera at all.

I then spawned a UI image bundle.

The render layers are:

* 0: 1st camera, UI image
* 1: 2nd camera.

```rs
use bevy::{
    prelude::*,
    render::{
        camera::RenderTarget,
        render_resource::{
            Extent3d, TextureDescriptor, TextureDimension, TextureFormat, TextureUsages,
        },
        texture::ImageSampler,
        view::RenderLayers,
    },
};

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_startup_system(setup)
        .run();
}

fn setup(
    windows: Res<Windows>,
    mut commands: Commands,
    mut images: ResMut<Assets<Image>>,
    asset_server: Res<AssetServer>,
) {
    // --- camera rendering to image ---
    // if this camera is removed, then the bug won't occur
    let size = Extent3d {
        width: 16,
        height: 16,
        ..default()
    };

    let mut image = Image {
        texture_descriptor: TextureDescriptor {
            label: None,
            size,
            dimension: TextureDimension::D2,
            format: TextureFormat::Bgra8UnormSrgb,
            mip_level_count: 1,
            sample_count: 1,
            usage: TextureUsages::TEXTURE_BINDING
                | TextureUsages::COPY_DST
                | TextureUsages::RENDER_ATTACHMENT,
        },
        ..default()
    };
    image.resize(size);
    let image_handle = images.add(image);

    commands
        .spawn_bundle(Camera3dBundle {
            camera: Camera {
                target: RenderTarget::Image(image_handle),
                ..default()
            },
            ..default()
        })
        .insert(RenderLayers::layer(0));

    // --- camera rendering to window ---
    commands
        .spawn_bundle(Camera3dBundle {
            camera: Camera {
                priority: 1,
                target: RenderTarget::Window(windows.get_primary().unwrap().id()),
                ..default()
            },
            ..default()
        })
        .insert(RenderLayers::layer(1));

    // --- image that is used by camera rendering to image ---
    commands
        .spawn_bundle(ImageBundle {
            style: Style {
                size: Size::new(Val::Px(256.0), Val::Px(256.0)),
                ..default()
            },
            image: asset_server.load("bevy.png").into(),
            ..default()
        })
        .insert(RenderLayers::layer(0));
}
```

## What went wrong

* what were you expecting?

I should see nothing, because the image is only visible to the 1st camera, and the output of the 1st camera is not used at all.

* what actually happened?

 I can see the image in full, suggesting that the 2nd camera is rendering it somehow...?

## Additional information

As suggested in the code, removing the 1st camera while leaving the rest untouched causes the bug to disappear.

**Comment by devil-ira** [comment] 2022-08-06 15:09
UI does not respect `RenderLayers`.
You may want to place the image on a quad mesh instead.

**Comment by alice-i-cecile** [comment] 2023-03-02 19:47
Closing as a duplicate of #6069 :)

**Closed by alice-i-cecile** 2023-03-02 19:47 UTC
Labels: C-Bug, A-Rendering, A-UI
