### ISSUE TITLE
Segmentation Fault on OSX on main branch

### ISSUE THREAD

**Issue by ManevilleF** [bevyengine/bevy#8211] opened 2023-03-25 11:16 UTC
> Possibly related to #8144
> Closed by #8180 and #8223

## Bevy version

Crash on: `0.11-dev` (the `main` branch) commit 289fd1d
Doesn't crash on: `0.10` commit 4f16d6e

EDIT: After investigation it seems it crashes since commit 6a85eb3 (#6529)

## System information

- rust 1.68.0
- system info: 
  - os: "MacOS 13.0.1 "
  - kernel: "22.1.0"
  -  cpu: "Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz"
  -  core_count: "6"
  -  memory: "16.0 GiB" 
- adapter info: 
  - name: "AMD Radeon Pro 5300M" 
  - vendor: 0
  -  device: 0
  -  device_type: DiscreteGpu 
  - backend: Metal

## What you did

I run any bevy example

## What went wrong

- what were you expecting?

The example should run

- what actually happened?

The examples compile but crash at runtime with a segmentation fault:

`[1]    33800 segmentation fault  cargo run --example $EXAMPLE_NAME`

The (empty) window appears for a split second before the crash.

## Additional information

This crash only happens on the `main`branch, the `0.10` release and prior versions did not

**Comment by mockersf** [comment] 2023-03-25 11:25
can't reproduce on a Mac with an m1

**Comment by ManevilleF** [comment] 2023-03-25 11:26
@mockersf  After investigation it seems it crashes since commit https://github.com/bevyengine/bevy/commit/6a85eb3d7eb6d8187c854318587c37e700b7a345 (https://github.com/bevyengine/bevy/pull/6529) So the addition of `bevy_gizmos`

**Comment by mockersf** [comment] 2023-03-25 11:32
Could you check which commit you are running on? the commit you mention in the issue is before gizmos were added. There was also a fix a few commits after, so could you retry with latest man?

**Comment by ManevilleF** [comment] 2023-03-25 11:35
> Could you check which commit you are running on? the commit you mention in the issue is before gizmos were added. There was also a fix a few commits after, so could you retry with latest man?

#8151 does'nt fix the crash but I just checked out @devil-ira fix #8180 and it works !

**Comment by mockersf** [comment] 2023-03-25 12:38
just tried gizmo related examples, `2d_gizmos` segfault for me but not `3d_gizmos`

**Comment by ManevilleF** [comment] 2023-03-25 14:13
> just tried gizmo related examples, `2d_gizmos` segfault for me but not `3d_gizmos`

With the fix ?

Because for me, on main, any example segfaults, even the examples unrelated to gizmos like UI or sprite examples

**Comment by rparrett** [comment] 2023-03-26 14:06
Any example with a 2d camera is segfaulting for me.

I think this is a duplicate of #8144.

#8151 fixed a separate bug that came up while investigating that one.

#8180 only mitigates it for examples that do not spawn gizmos. `2d_gizmos` still segfaults.

**Closed** 2023-03-29 18:34 UTC
Labels: C-Bug, O-MacOS
