### ISSUE TITLE
4k texture model loading is way to slow.

### ISSUE THREAD

**Issue by HyeokSuLee** [bevyengine/bevy#1947] opened 2021-04-17 04:01 UTC
It took over 1 minute as gltf extension.
Is there some solution for pre load?
Or command to load and check when loading is complete.

**Comment by alice-i-cecile** [comment] 2021-04-17 04:04
See #1307 for your last request :)

**Comment by DJMcNab** [comment] 2021-04-17 06:09
Have you tried running in release mode? The `image` crate is very slow in debug mode

You can also set up your project so that cargo builds your dependencies in release mode. I'm on mobile, so it's hard to check, but I think it's in `Cargo.toml`:

```toml
[profile.dev.package.*]
opt-level = 3
```

**Comment by HyeokSuLee** [comment] 2021-04-17 13:51
> Have you tried running in release mode? The `image` crate is very slow in debug mode
> 
> You can also set up your project so that cargo builds your dependencies in release mode. I'm on mobile, so it's hard to check, but I think it's in `Cargo.toml`:
> 
> ```toml
> [profile.dev.package.*]
> opt-level = 3
> ```

yeah, you are right. in release mode it is fast enough. 
Can you tell me more detail about build dependencies in release mode ?
I've tried with below but it doesn't seem to work.

`[dependencies]
bevy = "0.5.0"
[profile.dev.package.bevy]
opt-level = 3`

**Comment by DJMcNab** [comment] 2021-04-17 15:09
Dependencies are built with whatever profile applies to them. In this case, you have asked exactly the bevy crate to be built in release mode, which will have no effect, because the `bevy` crate itself is only a wrapper crate. I personally use exactly the code snippet I advised you use (the one using using `[profile.dev.package.*]`) in my `Cargo.toml`. There is more documentation in [the cargo book](https://doc.rust-lang.org/cargo/reference/profiles.html#overrides).

Bevy locates assets based on the cargo workspace root, environment environment variable with a fallback to the current executable location. This is implemented here: https://github.com/bevyengine/bevy/blob/20673dbe0e935d9b7b4fdc8947830bfcff6bc071/crates/bevy_asset/src/io/file_asset_io.rs#L29-L41

To use a bevy program in a different folder, you should set the `CARGO_MANIFEST_DIR` environment variable, or you can move the executable manually. There are plans for further integration with [Distill](https://github.com/amethyst/distill), which might improve this situation. This work is tracked in #708

**Comment by alice-i-cecile** [comment] 2021-04-17 16:04
I'm going to close this for now, but feel free to ask for any more assistance that you need, either here, in the Discussions or on Discord @HyeokSuLee <3

Asset loading speed will continue to be improved, but I think the issue is resolved for now thanks to release mode.

**Closed by alice-i-cecile** 2021-04-17 16:04 UTC
Labels: assets, performance
