### ISSUE TITLE
Apple Silicon support

### ISSUE THREAD

**Issue by darthdeus** [bevyengine/bevy#928] opened 2020-11-25 20:52 UTC
**Bevy version**

01ba7c44

**Operating system & version**

macOS Big Sur 11.0.1

**What you did**

Ran `cargo run --example breakout`

**What you expected to happen**

I expected the example to compile and run.

**What actually happened**

The example failed to compile with the following error

```
error: failed to run custom build command for `bevy-glsl-to-spirv v0.2.1`

Caused by:
  process didn't exit successfully: `/Users/darth/projects/bevy/target/debug/build/bevy-glsl-to-spirv-fa67d3095c93334b/build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'Missing target support aarch64-apple-darwin', /Users/darth/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy-glsl-to-spirv-0.2.1/build/build.rs:24:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by cart** [comment] 2020-11-25 20:55
Good to know. We _might_ be able to work around this by using shaderc on the `aarch64-app-darwin` target (which we already do for ios).

**Comment by mockersf** [comment] 2020-11-25 21:32
which can be done [around here](https://github.com/bevyengine/bevy/blob/master/crates/bevy_render/Cargo.toml#L49) if someone with a new Mac wants to try (adding the arch at the same place of the iOS target is checked for, and also probably a few changes in the crate too)

**Comment by joshuajbouw** [comment] 2020-11-27 12:57
@cart 11.0 Big Sur can be added to the CI as the preview had been added but, I'm not entirely too sure if it actually is compiling to the ARM target or not. It should be able to else ARM chip Apple would've had nothing at launch haha.

Would be a good idea to add that target to shaderc and trying to build an ARM example for Big Sur as a new CI.

**Comment by joshuajbouw** [comment] 2020-11-27 18:02
Update: https://blog.rust-lang.org/2020/11/27/Rustup-1.23.0.html <- M1 support just released it looks like.

```
Rustup is now natively available for the new Apple M1 devices, allowing you to install it on the new Macs the same way you'd install it on other platforms!

Note that at the time of writing this blog post the aarch64-apple-darwin compiler is at Tier 2 target: precompiled binaries are available starting from Rust 1.49 (currently in the beta channel), but no automated tests are executed on them.```

**Comment by frewsxcv** [comment] 2020-12-08 00:05
I opened a pull request that enables shaderc for Apple Silicon targets. All we need besides that is a new version of winit published! https://github.com/rust-windowing/winit/issues/1789

**Comment by frewsxcv** [comment] 2020-12-09 21:19
#1027 has merged. Now we wait for https://github.com/rust-windowing/winit/pull/1793

**Comment by frewsxcv** [comment] 2020-12-10 22:16
Alright, this should be the last pull request needed for Apple Silicon support: https://github.com/bevyengine/bevy/pull/1043/

**Closed** 2020-12-13 19:27 UTC
Labels: bug, platform macos

**Comment by cart** [comment] 2020-12-13 19:29
Great work everyone!

**Comment by enfipy** [comment] 2021-01-06 08:22
Recently, I've got an m1 mac and tried to build some bevy examples. Got shaderc errors while compiled bevy.

<img width="1158" alt="Screenshot 2021-01-06 at 10 18 55" src="https://user-images.githubusercontent.com/24860875/103745683-96821500-5008-11eb-818d-06a55e392d40.png">

**Comment by cart** [comment] 2021-01-06 19:37
Dang I thought #1027 had shaderc working on m1s

**Comment by enfipy** [comment] 2021-01-06 19:39
Well, I'm planning to reinstall my operating system and set up everything again tonight. Maybe this will help o_o

**Comment by frewsxcv** [comment] 2021-01-13 17:50
@enfipy Do you get the same error?

**Comment by enfipy** [comment] 2021-01-19 17:32
@frewsxcv Finally I managed to reinstall macOS and got the same error. Steps to reproduce this error on a clean M1 device:
1. Install Rust with `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`.
2. Clone `bevy` repo.
3. Run `cargo run --example ui`

<img width="991" alt="Screenshot 2021-01-19 at 19 27 03" src="https://user-images.githubusercontent.com/24860875/105070690-51d88e00-5a8c-11eb-94bb-d0532c1fe8d2.png">

The last time I tried to install `cmake` - I got pretty poor same results but with installed `cmake` for x86_64.

**Comment by frewsxcv** [comment] 2021-01-19 17:40
What happens if you install the ARM version of `cmake`? What happens if you do `file $(which cmake)`?

**Comment by enfipy** [comment] 2021-01-19 17:47
What is the right way to install cmake for ARM?

Result for `file $(which cmake)`:
```
cmake: cannot open `cmake' (No such file or directory)
not:   cannot open `not' (No such file or directory)
found: cannot open `found' (No such file or directory)
```

**Comment by frewsxcv** [comment] 2021-01-19 17:54
Do you have Homebrew installed? If so, `brew install cmake`

**Comment by enfipy** [comment] 2021-01-19 18:01
Now got this error:
```
 [ 44%] Built target build-version

  --- stderr
  CMake Warning (dev) at CMakeLists.txt:8 (project):
    Policy CMP0048 is not set: project() command manages VERSION variables.
    Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
    command to set the policy and suppress this warning.

    The following variable(s) would be set to empty:

      CMAKE_PROJECT_VERSION
      CMAKE_PROJECT_VERSION_MAJOR
      CMAKE_PROJECT_VERSION_MINOR
      CMAKE_PROJECT_VERSION_PATCH
  This warning is for project developers.  Use -Wno-dev to suppress it.

  CMake Warning (dev):
    Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
    --help-policy CMP0042" for policy details.  Use the cmake_policy command to
    set the policy and suppress this warning.

    MACOSX_RPATH is not specified for the following targets:

     SPIRV-Tools-shared
     shaderc_shared

  This warning is for project developers.  Use -Wno-dev to suppress it.

  clang: error: cannot use 'precompiled-header' output with multiple -arch options
  make[2]: *** [glslang/glslang/CMakeFiles/MachineIndependent.dir/cmake_pch_x86_64.hxx.pch] Error 1
  make[1]: *** [glslang/glslang/CMakeFiles/MachineIndependent.dir/all] Error 2
  make[1]: *** Waiting for unfinished jobs....
  make: *** [all] Error 2
  thread 'main' panicked at '
  command did not execute successfully, got: exit code: 2

  build script failed, must exit now', /Users/enfipy/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.45/src/lib.rs:894:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by darthdeus** [comment] 2021-01-20 00:54
I've definitely had a `shaderc` related build fail (even today), but it seems `cargo clean` or just doing `--release` or removing `--release` fixes it. I know this isn't probably super useful, but just wanted to confirm that it is possible to make it work on M1. 

Unfortunately I can't really reproduce the failure anymore, running `cmake` 3.19.3 installed via homebrew. Have you tried running Rust nightly? I've only tried it on 1.51.0

**Comment by enfipy** [comment] 2021-01-20 10:21
@darthdeus Tested on 1.49.0 stable with and without `--release` flag after `cargo clean` - got the same error.

Tried to build with rust 1.51.0 nightly but still with that error.

Command `cmake --version` results in:
```sh
cmake version 3.19.3

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

Also, installed it with `brew` as specified @frewsxcv above.

**Comment by bjorn3** [comment] 2021-01-20 11:42
What does `file $(which cmake)` give now? That should show if cmake is built for arm. If any parent of clang is an x86_64 executable running using Rosetta, it will forcefully build x86_64 binaries.

**Comment by enfipy** [comment] 2021-01-20 12:04
@bjorn3 It results in:
```
$ file $(which cmake)
/opt/homebrew/bin/cmake: Mach-O 64-bit executable arm64
```

**Comment by ostwilkens** [comment] 2021-01-24 12:07
I'm on an M1 Macbook Air and trying to make sense of this. 

I was using the 0.4.0 bevy crate in my project, no problem. 
Then I got a build error from shaderc when trying to run an example in https://github.com/bonsairobo/building-blocks. 
It also uses 0.4.0 bevy, so I was confused. 

Trying to identify the cause, I added this to the .toml of my project: 
```
[target.'cfg(all(target_arch = "aarch64", target_os = "macos"))'.dependencies]
shaderc = "0.7.0"
```
This shouldn't make a difference, as I'm depending on bevy_render, which also contains this. 
However, this caused shaderc to fail to build. **And now I can't get my project to build again, no matter what I do.** 💩

My cmake is an universal binary: 
```
$ file $(which cmake)
/usr/local/bin/cmake: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64]
/usr/local/bin/cmake (for architecture x86_64):	Mach-O 64-bit executable x86_64
/usr/local/bin/cmake (for architecture arm64):	Mach-O 64-bit executable arm64
```

This is the error I get from shaderc-sys:
```
clang: error: cannot use 'precompiled-header' output with multiple -arch options
  make[2]: *** [glslang/glslang/CMakeFiles/MachineIndependent.dir/cmake_pch_x86_64.hxx.pch] Error 1
  make[1]: *** [glslang/glslang/CMakeFiles/MachineIndependent.dir/all] Error 2
  make[1]: *** Waiting for unfinished jobs....
  make: *** [all] Error 2
  thread 'main' panicked at '
  command did not execute successfully, got: exit code: 2
```

It could be that my project was before, for some reason, running under rosetta? I'm not sure. 
All this platform jumping is give me a headache.

**Comment by ostwilkens** [comment] 2021-01-24 13:19
Aha. My VS Code is running under arch `i386`. If I start a build from VS Code, a `cargo clean` is required, and i can then successfully build from a non-rosetta terminal. I need to get the arm64 version. 
@bjorn3 was spot on. 

@enfipy What terminal are you using? Could it be running under rosetta? Try the `arch` command.

**Comment by enfipy** [comment] 2021-01-24 14:14
@ostwilkens Wow, it worked as I made `cargo clean` and ran it on the default macOS terminal! Thank you so much!

**Comment by shabaduu** [comment] 2021-03-04 01:37
I'm running into the exact same error as enfipy above. I'm using the arm64 version 3.19.6 of cmake installed via homebrew and I'm using the nightly version of the rust toolchain. I'm very much new to coding and am not sure where to go from here. Was wondering if I could get some help.

**Comment by lord** [comment] 2021-05-12 02:22
i think this also works

```
cargo clean
arch -arm64 cargo run
```

**Comment by bjorn3** [comment] 2021-10-15 08:54
```
Did find:
    /usr/local/opt/llvm/lib/libclang.dylib: mach-o, but wrong architecture
```
It seems like rustc and libclang are compiled for different cpu architectures. Are you using an x86_64 or AArch64 rustc installation? And did brew install an x86_64 or AArch64 version of libclang? I think you can use `file /usr/local/opt/llvm/lib/libclang.dylib` to check which arch is used for libclang.
