### ISSUE TITLE
Gamepad Input Support

### ISSUE THREAD

**Issue by PradeepKumarRajamanickam** [bevyengine/bevy#455] opened 2020-09-07 16:43 UTC
It would be nice to have support for popular gamepads with standard dual analog controls.

Popular Controllers (as of 2018)
1. Xbox 360
2. PS4
3. Xbox One

![survey](https://user-images.githubusercontent.com/4343031/92406875-c6063b00-f156-11ea-8e80-691e584b4cb3.jpg)
_Source: Steam Blog_

More info: https://steamcommunity.com/games/593110/announcements/detail/1712946892833213377

**Comment by memoryruins** [comment] 2020-09-07 19:49
It would definitely be nice! There is a former gamepad tracking issue at https://github.com/bevyengine/bevy/issues/94, and an open PR that adds support with `gilrs` craate https://github.com/bevyengine/bevy/pull/280

**Comment by cart** [comment] 2020-09-07 20:49
Yup I agree that this is basically a must have. Closing as a dupe of #94

**Closed by cart** 2020-09-07 20:49 UTC
