### ISSUE TITLE
2D camera renders nothing if scale is < 1.0

### ISSUE THREAD

**Issue by inodentry** [bevyengine/bevy#239] opened 2020-08-19 07:03 UTC
As I am trying to get my scene to fit on-screen (difficult with the default orthographic projection, but that's another issue), I noticed that nothing is being rendered if the camera scale is < 1.0.

```rust
let mut camera = Camera2dComponents::default();
camera.scale = Scale(0.9);
commands.spawn(camera);
```

If the scale is above 1.0, the view becomes "zoomed out" (everything renders smaller). If the scale is any value below 1.0 (like in the example above), I get a blank screen with nothing rendered.

**Comment by cart** [comment] 2020-08-19 07:07
i have a feeling this has to do with depth / clip distance. if thats the problem, we could consider increasing the near/far distance to see if that resolves this problem.

**Comment by Matthew-Maclean** [comment] 2020-09-13 19:38
@Finnerale When you set `far` to `1000.0 / scale`, did you just plug `far` into the translation and orthographic camera, Or were there more places to use it? Those were all the places I could see to use it, but I still can't get anything to draw. I also tried with `far = f32::MAX`, but I couldn't get anything.

**Comment by Finnerale** [comment] 2020-09-13 21:01
@Matthew-Maclean All I did, was setting `OrthographicProjection { far: 1000.0 / scale }` and `Scale(scale)` then my sprites showed up with any scale I tried.

**Comment by Matthew-Maclean** [comment] 2020-09-13 21:22
@Finnerale Ok, so you didn't touch the `translation`. That method worked for me. Thanks.

**Comment by concave-sphere** [comment] 2021-02-19 03:49
I am experiencing the same behavior, but setting `far` to 1000.0 / scale does not fix it for me.  However, it does work for me (everything(*) shows up at all the scales I tried) if I do this after adjusting the scale:

```
        camera_transform.translation.z = 999.0 * camera_transform.scale.x;
```

(*) I'm drawing a grid of lines (with lyon) and they start to "twinkle" in and out when I zoom out too far, but I'm guessing that's a different category of problem, something to do with rendering polygons that are smaller than a pixel.

**Comment by alice-i-cecile** [comment] 2022-03-21 00:13
Closing as stale. Feel free to reopen if you have a modern reproduction.

**Comment by colepoirier** [comment] 2022-03-21 07:06
@alice-i-cecile unfortunately this is still an issue. Here is a minimum reproducible example using bevy main as of today: <https://github.com/colepoirier/bevy_2d_camera_scale_repro/tree/master>.

**Comment by ostwilkens** [comment] 2022-04-16 18:23
I investigated a bit, but don't know enough about the rendering pipeline to have opinions on what to do about it. 

The `view_proj` uniform is set in `bevy_render > src > view > mod.rs:155`. 
It is used in `bevy_sprite > src > render > sprite.wgsl:26` to set `VertexOutput.position`. 

`out.position.z` scales with `camera.transform.scale`. 

if `camera.transform.scale = Vec3::splat(1.0);` then `out.position.z = 0`
if `camera.transform.scale = Vec3::splat(0.9);` then `out.position.z = -0.12`
if `camera.transform.scale = Vec3::splat(0.8);` then `out.position.z = -0.25`

When `out.position.z` is less than 0, it doesn't render.

**Comment by superdump** [comment] 2022-07-13 22:23
Adjust the orthographic projection scale, not the camera transform scale. The latter will end up moving the vertices outside the view frustum defined by the projection. Scaling the orthographic projection only adjusts the left/right/top/bottom bounds of the view frustum and doesn't touch the near/far, which is what you want for zooming.

**Comment by targrub** [comment] 2022-10-07 16:34
> @alice-i-cecile unfortunately this is still an issue. Here is a minimum reproducible example using bevy main as of today: https://github.com/colepoirier/bevy_2d_camera_scale_repro/tree/master.

When I run this on Bevy|main, I always see the blue square, and scale is always reported as Vec3(1.0, 1.0, 1.0).  a) Is this exercising the failure scenario?, b) Is the problem fixed?, c) Does the example need to be adjusted?

**Comment by alice-i-cecile** [comment] 2022-10-07 18:55
This is a valid reproduction. Does the perceived zoom level actually change? If not, I would probably call this "basically fixed, but needs a warning somewhere". If it does, via implicitly updating the orthographic projection's scale field, I would call this fixed but likely in need of more documentation.

**Comment by TimJentzsch** [comment] 2024-01-24 17:36
I cannot reproduce the issue with Bevy 0.12 anymore, closing this issue.

I used the reproduction code by @colepoirier, adapted to 0.12: <https://github.com/colepoirier/bevy_2d_camera_scale_repro/pull/1>

I can see the zoom effect and the sprite is always rendered, also for a scale of `Vec3(0.9, 0.9, 0.9)`.

**Closed by TimJentzsch** 2024-01-24 17:36 UTC
Labels: C-Bug, A-Rendering

**Comment by the-az-dev** [comment] 2024-07-06 08:59
This code sheet saves my nerves and time (thankfully GPT):

```rust
commands.spawn(Camera2dBundle {
        transform: Transform::from_xyz(100., 0., 1000.), // Set Z transform to 1000.0 for saving far distance in general option
        projection: OrthographicProjection {
            scaling_mode: ScalingMode::FixedVertical(500.0), // you can change scale based on your needings
            ..default()
        }.into(),
        ..default()
    })
```

So, the main problem is that, Camera have un-predictable option on zooming at long far distance when `Transform.Z` equals `0`. To obtain this feature you need to set static posizition at Z cordinate and set scaling based on your needings. It can helps even in another problem, when you want save scale and zoom parameters when you change window size.

You don`t need to write code-lines where you setup distance and scaling for your camera. You can set this when you create Camera 2d and this can save your time.
