### ISSUE TITLE
`bevy::diagnostic::FrameTimeDiagnosticsPlugin` cannot obtain true FPS with modifying `bevy::time::TimeUpdateStrategy`

### ISSUE THREAD

**Issue by Neutron3529** [bevyengine/bevy#15409] opened 2024-09-24 09:51 UTC
## Bevy version

0.14.2

## What you did

Writting down such minimal example:
```rust
use bevy::prelude::*;

fn main() {
    App::new()
        .add_plugins(bevy::diagnostic::LogDiagnosticsPlugin::default())
        .add_plugins(bevy::diagnostic::FrameTimeDiagnosticsPlugin::default())
        .add_plugins(DefaultPlugins)
        .add_systems(Startup, init)
        // .add_systems(Update, despawn)
        .run();
}

fn init(mut tus: ResMut<bevy::time::TimeUpdateStrategy>) {
    *tus = bevy::time::TimeUpdateStrategy::ManualDuration(std::time::Duration::from_secs(100));
}
```

## What went wrong

The actual FPS (which could be calculated from the wall logging time) does not reported.
Instead, a fixed fps `0.01` is reported every frame.

```
$ cargo run --release
   Compiling minimal v0.1.0 (/me/bug)
    Finished `release` profile [optimized] target(s) in 2.13s
     Running `target/release/minimal`
2024-09-24T09:24:28.335904Z  INFO bevy_render::renderer: AdapterInfo { name: "NVIDIA GeForce RTX 3060 Laptop GPU", vendor: 4318, device: 9504, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "560.35.03", backend: Vulkan }
2024-09-24T09:24:28.938985Z  INFO bevy_winit::system: Creating new window "App" (Entity { index: 0, generation: 1 })
2024-09-24T09:24:28.951865Z  INFO bevy diagnostic: fps        :    0.010000   (avg 0.010000)
2024-09-24T09:24:28.951907Z  INFO bevy diagnostic: frame_time : 100000.000000ms (avg 100000.000000ms)
2024-09-24T09:24:28.951915Z  INFO bevy diagnostic: frame_count:    1.000000   (avg 0.500000)
2024-09-24T09:24:29.049511Z  INFO bevy diagnostic: fps        :    0.010000   (avg 0.010000)
2024-09-24T09:24:29.049543Z  INFO bevy diagnostic: frame_time : 100000.000000ms (avg 100000.000000ms)
2024-09-24T09:24:29.049552Z  INFO bevy diagnostic: frame_count:    2.000000   (avg 1.000000)
2024-09-24T09:24:29.062974Z  INFO bevy diagnostic: fps        :    0.010000   (avg 0.010000)
```

## Additional information

It should be the misuse about the real time. For some meta informations, `Res<Time>` should not be used. Maybe `bevy` should provide a `Time<Wall>` that just wraps `std::time::Instant::now()` for those users who needs the wall time, or just let those user call `std::time::Instant::now()`.

**Comment by BenjaminBrienen** [comment] 2024-09-26 06:03
Maybe related: #14152

**Comment by Neutron3529** [comment] 2024-09-26 06:46
> Maybe related: #14152

That is not related.

The reason this bug occurs is that, `Time<Real>` affected by `bevy::time::TimeUpdateStrategy::ManualDuration(std::time::Duration::from_secs(100));`

which is definately not what the doc said (Time<Real> should ve wall time)

Unfortunately, since there are guides that tell user modify Time<Real> for some multiplayer game, I have no idea whether Time<Real> should be modified.

Maybe we should correct the mechanism, makes Time<Real> unchangable, and TimeUpdateSchedule affects Time<Virtual>

**Comment by maniwani** [comment] 2024-09-26 15:44
What are we calling the "bug" here?

This is the intended behavior. The `TimeUpdateStrategy` was introduced by https://github.com/bevyengine/bevy/pull/6159 specifically to help people write test cases that want to mock wall time.

You can see in the code that it works by directly controlling `Time<Real>`.

https://github.com/bevyengine/bevy/blob/5fcbdc137a6e3e636aef3e5fd9190b0bc6ec2887/crates/bevy_time/src/lib.rs#L147-L151

Making `Time<Real>` non-configurable would be regressive. This seems like a documentation issue.

**Comment by BenjaminBrienen** [comment] 2024-09-26 16:55
Closing because this is working as intended and following this up with the new issue for the idea to make it less confusing.

**Closed by BenjaminBrienen** 2024-09-26 16:55 UTC
Labels: C-Bug, S-User-Error, A-Time

**Comment by Neutron3529** [comment] 2024-09-27 04:46
> Closing because this is working as intended and following this up with the new issue for the idea to make it less confusing.

Please remove the `S-User-Error` flag, since it is something related to documents.

Firstly, it is not only test cases that allow using `TimeUpdateStrategy`, which is documented in its doc:

> For most cases, [TimeUpdateStrategy::Automatic](https://docs.rs/bevy/latest/bevy/time/enum.TimeUpdateStrategy.html#variant.Automatic) is fine. When writing tests, ***dealing with networking or similar***, you may prefer to set the next [Time](https://docs.rs/bevy/latest/bevy/time/struct.Time.html) value manually.

Secondly, `Time<Real>` is documented to be the wall clock, but it is not.

And the most important, the problem is not solved with using both a modified `TimeUpdateStrategy` and FPS plugins.
