### ISSUE TITLE
Tracing's overhead may be too high for profiling CPU-bound operations

### ISSUE THREAD

**Issue by james7132** [bevyengine/bevy#4892] opened 2022-06-01 20:33 UTC
## Bevy version
0.7 and current head (cc4062ec4359b80a8c88a63aa45f17c681bb0e71)

## What you did
Attempted to profile `many_foxes` with `trace_tracy` enabled. Commented out spans for `system_overhead` and `system_commands`.

## What went wrong
Profiled measurements for each stage show significant changes. Here's a comparison of the `Update` stage measurements:

![image](https://user-images.githubusercontent.com/3137680/171494201-41ab5859-e86d-4ff9-8f1b-324065d22bed.png)

There's only 10-20 systems in that stage, and the overhead scales with the number of systems. This overhead should be much lower, and it makes it difficult to make perf decisions on a macro level.

**Comment by hymm** [comment] 2022-06-02 04:02
I should mention that a big portion of the difference between the two histograms above is due to the applying system commands. This is mostly just a constant offset since most systems don't apply commands every frame. The issue is that it shows up in the trace as a bunch of spans.

![image](https://user-images.githubusercontent.com/2180432/171549892-cc7a71e5-6dce-4787-a1b1-74ff1ed382bb.png)

Without tracing enable applying these commands is probably less than a microsecond, but shows up in the above image as 90us.

I'm not sure how much of an issue this is as it shows up a constant offset for most frames, but we should probably supply a way of disabling these spans if people want to see something closer to the real framerate.

**Comment by davidbarsky** [comment] 2022-06-07 16:44
Notes from Discord: the `span` macro does not allocate, which means that the overhead isn't `tracing` or `tracing-core`, but rather, `tracing-subscriber`. `tracing-subscriber`'s `Registry` and `Extensions` (which are used by `tracing-tracy`) to store profiling have room to improve performance, but a decent amount of the overhead you're experiencing comes from `tracing-subscriber::Registry` trying to be modular and flexible in accepting data for arbitrary user-defined Layers.

For a profiling use-case, it might be worthwhile to implement your own subscriber (replacing the `Registry` but using the underlying [`sharded-slab`](https://docs.rs/sharded-slab/latest/sharded_slab/) data structure without boxing values into extensions.)

@hawkw has some ideas to improve `tracing_subscriber::Registry`, where instead of using a `HashMap` for extensions, Layer types would be required to pre-declare extension types they'd be storing in the `Registry` and use arrays to store extensions. However, this will be a tracing-subscriber 0.4 change, which is not currently scheduled.

**Comment by alice-i-cecile** [comment] 2023-09-13 19:10
I'm calling this fixed by #9390. If there's still ongoing problems, please reopen this issue :)

**Closed by alice-i-cecile** 2023-09-13 19:10 UTC
Labels: C-Bug, A-Diagnostics
