### ISSUE TITLE
Duplicate image asset loader warning is emitted

### ISSUE THREAD

**Issue by rparrett** [bevyengine/bevy#15785] opened 2024-10-09 13:50 UTC
## Bevy version

main, since #15586 

## Relevant system information

```
SystemInfo { os: "MacOS 14.5 ", kernel: "23.5.0", cpu: "Apple M1 Max", core_count: "10", memory: "64.0 GiB" }
AdapterInfo { name: "Apple M1 Max", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
```

## What you did

`cargo run --example sprite`

## What went wrong

```
2024-10-09T13:41:12.404995Z  WARN bevy_asset::server::loaders: Duplicate AssetLoader preregistered for Asset type `bevy_image::image::Image` with extensions `["hdr"]`. Loader must be specified in a .meta file in order to load assets of this type with these extensions.
```

**Comment by alice-i-cecile** [comment] 2024-10-09 14:02
Duplicate of #15730.

**Closed as not planned by alice-i-cecile** 2024-10-09 14:02 UTC
Labels: C-Bug, S-Needs-Triage
