### ISSUE TITLE
Add UiNode size (width/height) to UI Pipeline and UI Material Pipeline

### ISSUE THREAD

**Issue by viridia** [bevyengine/bevy#11706] opened 2024-02-04 23:19 UTC
## What problem does this solve or what need does it fill?

The rounded corners PR [#8973](https://github.com/bevyengine/bevy/pull/8973/files#diff-73d5bbb98e94d0fa67a1c6cd29fbbe523ecde5aec00794f9c45b23591e2eb19e) adds a size attribute to the data that is passed to the shader, which contains the width and height of the UI node. This should be added to the custom `UiMaterial` pipeline as well: may custom shaders will want to be able to render pixel-accurate shapes, and this is hard to do without knowing how u/v values correspond with actual pixels.

Similarly, one might want to write a shader that maintains a proper aspect ratio of the rendered content, even when the ui node is resized. This is fairly easy to do if you know the width and height of the UI node.

Without this, writing a custom UI shader that understands aspect ratios or pixel sizes is very difficult, as it requires re-implementing the entire render pipeline for UI nodes.

@ickshonpe @alice-i-cecile 

## What solution would you like?

Simply to add an additional attribute `[f32;2]` which is passed to the shader.

## What alternative(s) have you considered?

You could re-implement the entire UI material pipeline, but this is a lot of work.

**Comment by rparrett** [comment] 2024-02-05 00:27
This seems like a duplicate of #11392

**Closed** 2024-02-05 00:55 UTC
Labels: S-Duplicate, C-Enhancement, A-UI
