### ISSUE TITLE
major graphics problems when using DirectX12 as a backend

### ISSUE THREAD

**Issue by adsick** [bevyengine/bevy#1941] opened 2021-04-16 18:57 UTC
some of the problems probably are already known, but the point of this issue is to make you aware that DirectX12 backend is basically broken now so if you encounter problems with it you should try switching to Vulkan backend. 
this issue is actually seems on wgpu/gfx side but untill it is not fixed by their developers team, Bevy devs should know that this problems exists.

## Bevy version

0.5 (from Git repo)

## Operating system & version

Windows 10

## Hardware:

AMD Ryzen 3500U with Vega 8 graphics

this appears on DirectX12 backend only, switching to Vulkan or older DirectX11 solves both the artifacts and the leak.

## What you did

Run different 3D examples

## What you expected to happen

Fancy 3D graphics rendered correctly

## What actually happened

Image is flooded with red color and has many artifacts

## Additional information
running vanilla  load_gltf example with dx12 backend looks like the following: (also note how memory usage growth and then falls when I close the application)
![image](https://user-images.githubusercontent.com/24528839/115070649-e6248680-9efd-11eb-8c84-c7a4ebe19876.png)
![image](https://user-images.githubusercontent.com/24528839/115070703-f6d4fc80-9efd-11eb-9dd0-0aede3026897.png)
when resizing the window, ugly glitches can be observed:
![image](https://user-images.githubusercontent.com/24528839/115070964-4f0bfe80-9efe-11eb-91cb-e66afbcbd94b.png)

proof that everything works fine with Vulkan (memory is also ok) btw noticed, that in this example dx11 (which is also ok) uses like twice less RAM than the Vulkan version
![image](https://user-images.githubusercontent.com/24528839/115071044-68ad4600-9efe-11eb-9287-9d8daafb26d1.png)

**Comment by mockersf** [comment] 2021-04-16 20:48
> this issue is actually seems on wgpu/gfx side

Can you reproduce those graphic glitches running examples from wgpu? They may have already fixed it. Do you know if there's an issue?

For memory usage, this is (as you know) #1804

**Comment by adsick** [comment] 2021-04-16 22:17
Ok, I will try to run some wgpu examples with different backends tomorrow. That requires a bit o time.

**Comment by adsick** [comment] 2021-04-17 16:20
so I've nearly burned my notebook during wgpu compilation, set it to Dx12 backend and it seems fine. I tested both debug and release builds and those problems were not encountered.
![image](https://user-images.githubusercontent.com/24528839/115119603-ed0cd100-9fb1-11eb-8625-665f02956cf6.png)

**Comment by mockersf** [comment] 2021-04-18 15:30
Could you check again after a `cargo update`? There has been a dependency related to dx12 that has been updated

**Comment by adsick** [comment] 2021-04-18 15:42
I updated the deps, saw it actually updated that dx12 related gfx thing, but unfortunately the artifacts reamain the same as they were before (except memory now does not growth up to infinity)

**Comment by kvark** [comment] 2021-06-15 13:58
If the issue is with wgpu/gfx, and it's not filed there, then waiting for it to be fixed is not the most efficient.
Here is what would help us to investigate:
  1. file this on gfx-rs repo
  2. record an API trace - https://github.com/gfx-rs/wgpu/wiki/Debugging-wgpu-Applications#tracing-infrastructure . I don't know how Bevy exposes this.
  3. run the app from within Visual Studio and copy out the Output window, which would show the DX runtime warnings

**Comment by kvark** [comment] 2021-06-15 17:14
Since wgpu's goal is to be fully safe and maximum portable, it seems like it would still be our problem, even if you are doing something unexpected.

**Comment by cart** [comment] 2021-06-15 19:22
> Since wgpu's goal is to be fully safe and maximum portable, it seems like it would still be our problem, even if you are doing something unexpected.

I appreciate this approach :smile:

**Comment by adsick** [comment] 2021-06-15 19:27
Is it possible to just switch default bevy wgpu backend to vulkan (or dx11)?

In situation when you want the game to work on end user machine the last thing you want is to tell him words "set the BEVY_WGPU_BACKEND env variable to vulkan"

Honestly I'm a noob, but I don't find thase env variable good/flexible, esp in gamejab scenario

**Comment by cart** [comment] 2021-06-15 19:59
I think ultimately it is wgpu's job to pick the best / most compatible backend. Currently it sounds like it favors DX12, but that results in inconsistent behavior. If DX12 really should be the "preferred" backend on windows, then this is just a bug that needs to be fixed in wgpu's DX12 backend. If the inconsistency cannot be fixed (or Vulkan is the better backend to prefer), then they should change that on their end.

We _could_ force vulkan on windows, but I think the wgpu team is better equipped / positioned to make that call on our behalf.

**Comment by kvark** [comment] 2021-06-16 01:20
Vulkan has always been our first candidate. If Bevy doesn't forbid it, we'd try it first, and only proceed to DX12 if the adapters it exposes fit better. See https://github.com/gfx-rs/wgpu/issues/1416 for some more details.

Here is an example where you can get DX12 today, but maybe don't expect it:
  - the machine has an Intel Haswell iGPU and an NVidia GPU
  - user requests a `LowPower` adapter, with a mask that permits all backends
  - we query Vulkan adapters and only get NVidia GPU one, since Haswell doesn't support Vulkan on Windows
  - we query DX12 adapters and get separate adapters for Intel and Nvidia
  - DX12 Intel iGPU is picked, since it's the only `LowPower` candidate

**Comment by adsick** [comment] 2021-06-16 22:52
Can we just disable dx12 for now as it does not work correctly?

**Comment by mockersf** [comment] 2021-06-16 23:05
Could someone with DX12 run (and exit as soon as the model is displayed and red)
```
cargo run --example load_gltf  --features wgpu_trace
```

This will create a `wgpu_trace` folder. Then please file an issue in https://github.com/gfx-rs/wgpu with this folder and any log from Bevy

**Comment by adsick** [comment] 2021-07-13 18:19
sorry for being a slowpoke, the problem is still present. I did the run with wgpu_trace and filed an issue at wgpu.

**Comment by mockersf** [comment] 2021-07-13 18:26
In the meantime, Bevy is rewriting its rendering stack and wgpu is rewriting its dx12 stack... There may be hope!

**Comment by inodentry** [comment] 2024-02-05 13:00
This issue is very old and probably stale. Bevy has had a renderer rewrite since this issue was created, and wgpu has had several major releases. The DX12 backend recently became the default on Windows. Closing this issue.

Feel free to reopen if it is still relevant / the issues are still present.

**Closed by inodentry** 2024-02-05 13:00 UTC
Labels: C-Bug, A-Rendering, C-Dependencies
