### ISSUE TITLE
[Bug] Example Font_Atlas_Debug crashes after a while

### ISSUE THREAD

**Issue by Telzhaak** [bevyengine/bevy#342] opened 2020-08-25 07:00 UTC
As the title says, after a printing some characters characters, the Application exits ungracefully

This happens in both debug and release builds

I have not debugged it, but this piece of code looks suspicious (font_atlas_debug.rs, line 61+):
```rust
if state.timer.finished {
    text.value = format!("{}", rand::random::<u8>() as char);
    state.timer.reset();
}
```
As it may try to print unprintables like `00000000`.

System:
------
Windows 10 Home 64-bit

Backtrace:
-----

```
cargo run --example font_atlas_debug
    Finished dev [unoptimized + debuginfo] target(s) in 0.39s
     Running `target\debug\examples\font_atlas_debug.exe`
thread '<unnamed>' panicked at 'ran out of space in font atlas', crates\bevy_text\src\font_atlas.rs:50:13
stack backtrace:
   0: std::panicking::begin_panic<str*>
             at C:\Users\Daniel\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panicking.rs:497
   1: bevy_text::font_atlas::FontAtlas::add_char
             at .\crates\bevy_text\src\font_atlas.rs:50
   2: bevy_text::font_atlas_set::FontAtlasSet::add_glyphs_to_atlas
             at .\crates\bevy_text\src\font_atlas_set.rs:73
   3: bevy_ui::widget::text::text_system
             at .\crates\bevy_ui\src\widget\text.rs:40
   4: core::ops::function::Fn::call<fn(bevy_ecs::resource::resource_query::ResMut<bevy_asset::assets::Assets<bevy_render::texture::texture::Texture>>, bevy_ecs::resource::resource_query::Res<bevy_asset::assets::Assets<bevy_text::font::Font>>, bevy_ecs::resource
             at C:\Users\Daniel\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:72
   5: core::ops::function::impls::{{impl}}::call_mut<tuple<bevy_ecs::resource::resource_query::ResMut<bevy_asset::assets::Assets<bevy_render::texture::texture::Texture>>, bevy_ecs::resource::resource_query::Res<bevy_asset::assets::Assets<bevy_text::font::Font>>
             at C:\Users\Daniel\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:253
   6: bevy_ecs::system::into_system::{{impl}}::system::{{closure}}<fn(bevy_ecs::resource::resource_query::ResMut<bevy_asset::assets::Assets<bevy_render::texture::texture::Texture>>, bevy_ecs::resource::resource_query::Res<bevy_asset::assets::Assets<bevy_text::f
             at .\crates\bevy_ecs\src\system\into_system.rs:186
   7: bevy_ecs::system::into_system::{{impl}}::run<bevy_ecs::system::into_system::QuerySystemState,closure-0,closure-1,closure-2,closure-3>
             at .\crates\bevy_ecs\src\system\into_system.rs:61
   8: bevy_ecs::schedule::parallel_executor::{{impl}}::run_ready_systems::{{closure}}
             at .\crates\bevy_ecs\src\schedule\parallel_executor.rs:313
   9: rayon_core::scope::{{impl}}::spawn_fifo::{{closure}}::{{closure}}<closure-0>
             at C:\Users\Daniel\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-core-1.7.1\src\scope\mod.rs:496
  10: std::panic::{{impl}}::call_once<tuple<>,closure-0>
             at C:\Users\Daniel\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panic.rs:308
  11: std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,tuple<>>
             at C:\Users\Daniel\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panicking.rs:373
  12: std::panicking::try::do_catch<std::panic::AssertUnwindSafe<closure-0>,tuple<>>
  13: std::panicking::try<tuple<>,std::panic::AssertUnwindSafe<closure-0>>
             at C:\Users\Daniel\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panicking.rs:337
  14: std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,tuple<>>
             at C:\Users\Daniel\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panic.rs:379
  15: rayon_core::unwind::halt_unwinding<closure-0,tuple<>>
             at C:\Users\Daniel\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-core-1.7.1\src\unwind.rs:17
  16: rayon_core::scope::ScopeBase::execute_job_closure<closure-0,tuple<>>
             at C:\Users\Daniel\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-core-1.7.1\src\scope\mod.rs:562
  17: rayon_core::scope::ScopeBase::execute_job<closure-0>
             at C:\Users\Daniel\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-core-1.7.1\src\scope\mod.rs:550
  18: rayon_core::scope::{{impl}}::spawn_fifo::{{closure}}<closure-0>
             at C:\Users\Daniel\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-core-1.7.1\src\scope\mod.rs:496
  19: rayon_core::job::{{impl}}::execute<closure-0>
             at C:\Users\Daniel\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-core-1.7.1\src\job.rs:167
  20: rayon_core::job::JobRef::execute
             at C:\Users\Daniel\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-core-1.7.1\src\job.rs:59
  21: rayon_core::job::{{impl}}::execute
             at C:\Users\Daniel\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-core-1.7.1\src\job.rs:209
  22: rayon_core::job::JobRef::execute
             at C:\Users\Daniel\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-core-1.7.1\src\job.rs:59
  23: rayon_core::registry::WorkerThread::execute
             at C:\Users\Daniel\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-core-1.7.1\src\registry.rs:685
  24: rayon_core::registry::WorkerThread::wait_until_cold<rayon_core::latch::CountLatch>
             at C:\Users\Daniel\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-core-1.7.1\src\registry.rs:669
  25: rayon_core::registry::WorkerThread::wait_until<rayon_core::latch::CountLatch>
             at C:\Users\Daniel\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-core-1.7.1\src\registry.rs:643
  26: rayon_core::registry::main_loop
             at C:\Users\Daniel\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-core-1.7.1\src\registry.rs:763
  27: rayon_core::registry::ThreadBuilder::run
             at C:\Users\Daniel\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-core-1.7.1\src\registry.rs:56
  28: rayon_core::registry::{{impl}}::spawn::{{closure}}
             at C:\Users\Daniel\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-core-1.7.1\src\registry.rs:101
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\examples\font_atlas_debug.exe` (exit code: 101)
```

**Comment by karroffel** [comment] 2020-08-25 07:30
duplicate of #343 

Seems to have the same backtrace as well.

**Closed** 2020-08-25 07:31 UTC
Labels: duplicate
