### ISSUE TITLE
KeyCode: Numpad key triggers regular key

### ISSUE THREAD

**Issue by ufReitter** [bevyengine/bevy#1666] opened 2021-03-16 13:41 UTC
## Bevy version

284889c64b2a4a4f67018e42a14062392edbd0aa
0.4.0 had the same result

## Operating system & version

macOS 11.2.2

## What you did

         if keyboard_input.just_pressed(KeyCode::Key5) {
             thruster.thrust = thruster.thrust_max * 1.;
         }

        if keyboard_input.just_pressed(KeyCode::Numpad5) {
            submarine.bow_thruster = 0.;
        }

## What you expected to happen

When pressing "5" on Number Pad the second If-Statement is triggered

## What actually happened

When pressing "5" on Number Pad only the first If-Statement (Key5) is triggered

**Comment by bjorn3** [comment] 2021-03-16 13:56
Bevy translates straight from winit keyboard events. Winit does support Numpad* events on macOS: https://github.com/rust-windowing/winit/blob/b9f3d333e41464457f6e42640793bf88b9563727/src/platform_impl/macos/event.rs#L176-L186 Does it change when you turn numlock on or off?

**Comment by nehalem501** [comment] 2021-03-17 08:46
> Does it change when you turn numlock on or off?

There is no numlock key in macOS if using an Apple keyboard (it is always "on").

**Comment by bjorn3** [comment] 2021-03-17 09:24
Then I think there is no way to distinguish numpad numbers and non-numpad numbers. Can other programs distinguish between them? For example in Blender the numpad numbers 2, 4, 6 and 8 should change between different view orientations while the non-numpad numbers should be interpreted as regular numbers.

**Comment by ufreitter** [comment] 2021-03-17 09:44
Did not try Blender. But the system distinguishes between numpad and non numpad. When I open the mac virtual keyboard only the regular number keys highlight when pressed and not when pressing the numpad ones. In a text editor the numpad input appears fine.

**Comment by bjorn3** [comment] 2021-03-17 09:59
Could you open an issue on winit? https://github.com/rust-windowing/winit/issues/

**Comment by mockersf** [comment] 2021-03-17 10:05
The scan code is correct, the issue is on the key code

To account for different keyboard layout, winit is attempting to translate the keyboard event to a keycode using the actual character typed, so it can't differentiate between `Numpad5` and `Key5`... 

It's done [here](https://github.com/rust-windowing/winit/blob/3a077ff21125e9b130ab18596e9a363b5d9dcb86/src/platform_impl/macos/view.rs#L603) gif you want to open the discussion on winit side

**Comment by maroider** [comment] 2021-03-22 09:03
There's currently ongoing work to improve the keyboard input API in Winit, which should address the fundamental issue encountered here.

See:
- rust-windowing/winit#1806
- rust-windowing/winit#753
- rust-windowing/winit#1788
- rust-windowing/winit#1890
- rust-windowing/winit#1888

**Comment by mockersf** [comment] 2023-06-11 19:34
should be fixed by https://github.com/bevyengine/bevy/pull/8745

**Comment by alice-i-cecile** [comment] 2024-01-10 14:02
Resolved upstream.

**Closed by alice-i-cecile** 2024-01-10 14:02 UTC
Labels: C-Bug, A-Input, O-MacOS
