### ISSUE TITLE
Performance Lag when focusing and unfocusing in WASM Firefox

### ISSUE THREAD

**Issue by newclarityex** [bevyengine/bevy#12471] opened 2024-03-14 05:54 UTC
## Bevy version

0.13

## \[Optional\] Relevant system information

If you cannot get Bevy to build or run on your machine, please include:
- Windows 10
- Firefox

## What you did
I tested a simple bevy wasm build in Firefox and Chrome. 

## What went wrong
In Chrome everything ran smoothly.
In Firefox, it initially ran smoothly but became extremely laggy after unfocusing/refocusing the game.

**Comment by james7132** [comment] 2024-03-14 06:03
This could be a duplicate of #12126.

**Closed** 2024-03-14 08:32 UTC
Labels: C-Bug, S-Duplicate, A-Windowing, C-Performance, O-Web
