### ISSUE TITLE
Broken rendering wireframes on windows / DX12

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#10019] opened 2023-10-04 14:55 UTC
it seems this PR broke rendering wireframes on windows / DX12
![4a70c28683d006612a308b440640b77d41660816281512fad182519013d51071](https://github.com/bevyengine/bevy/assets/8672791/2f502e3c-eb80-4365-bd60-ce1c56f72e33)

_Originally posted by @mockersf in https://github.com/bevyengine/bevy/issues/7328#issuecomment-1746274687_

**Comment by alice-i-cecile** [comment] 2023-10-04 14:56
I think just reverting for now is likely the safest choice, but if y'all can find another fix I'm happy to take a look.

**Comment by IceSentry** [comment] 2023-10-04 15:12
I don't think this is a new bug, the PR didn't touch any rendering code.

I just tested it with bevy before the PR and wireframes were already broken with DX12

**Comment by mockersf** [comment] 2023-10-04 16:17
I can't test locally DX12, but it's running as part of https://vleue.com/bevy-example-tests/index.html
Wireframes on Windows/DX12 were working before the last two commits on main

**Comment by IceSentry** [comment] 2023-10-04 16:26
So, I'm not entirely sure what the issue is yet, but I know why this tool didn't show you the error. It only shows up on the plane mesh but before that PR the plane was disabled. I needed to enable the global wireframe to show the issue.

**Comment by IceSentry** [comment] 2023-10-04 16:27
I'm still digging, but 0.11.3 works correctly but 20ed3e0e765405ee334a44ce3c49c72bd29ab753 doesn't

**Comment by IceSentry** [comment] 2023-10-04 16:38
Alright, found the commit where it started ae6bc08a58a076ea628311334516855e7f29c86a it's https://github.com/bevyengine/bevy/pull/9734

@mockersf 👀

**Comment by IceSentry** [comment] 2023-10-04 16:40
To be clear, this only happens with the DX12 backend, Vulkan backend is fine.

Technically it's also broken on the webgpu backend, but line drawing isn't supported on that backend so the fact that it renders anything is a wgpu bug that will be fixed.

**Comment by mockersf** [comment] 2023-10-04 16:56
> Alright, found the commit where it started [ae6bc08](https://github.com/bevyengine/bevy/commit/ae6bc08a58a076ea628311334516855e7f29c86a) it's #9734
> 
> @mockersf 👀

nice, thanks for digging!

**Closed** 2023-10-04 18:50 UTC
Labels: C-Bug, A-Rendering, C-Regression

**Comment by superdump** [comment] 2023-10-05 08:36
I was going to say - it looks like it's loading the wrong transforms from instance data, and I remembered that there was an instance index workaround for DX12 misbehaviour.
