### ISSUE TITLE
Wayland windows' colors are too dark

### ISSUE THREAD

**Issue by johanhelsing** [bevyengine/bevy#7318] opened 2023-01-21 16:55 UTC
![Screenshot_20230121_175039](https://user-images.githubusercontent.com/2620557/213877729-a3ca59aa-2d34-4383-85af-2aaa37a88ba8.png)

[breakout-wayland.log](https://github.com/bevyengine/bevy/files/10472596/breakout-wayland.log)
![Screenshot_20230121_175325](https://user-images.githubusercontent.com/2620557/213877811-a9853df1-5d6b-4432-8214-c5c315f23974.png)

- kwin
- bevy: cb4e8c83
- Nvidia GTX 970

**Comment by JMS55** [comment] 2023-01-21 18:22
Bloom has known issues with transparency, which will be fixed by https://github.com/bevyengine/bevy/pull/6677. 

The lightness shift is interesting though.

**Comment by johanhelsing** [comment] 2023-01-21 22:40
Alright, removing bloom from the title to keep the issue focused.

For what it's worth, I tested on gnome as well, and it's behaving the same, so likely not a compositor bug.

![image](https://user-images.githubusercontent.com/2620557/213889721-ef2d951b-2faa-40ed-ae46-42abc0c72f5c.png)

wayland on the left, x11 on the right

The colors on X11 are consistent with what I see on Windows and wasm, (just confirming it's wayland that is off, and not x11)

**Comment by johanhelsing** [comment] 2023-01-21 23:30
From the wayland logs, it looks like we're creating the right kind of surface:
```
[1036841.262]  -> wl_surface@18.frame(new id wl_callback@43)
[1036841.622]  -> zwp_linux_dmabuf_v1@45.create_params(new id zwp_linux_buffer_params_v1@51)
[1036841.633]  -> zwp_linux_buffer_params_v1@51.add(fd 51, 0, 0, 5120, 50331648, 5234708)
[1036841.639]  -> zwp_linux_buffer_params_v1@51.create_immed(new id wl_buffer@54, 1280, 720, 875713089, 0)
[1036841.644]  -> zwp_linux_buffer_params_v1@51.destroy()
```
We're creating a surface with the 875713089 format, which is AR24 in fourcc (ARGB8888)

I'm not really sure how to dig further. I took some `RUST_LOG=debug` logs from running the breakout example as well. Let me know if there's any other way I can help.

[breakout-debug-wayland.log](https://github.com/bevyengine/bevy/files/10473337/breakout-debug-wayland.log)

**Comment by Elabajaba** [comment] 2023-01-27 06:19
So we should be able to fix this once we land [wgpu 0.15](https://github.com/bevyengine/bevy/pull/7356), but it requires using `texture_views` on non-srgb surfaces (and we should still default to srgb surfaces if they're available).

The problem is I wasn't able to get them working without a ton of vulkan validation errors, so I opted out of it for that PR.

**Comment by JMS55** [comment] 2023-02-11 05:42
@Elabajaba the recently released wgpu 0.15.1 should fix this. Do you mind taking another stab at it?

**Comment by VitalyAnkh** [comment] 2023-02-12 16:21
@JMS55 I found the color is still too dark on Wayland with the lasted commit (eaac730617103b61fd5ede9dca463243f2d7900e) which contains wgpu 0.15.1 update:
On Wayland:
```
RUST_BACKTRACE=1 RUST_LOG=info WGPU_BACKEND=vulkan cargo run --features wayland --example fog
```
![image](https://user-images.githubusercontent.com/24508452/218323032-551d65f0-13e1-473c-af02-15816b16aab7.png)

and on X11:
```
RUST_BACKTRACE=1 RUST_LOG=info WGPU_BACKEND=vulkan cargo run --example fog
```
![image](https://user-images.githubusercontent.com/24508452/218323118-45a7dea1-7cea-4739-9bcb-10f88d73431e.png)

**Comment by Hellzbellz123** [comment] 2023-02-18 22:06
bug exists on nvidia-dkms it seems. testing nvidia-open-dkms to see if there is a difference.
nvidia-dkms/525.89.02 with an RTX 3070 lhr
running cachyos linux kernel 6.1.12-1
running said apps with wayland and using swrast/lavapipe gets me the correct colors so that leads me to believe its a driver issue, while testing this i also discovered that the bloom example has a bug where the window is transparent when intensity is postive
xorg:
![x11](https://user-images.githubusercontent.com/31550512/219901057-1025fb86-2bf9-4f60-ad4b-20cf76a22ed7.png)
wayland: 
![wayland](https://user-images.githubusercontent.com/31550512/219901079-f0d33cea-51b9-471f-908d-d43f062b8ce5.png)

**Comment by VitalyAnkh** [comment] 2023-02-19 02:42
So this problem only happens on NVIDIA's GPU?  Are there any similar issues on Intel or AMD? 

I'm also using nvidia-dkms-open and experiencing this problem.

**Comment by Elabajaba** [comment] 2023-02-19 03:58
> So this problem only happens on NVIDIA's GPU?  Are there any similar issues on Intel or AMD? 
> 
> I'm also using nvidia-dkms-open and experiencing this problem. 

Afaik Nvidia's Linux driver kinda sucks and doesn't support sRGB surface formats. 

I'll try and get a pr up tomorrow to use an srgb texture view when the surface format isn't srgb now that it was fixed on the wgpu side.

**Closed** 2023-05-04 22:32 UTC
Labels: C-Bug, A-Rendering, O-Linux

**Comment by martinkozle** [comment] 2023-05-05 00:55
Surprise fix 😲
