### ISSUE TITLE
UI nodes don't resize when toggling fullscreen

### ISSUE THREAD

**Issue by benfrankel** [bevyengine/bevy#14277] opened 2024-07-11 08:03 UTC
## Bevy version

0.14.0

## Relevant system information

Linux with i3wm (tiling window manager).

```
AdapterInfo { name: "AMD Radeon RX 570 Series (RADV POLARIS10)", vendor: 4098, device: 26591, device_type: DiscreteGpu, driver: "radv", driver_info: "Mesa 24.0.6-arch1.2", backend: Vulkan }
```

## What you did

Toggle fullscreen while looking at my title screen UI.

## What went wrong

This is how my UI normally looks:

![2024-07-11_1720684551_1215x728](https://github.com/bevyengine/bevy/assets/12173779/7c0bd396-ca01-42c3-b68a-a02677d1025f)

This is how my UI _sometimes_ looks after toggling from fullscreen to windowed:

![2024-07-11_1720684545_1215x728](https://github.com/bevyengine/bevy/assets/12173779/b6398e65-a815-4e87-ab1e-b9ea38a39402)

I checked, and the buttons in this case are _the same size_ as they were while in fullscreen.

This issue can happen in reverse as well, with the fullscreen buttons being as small as they were while windowed.

Resizing the window slightly after the bug occurs will snap the buttons back to the correct size.

**Comment by ickshonpe** [comment] 2024-07-11 10:43
It seems like the single UI layout update after the window resize isn't enough. You could try a system something like this to force  it to reupdate again for few frames after the window resizes:

```rust
fn force_ui_reupdate_on_window_resized(
    mut counter: Local<u8>,
    mut window_resized_events: EventReader<WindowResized>,
    mut ui_scale: ResMut<UiScale>,
    mut ui_node_query: Query<(&mut Style, Option<&mut Text>)>,
) {
    if 0 < *counter {
        ui_scale.set_changed();
        for (mut style, maybe_text) in ui_node_query.iter_mut() {
            style.set_changed();
            if let Some(mut text) = maybe_text {
                text.set_changed();
            }
        }
    }   

    *counter = counter.saturating_sub(1);
    if !window_resized_events.is_empty() {
        window_resized_events.clear();
        *counter = 2;
    }
}
```

I just typed this out quickly, it's not tested but I think it should work. The query might be overkill, maybe it'll correct itself just with set ing `UiScale` to changed the frame directly after the window resize.

**Comment by alice-i-cecile** [comment] 2024-07-11 13:01
Duplicate of #14255.

**Comment by benfrankel** [comment] 2024-07-29 20:47
I'm seeing this build in the itch.io release of my jam game as well. This is much more severe than the related bug, because the size difference between windowed and fullscreen makes the UI completely bugged instead of "slightly off / delayed".

**Comment by benfrankel** [comment] 2024-08-04 00:59
This appears to be a system ordering bug. I ran the same app 25 times without recompiling and saw the bug 9/25 times. Whenever the bug was present, it happened 100% consistently on every fullscreen toggle.

**Comment by benfrankel** [comment] 2024-08-04 02:00
I suspect that this is a system ordering bug between `CameraUpdateSystem` and `UiSystem::Layout`, which both run in `PostUpdate` with no ordering specified between them. The former set contains a system that updates the `Camera`'s viewport size, while the latter has a system that reads the `Camera`'s viewport size if the window has been resized.

**Comment by benfrankel** [comment] 2024-08-04 05:48
Well. I wasn't able to reproduce the bug in a modified bevy example, _but_ I tried explicitly ordering `CameraUpdateSystem` _before_ `UiSystem::Layout` and it triggered the exact same behavior.

**Comment by benfrankel** [comment] 2024-08-04 06:07
Opened PR :)

**Closed** 2024-08-04 13:49 UTC
Labels: C-Bug, A-Windowing, A-UI
