### ISSUE TITLE
Entity labeling

### ISSUE THREAD

**Issue by Itsnotdone** [bevyengine/bevy#11897] opened 2024-02-16 09:49 UTC
## What problem does this solve or what need does it fill?

Easier iterating over entities, you dont need to create multiple queries to distinguish entities. Currently you need to create two queries to get (for example) Enemy and Player, also it may be useful for future editor

## What solution would you like?

Something like:
```
commands.spawn((transform, health).label("Player"));
commands.spawn((transform, health).label("Enemy"));

fn my_system(query: Query<(&Transform, &Health)>){
    let (e_transform, e_health) = query.label("Enemy").unwrap();
    let (p_transform, p_health) = query.label("Player").unwrap();
}
```

## What alternative(s) have you considered?

Storing the Entity ID and using query.get(entity)

**Comment by Adamkob12** [comment] 2024-02-16 09:54
I agree, I've been thinking about tagging / labeling entities lately and it makes sense.

**Comment by Itsnotdone** [comment] 2024-02-16 09:59
I was thinking about the actual implementation and it shouldn't be hard, I'll try to implement it today

**Comment by DasLixou** [comment] 2024-02-16 12:16
Seems like a duplicate of #6556 . I also made a crate for this which is linked to in this issue but it hasn't been updated since 0.10. if you want, you can fork or pr tho

**Comment by alice-i-cecile** [comment] 2024-02-16 13:29
Yeah, I think this is functionally a duplicate. Not opposed, but just want to collect discussion.

**Closed by alice-i-cecile** 2024-02-16 13:29 UTC
Labels: C-Enhancement, S-Needs-Triage

**Comment by Itsnotdone** [comment] 2024-02-16 14:03
> Can't you create a marker component and use [`With<T>`](https://docs.rs/bevy/latest/bevy/ecs/prelude/struct.With.html) to filter the query?
> 
> ```rust
> #[derive(Component)]
> struct Player;
> 
> #[derive(Component)]
> struct Enemy;
> 
> fn spawn_system(
>     mut commands: Commands,
> ) {
>     commands.spawn((transform, health, Player));
>     commands.spawn((transform, health, Enemy));
> }
> 
> fn my_system(
>     player: Query<(&Transform, &Health), With<Player>>,
>     enemy: Query<(&Transform, &Health), With<Enemy>>,
> ) {
>     let (p_transform, p_health) = player.single();
>     let (e_transform, e_health) = enemy.single();
> }
> ```
> 
> If you don't want to use marker components, you could make a [`WorldQuery`](https://docs.rs/bevy/latest/bevy/ecs/query/trait.WorldQuery.html) that filters by the [`Name`](https://docs.rs/bevy/latest/bevy/core/struct.Name.html) component, but that's fallible (`Name` components do not guarantee that they are unique)

yes, but you need to create 2 queries, this example is simple but what if you had more complicated case?

**Comment by DasLixou** [comment] 2024-02-16 14:07
@Itsnotdone when there only exists one "player" or "enemy" at the same time, you can use entity markers. When there are multiple you won't get around multiple queries. Also note that the queries mustn't overlap, so you must add `Without<Enemy/Player>` to the queries

**Comment by Itsnotdone** [comment] 2024-02-16 14:07
> Seems like a duplicate of #6556 . I also made a crate for this which is linked to in this issue but it hasn't been updated since 0.10. if you want, you can fork or pr tho

Not exactly, because in this proposal you need to add  every tag to query which you are requesting, thats horrible if you have more tags (or am i wrong?)

**Comment by DasLixou** [comment] 2024-02-16 14:09
> > Seems like a duplicate of #6556 . I also made a crate for this which is linked to in this issue but it hasn't been updated since 0.10. if you want, you can fork or pr tho
> 
> Not exactly, because in this proposal you need to add every tag to query which you are requesting, thats horrible if you have more tags (or am i wrong?)

yes that's because it initially was meant to provide some parallelism hints but that wasn't done.

**Comment by DasLixou** [comment] 2024-02-16 14:11
Never the less, as alice says you are welcome to contribute your ideas to the open issue.
So what I think you want is a way to label entities and query them without much stuff inside the system params.
The reason why my crate does that is because every marker is stored inside a resource and modifing marker A shouldn't stop bevy from parallelizing a system which modifies marker B.
One thing I don't understand is whether you only want to mark/label one entity or multiple with the same label
