### ISSUE TITLE
Get blank in example breakout

### ISSUE THREAD

**Issue by jayzhan211** [bevyengine/bevy#152] opened 2020-08-13 01:44 UTC
After running `cargo run --example breakout`

I get the following, what is missing ?

![](https://i.imgur.com/fcQk8hG.png)

os: win10
rustc: 1.45.2

**Comment by cart** [comment] 2020-08-13 03:42
Hmm thats definitely not what we expect to see. What GPU are you running?

Do the other examples work? Ex: does ```cargo run --example 3d_scene``` render a scene?

If the other examples work, can you try [cloning wgpu](https://github.com/gfx-rs/wgpu-rs) (the rendering library we depend on) and running:
```
cargo run --example cube
```

If you get a blank screen there, you might want to file an issue with them.

**Comment by accelsao** [comment] 2020-08-13 04:26
gpu: Intel(R) HD Graphics

btw what is the minimum system requirements?

**Comment by luk-lo** [comment] 2020-08-14 18:30
I have the same problem with an AMD Radeon HD 6900 on Windows 10. the `3d_scene`, `ui` and `button` examples also result in a window with blank content but the wgpu cube example works.

**Comment by insrcd** [comment] 2020-08-14 21:09
I had a similar problem on my laptop, w/ Intel UHD Graphics 630 and a Nvidia Quadro P1000. 

Using the Nvidia Control Panel and Manage 3D Settings and added the binary to the list. If I assign the the Integrated Intel it will render. However, switching to the Quadro would cause the window to look exactly like above. 

I can run the examples for cube and get a result (on the Quadro), but not the bevy ui or button examples. If any more information is required (or ways I can debug this further) I'd be happy to help out.

**Comment by cart** [comment] 2020-08-14 22:08
One more request: can you try the examples on our [wgpu_upgrade](https://github.com/bevyengine/bevy/tree/wgpu_upgrade) branch? Its possible this is an issue they fixed in the latest wgpu version.

**Comment by luk-lo** [comment] 2020-08-15 20:54
> 
> 
> One more request: can you try the examples on our [wgpu_upgrade](https://github.com/bevyengine/bevy/tree/wgpu_upgrade) branch? Its possible this is an issue they fixed in the latest wgpu version.

Same result, unfortunately

**Comment by insrcd** [comment] 2020-08-17 14:11
> 
> 
> One more request: can you try the examples on our [wgpu_upgrade](https://github.com/bevyengine/bevy/tree/wgpu_upgrade) branch? Its possible this is an issue they fixed in the latest wgpu version.

I tried the wgpu_upgrade branch and had the following results:

Quadro is working as expected, but now the Integrated (UHD) is rendering strangely. The 3d_scene example is blank, the little project I'm working on only renders one tile (but movement, camera panning, collisions, etc all seem to work).

Intel UHD
![image](https://user-images.githubusercontent.com/1045498/90405052-431b2480-e071-11ea-8753-5ff7dd71777c.png)

Quadro :
![image](https://user-images.githubusercontent.com/1045498/90405410-b1f87d80-e071-11ea-9ca0-f652146c1a4c.png)


Not sure if this helps or confuses the matter further ;).

**Comment by mbenoukaiss** [comment] 2020-08-19 17:50
So it seems to come from Intel HD Graphics GPUs because I'm getting the same problem on Debian 9 with an Intel(R) HD Graphics 620.
Here is the output of `vulkaninfo` if that can be of any help https://pastebin.com/JhaiwMAs

**Comment by jeremydavis519** [comment] 2020-08-20 01:06
I'm seeing a similar non-drawing behavior, but rotating the sprites didn't help. Also, for some reason, text is being shown correctly, even though nothing else is visible. I know wgpu works, and I'm currently trying to track down the issue in the Bevy source code. If I manage to find and fix it on my computer before someone else figures it out, I'll issue a pull request, and hopefully it'll fix the bug on your computers too.

By the way, I'm running Windows 10 with a GTX 570.

**Comment by mimoguz** [comment] 2020-08-20 05:45
I have a similiar issue on my notebook when using discrete graphics (Windows 10, NVidia GTX 1060 with latest drivers). Text rendering works, but sprites are not visible. Everything works fine with integrated graphics (Intel UHD 630).

**Comment by adambiltcliffe** [comment] 2020-08-28 19:33
Similar issue on Windows 10 Home 64 bit on a Radeon R7 M260. Flickering screen with `breakout` and `sprite`, blank screen with `3d_scene` and `text`, lavender screen with `clear_color`. The cube example from `wgpu-rs` renders correctly.

Switching to the `wgpu-upgrade` branch, `breakout` stops flickering (but still doesn't show anything) and `3d_scene` shows a single grey quad. The others are unaffected.

**Comment by Peohta** [comment] 2020-10-18 14:06
I have a similar problem with `3d_scene`, `sprite`, `text`. The screen flickers between white and black.
I have a ATI Radeon 3000 running on Windows 10 Pro 64 bit.

**Comment by alice-i-cecile** [comment] 2022-03-21 00:15
Closing due to the rendering rework: I don't think this reproduces anymore.

**Closed by alice-i-cecile** 2022-03-21 00:15 UTC
Labels: C-Bug, O-Windows, C-Dependencies
