### ISSUE TITLE
System ambiguity detection does not take query filters into account

### ISSUE THREAD

**Issue by jannik4** [bevyengine/bevy#11796] opened 2024-02-09 16:26 UTC
## Bevy version

0.12.1

## What you did

Use a custom schedule with `ambiguity_detection` set to `LogLevel::Error`. Insert two systems that are disjoint by using `Without<T>`.

```rust
use bevy::{
    ecs::schedule::{ScheduleBuildSettings, ScheduleLabel},
    prelude::*,
};

fn main() {
    let mut app = App::new();

    app.add_plugins(DefaultPlugins);
    app.edit_schedule(MySchedule, |schedule| {
        schedule.set_build_settings(ScheduleBuildSettings {
            ambiguity_detection: bevy::ecs::schedule::LogLevel::Error,
            ..schedule.get_build_settings()
        });
    });

    app.add_systems(MySchedule, (a, b));
    app.add_systems(Update, |world: &mut World| world.run_schedule(MySchedule));

    app.run();
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, ScheduleLabel)]
struct MySchedule;

#[derive(Component)]
struct Shared;

#[derive(Component)]
struct Disjoint;

fn a(_query: Query<&mut Shared, &Disjoint>) {}

fn b(_query: Query<&mut Shared, Without<Disjoint>>) {}
```

## What went wrong

bevy panicked, although the queries are disjoint and therefore not ambiguous:

```
thread 'main' panicked at C:\Users\Jannik\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.12.1\src\schedule\schedule.rs:290:33:
Error when initializing schedule MySchedule: Systems with conflicting access have indeterminate run order.
1 pairs of systems with conflicting data access have indeterminate execution order. Consider adding `before`, `after`, or `ambiguous_with` relationships between these:
 -- b and a
    conflict on: ["debug_tick_schedule::Shared"]
```

## Additional information

Looking a little bit into the code, I noticed bevy has both `Access<T>` and `FilteredAccess<T>` to check for conflicts. But it seems it only uses only the `Access<T>` to check for conflicts here:

https://github.com/bevyengine/bevy/blob/f4dab8a4e86f965919dc7525d72dff51be70b857/crates/bevy_ecs/src/schedule/schedule.rs#L1321-L1339

I don't know if this is just an oversight or if there's a good reason for it....

**Comment by alice-i-cecile** [comment] 2024-02-09 16:35
This is an oversight / bug: we should be detecting these via `FilteredAccess`.

**Comment by rparrett** [comment] 2024-02-09 17:04
Is this a duplicate of #4381?

**Comment by jannik4** [comment] 2024-02-09 18:21
Looks like it yes. Now that #4381 is almost two years old, I wonder if something has changed so that this problem is easier to solve now?

**Comment by alice-i-cecile** [comment] 2024-02-10 01:55
The ambiguity detection internals are meaningfully cleaner now: I suspect this will be easier to tackle now.

**Closed by alice-i-cecile** 2024-02-10 01:55 UTC
Labels: C-Bug, A-ECS
