### ISSUE TITLE
.with_run_criteria() doesn't respect SystemSet state

### ISSUE THREAD

**Issue by BlondeBurrito** [bevyengine/bevy#3636] opened 2022-01-11 01:48 UTC
## Bevy version

bevy = "0.6"

## Operating system & version

Windows 10

## What you did

Example app (link below) has two possible states, in state `Go` a system prints a number to the terminal based on a `.with_run_criteria()` time step. On clicking a button the state is changed to state `Stop` which has no systems associated with it.

## What you expected to happen

After changing state the system printing to terminal during state `Go` should no longer print a number to the terminal.

## What actually happened

The system carried on executing with the timestep even though the SystemSet state had been changed.

## Additional information

Example [code](https://github.com/BlondeBurrito/testing_random_code).  The `main()` has two scenarios to try, one shows `.with_run_criteria()` and the continuous logging after a button click changes state. Swap the comments described therein and the second scenario will print numbers to the terminal until the user clicks the button and the state is changed.

**Comment by Ranchosm335** [comment] 2022-01-11 04:19
[]()

**Comment by PaperCow** [comment] 2022-01-13 04:02
What is happening is that one run criteria is overwriting the other. Under the hood `SystemSet::on_update` (and it's other state related methods) are themselves just calling `.with_run_criteria`. Adding the fixed timestamp run criteria overwrites the state based run criteria.

For reference there are a couple relevant open issues like #2233 and #1295.

**Comment by daniellga** [comment] 2022-02-02 20:48
What would be the workaround for the example showed by @BlondeBurrito to continue working with a specified FixedTimeStep + states?

**Comment by alice-i-cecile** [comment] 2022-02-15 01:47
Closing as a duplicate of #1839.

**Closed by alice-i-cecile** 2022-02-15 01:47 UTC
Labels: C-Bug, A-ECS
