### ISSUE TITLE
Animation Player being placed on wrong entity when loading certain GLTF files

### ISSUE THREAD

**Issue by LoopyAshy** [bevyengine/bevy#4416] opened 2022-04-04 18:42 UTC
## Bevy version

[28d0a40](https://github.com/bevyengine/bevy/commit/28d0a400288862e344cd16baae0dfd04f358a806)

## Operating system & version

Windows 10,

## What you did

I loaded one of the many gltf models I had to simply see its performance and how easy it was to achieve in bevy.

## What you expected to happen

I expected the animation to load, placing the `AnimationPlayer` on the base skeleton node and running perfectly considering it runs flawlessly in all other gltf viewers I have tried it with.

## What actually happened

the `AnimationPlayer` was placed on one of the meshes and as a result none of the animations could run due to the `EntityPath` being unrelated.

## Additional information
I ended up spending a lot of time debugging this problem and quickly discovered it is caused due to being placed on a incorrect entity when generated in the gltf loader.

Attached is the model,
[Drake.zip](https://github.com/bevyengine/bevy/files/8412273/Drake.zip)
my console logs (I pause the animation as soon as it loads to not spam the console)
[log.txt](https://github.com/bevyengine/bevy/files/8412269/log.txt)
I added extra prints in the animation crate to try and figure out what was going wrong.
![image](https://user-images.githubusercontent.com/42229301/161607909-513afdd5-e8fa-4941-bf5c-7d0df51d3750.png)

**Comment by mockersf** [comment] 2022-04-04 20:05
I have a fix almost ready, waiting for a few other PRs to be merged 👍 

root cause is that your scene has several root nodes

**Closed** 2022-04-05 22:08 UTC
Labels: C-Bug, A-Animation
