### ISSUE TITLE
Simple window crash on minimize (Windows 10)

### ISSUE THREAD

**Issue by vyshnavks8** [bevyengine/bevy#2018] opened 2021-04-26 15:02 UTC
## Bevy version ="0.5.0"

version using from crates.io.

## code

use bevy::prelude::*;
fn main() {
    App::build()
    .add_plugins(DefaultPlugins)
    .run();

}

This code run runs program correctly and a window is opened but when we tries to minimise it crashes simply.

#error shown after crash

thread 'main' panicked at 'Error in Device::create_swap_chain: Both `SwapChain` width and height must be non-zero. Wait to recreate the `SwapChain` until the window has non-zero area.', 
C:\.{path}\wgpu-0.7.1\src\backend\direct.rs:129:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

(exit code: 0xc000041d)

**Comment by lukors** [comment] 2021-04-26 15:13
Possible duplicate: https://github.com/bevyengine/bevy/issues/899

**Comment by mrec** [comment] 2021-04-26 20:31
Also probably duplicate of #1882 and #170

**Comment by NathanSWard** [comment] 2021-06-03 06:55
Closing as this is a duplicate of #170, #899, #1882

**Closed by NathanSWard** 2021-06-03 06:55 UTC
Labels: bug, duplicate, platform windows, windowing
