### ISSUE TITLE
Document how to use memory profiling

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#8417] opened 2023-04-17 16:04 UTC
Not going to block on it, but we should have something for how to use the feature in `profiling.md`.

_Originally posted by @hymm in https://github.com/bevyengine/bevy/pull/8272#pullrequestreview-1386606286_
            
We should also encourage users to keep this off when profiling except when explicitly needed due to the high overhead.

**Comment by Mohamed-khattab** [comment] 2023-04-19 19:14
hello @alice-i-cecile ,

 I am interested in contributing to the Beavy project on GitHub, and I noticed that there is an open issue related to creating a document.
As a new contributor, I would like to work on resolving this issue by creating the requested document. I believe that this will be a great opportunity for me to learn more about open source development and contribute to the project.

Before I proceed, I would like to confirm with you if the issue is still open and available for contributions. Additionally, I would appreciate any suggestions or feedback you may have to help me get started with creating the document.

**Comment by alice-i-cecile** [comment] 2023-04-19 22:37
Great :) This is still available. 

In order to turn this on, you need to enable the [cargo feature](https://doc.rust-lang.org/cargo/reference/features.html) [added here](https://github.com/bevyengine/bevy/pull/8272/files#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R112) when running your app.

This is the file we should be modifying: https://github.com/bevyengine/bevy/blob/main/docs/profiling.md :) Try your best to get `tracy` set up on your PC so you can test that the instructions work too! If you get stuck in the install process, post a new Discussion here for troubleshooting help so others can Google errors you run into in the future.

**Comment by theotherphil** [comment] 2024-06-07 20:45
@mockersf I've just tried using this on a MacBook in order to update the docs here.

The Zone Info tab shows information as in your PR:

<img width="1332" alt="Screenshot 2024-06-07 at 21 41 16" src="https://github.com/bevyengine/bevy/assets/1974256/dcbdbfc8-cd0b-4f37-91e5-099bc3144414">

However, the Memory tab is missing function names for the call stacks:
<img width="240" alt="Screenshot 2024-06-07 at 21 43 30" src="https://github.com/bevyengine/bevy/assets/1974256/b2f583ce-e8ec-4b36-b3e4-78051ccb4ddd">

<img width="498" alt="Screenshot 2024-06-07 at 21 44 31" src="https://github.com/bevyengine/bevy/assets/1974256/1a3aeff1-8db8-444a-acb8-3e9e974dfed3">

(Screenshots unhelpfully and somewhat irrationally truncated to not include my full name.)

Is this something that you would expect to work, or should I add a note in the docs that this isn't supported?

**Comment by mockersf** [comment] 2024-06-08 12:28
probably not supported for now!

**Closed as completed** 2024-06-25 13:13 UTC
Labels: C-Docs, D-Trivial, A-Diagnostics
