### ISSUE TITLE
Fix ssot conflict between Transform and Translation/Rotation/Scale

### ISSUE THREAD

**Issue by MarekLg** [bevyengine/bevy#327] opened 2020-08-24 17:02 UTC
At the declaration of `Transform.bool` it is noted, that this would be a temporary measure.
Are there already any ideas on how to improve this system?

If not I would like to present a possible solution:
Wherever `Transform `is required, if there is none attached, build it (maybe with #266) from `Translation`, `Rotation`, `Scale`, or `Trasform::identity()`, if nothing else is present. `DynamicBundles `would have to restrict creation to just `Transform`, which could however incorporate `Translation`, `Rotation `and/or `Scale `by using the above mentioned `TransformBuilder`.

I'm not sure if I'm missing the point here, so if I am, I'd at least try to start the discussion.

**Comment by Moxinilian** [comment] 2020-08-24 20:18
Hey!
I think this is kind of a duplicate of #229, feel free to post your suggestion there!

**Closed by Moxinilian** 2020-08-24 20:18 UTC

**Comment by MarekLg** [comment] 2020-08-24 20:54
I feel like #229 is more about conveing the current situation more clearly in the docs, not about changing it. But if you think it fits better I'll post my suggestion over there.

**Comment by Moxinilian** [comment] 2020-08-24 21:20
I'd say the title is sufficiently generic to cover changes too. But if you want we can reopen this issue!

**Comment by MarekLg** [comment] 2020-08-24 21:36
Thanks, but I think you're right. I'll post my suggestion over at #229.
