### ISSUE TITLE
Mixing of SpriteSheetComponents with TextComponents panics with MismatchedDynamicOffsetCount { actual: 0, expected: 2 }'

### ISSUE THREAD

**Issue by Bobox214** [bevyengine/bevy#208] opened 2020-08-16 16:49 UTC
When adding a UiCameraComponents and TextComponents in the exampels/2d/sprite_sheet.rs you trigger the following runtime panic:
```bash
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: MismatchedDynamicOffsetCount { actual: 0, expected: 2 }', /home/boris/.cargo/registry/src/github.com-1ecc6299db9ec823/cart-tmp-wgc-0.1.0/src/command/render.rs:892:67
```

The issue does not trigger if you spawn TextComponents and SpriteComponents.

Modified examples/2d/sprite_sheet.rs
```rust
use bevy::prelude::*;

fn main() {
    App::build()
        .add_default_plugins() 
        .add_startup_system(setup.system())
        //.add_system(animate_sprite_system.system())
        .run();
}   

fn animate_sprite_system(
    texture_atlases: Res<Assets<TextureAtlas>>,
    mut query: Query<(&mut Timer, &mut TextureAtlasSprite, &Handle<TextureAtlas>)>,
) {
    for (mut timer, mut sprite, texture_atlas_handle) in &mut query.iter() {
        if timer.finished {
            let texture_atlas = texture_atlases.get(&texture_atlas_handle).unwrap();
            sprite.index = ((sprite.index as usize + 1) % texture_atlas.textures.len()) as u32;
            timer.reset();
        }
    }
}
    
fn setup(
    mut commands: Commands,
    asset_server: Res<AssetServer>,
    mut textures: ResMut<Assets<Texture>>,
    mut texture_atlases: ResMut<Assets<TextureAtlas>>,
) {
    let texture_handle = asset_server
        .load_sync(
            &mut textures,
            "assets/textures/rpg/chars/gabe/gabe-idle-run.png",
        )
        .unwrap();
    let texture = textures.get(&texture_handle).unwrap();
    let texture_atlas = TextureAtlas::from_grid(texture_handle, texture.size, 7, 1);
    let texture_atlas_handle = texture_atlases.add(texture_atlas);
    commands
        .spawn(Camera2dComponents::default())
        .spawn(SpriteSheetComponents {
            texture_atlas: texture_atlas_handle,
            scale: Scale(6.0),
            ..Default::default()
        })
        .with(Timer::from_seconds(0.1));
    commands.spawn(UiCameraComponents::default());
    commands.spawn(TextComponents {
            text: Text {
                value: "Example".to_string(),
                font: asset_server.load("assets/fonts/FiraSans-Bold.ttf").unwrap(),
                style: TextStyle {
                    font_size: 30.0,
                    color: Color::BLACK,
                },
                ..Default::default()
            },
            ..Default::default()
        });
}   
```

**Comment by karroffel** [comment] 2020-08-16 16:53
Looks to me like this is a duplicate of #134 

If you don't think this is a duplicate, feel free to re-open the issue!

**Closed by karroffel** 2020-08-16 16:53 UTC

**Comment by Bobox214** [comment] 2020-08-16 16:55
Good point. I did not find the issue through search. Need to work on my search skills.
Sorry for duplicate.

**Comment by karroffel** [comment] 2020-08-16 16:57
No worries! I had to enter the exact name of the error for it to find the other one, so GitHub certainly is to blame here as well and did not make it any easier. :)
