### ISSUE TITLE
Duplicate access

### ISSUE THREAD

**Issue by SneakyBerry** [bevyengine/bevy#9658] opened 2023-08-31 16:48 UTC
## Bevy version

0.11.2

## What you did

Try to access `&World` and `EventWriter` simultaniously

```rust
fn main() {
    let mut app = App::new();

    #[derive(Event)]
    struct Foo;

    app.add_event::<Foo>().add_systems(First, |world: &World, foo: EventWriter<Foo>| ());

    app.run()
}
```

## What went wrong

Expected: Correct resource scoping or relevant error message.
Got irrelevant error.

## Additional information

```rust
thread 'main' panicked at 'error[B0002]: ResMut<bevy_ecs::event::Events<ashcraft_world_server::main::Foo>> in system ashcraft_world_server::main::{{closure}} conflicts with a previous Res<bevy_ecs::event::Events<ashcraft_world_server::main::Foo>> access. Consider removing the duplicate access.', C:\Users\punks\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.11.2\src\system\system_param.rs:516:13
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\std\src\panicking.rs:593
   1: core::panicking::panic_fmt
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\core\src\panicking.rs:67
   2: bevy_ecs::system::system_param::impl$6::init_state<bevy_ecs::event::Events<ashcraft_world_server::main::Foo> >
             at C:\Users\punks\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.11.2\src\system\system_param.rs:516
   3: bevy_ecs::system::system_param::impl$85::init_state<bevy_ecs::change_detection::ResMut<bevy_ecs::event::Events<ashcraft_world_server::main::Foo> > >
             at C:\Users\punks\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.11.2\src\system\system_param.rs:1384
   4: bevy_ecs::event::_::impl$0::init_state<ashcraft_world_server::main::Foo>
             at C:\Users\punks\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.11.2\src\event.rs:335
   5: bevy_ecs::system::system_param::impl$87::init_state<ref$<bevy_ecs::world::World>,bevy_ecs::event::EventWriter<ashcraft_world_server::main::Foo> >
             at C:\Users\punks\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.11.2\src\system\system_param.rs:1384
   6: bevy_ecs::system::function_system::impl$6::initialize<void (*)(ref$<bevy_ecs::world::World>,bevy_ecs::event::EventWriter<ashcraft_world_server::main::Foo>),ashcraft_world_server::main::closure_env$0>
             at C:\Users\punks\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.11.2\src\system\function_system.rs:483
   7: bevy_ecs::schedule::schedule::ScheduleGraph::initialize
             at C:\Users\punks\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.11.2\src\schedule\schedule.rs:849
   8: bevy_ecs::schedule::schedule::Schedule::initialize
             at C:\Users\punks\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.11.2\src\schedule\schedule.rs:244
   9: bevy_ecs::schedule::schedule::Schedule::run
             at C:\Users\punks\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.11.2\src\schedule\schedule.rs:234
  10: bevy_ecs::world::impl$3::try_run_schedule::closure$0<ref$<dyn$<bevy_ecs::schedule::set::ScheduleLabel> > >
             at C:\Users\punks\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.11.2\src\world\mod.rs:1851
  11: bevy_ecs::world::World::try_schedule_scope<tuple$<>,ref$<dyn$<bevy_ecs::schedule::set::ScheduleLabel> >,bevy_ecs::world::impl$3::try_run_schedule::closure_env$0<ref$<dyn$<bevy_ecs::schedule::set::ScheduleLabel> > > >
             at C:\Users\punks\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.11.2\src\world\mod.rs:1782
  12: bevy_ecs::world::World::try_run_schedule<ref$<dyn$<bevy_ecs::schedule::set::ScheduleLabel> > >
             at C:\Users\punks\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.11.2\src\world\mod.rs:1851
  13: bevy_app::main_schedule::impl$2::run_main::closure$0
             at C:\Users\punks\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_app-0.11.2\src\main_schedule.rs:146
  14: bevy_ecs::world::World::resource_scope<bevy_app::main_schedule::MainScheduleOrder,tuple$<>,bevy_app::main_schedule::impl$2::run_main::closure_env$0>
             at C:\Users\punks\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.11.2\src\world\mod.rs:1344
  15: bevy_app::main_schedule::Main::run_main
             at C:\Users\punks\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_app-0.11.2\src\main_schedule.rs:144
  16: core::ops::function::FnMut::call_mut<void (*)(ref_mut$<bevy_ecs::world::World>,bevy_ecs::system::system_param::Local<bool>),tuple$<ref_mut$<bevy_ecs::world::World>,bevy_ecs::system::system_param::Local<bool> > >
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be\library\core\src\ops\function.rs:166
  17: core::ops::function::impls::impl$3::call_mut<tuple$<ref_mut$<bevy_ecs::world::World>,bevy_ecs::system::system_param::Local<bool> >,void (*)(ref_mut$<bevy_ecs::world::World>,bevy_ecs::system::system_param::Local<bool>)>
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be\library\core\src\ops\function.rs:294
  18: bevy_ecs::system::exclusive_function_system::impl$4::run::call_inner<tuple$<>,bevy_ecs::system::system_param::Local<bool>,ref_mut$<void (*)(ref_mut$<bevy_ecs::world::World>,bevy_ecs::system::system_param::Local<bool>)> >
             at C:\Users\punks\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.11.2\src\system\exclusive_function_system.rs:203
  19: bevy_ecs::system::exclusive_function_system::impl$4::run<tuple$<>,void (*)(ref_mut$<bevy_ecs::world::World>,bevy_ecs::system::system_param::Local<bool>),bevy_ecs::system::system_param::Local<bool> >
             at C:\Users\punks\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.11.2\src\system\exclusive_function_system.rs:206
  20: bevy_ecs::system::exclusive_function_system::impl$1::run<void (*)(bevy_ecs::system::system_param::Local<bool>),void (*)(ref_mut$<bevy_ecs::world::World>,bevy_ecs::system::system_param::Local<bool>)>
             at C:\Users\punks\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.11.2\src\system\exclusive_function_system.rs:103
  21: bevy_ecs::schedule::executor::single_threaded::impl$0::run::closure$0
             at C:\Users\punks\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.11.2\src\schedule\executor\single_threaded.rs:98
  22: core::ops::function::FnOnce::call_once<bevy_ecs::schedule::executor::single_threaded::impl$0::run::closure_env$0,tuple$<> >
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be\library\core\src\ops\function.rs:250
  23: core::panic::unwind_safe::impl$23::call_once<tuple$<>,bevy_ecs::schedule::executor::single_threaded::impl$0::run::closure_env$0>
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be\library\core\src\panic\unwind_safe.rs:271
  24: std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<bevy_ecs::schedule::executor::single_threaded::impl$0::run::closure_env$0>,tuple$<> >
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be\library\std\src\panicking.rs:500
  25: bevy_ecs::world::unsafe_world_cell::UnsafeWorldCell::get_resource_mut_by_id
  26: std::panicking::try<tuple$<>,core::panic::unwind_safe::AssertUnwindSafe<bevy_ecs::schedule::executor::single_threaded::impl$0::run::closure_env$0> >
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be\library\std\src\panicking.rs:464
  27: std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<bevy_ecs::schedule::executor::single_threaded::impl$0::run::closure_env$0>,tuple$<> >
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be\library\std\src\panic.rs:142
  28: bevy_ecs::schedule::executor::single_threaded::impl$0::run
             at C:\Users\punks\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.11.2\src\schedule\executor\single_threaded.rs:97
  29: bevy_ecs::schedule::schedule::Schedule::run
             at C:\Users\punks\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.11.2\src\schedule\schedule.rs:235
  30: bevy_ecs::world::impl$3::run_schedule::closure$0<ref$<dyn$<bevy_ecs::schedule::set::ScheduleLabel> > >
             at C:\Users\punks\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.11.2\src\world\mod.rs:1865
  31: bevy_ecs::world::World::try_schedule_scope<tuple$<>,ref$<dyn$<bevy_ecs::schedule::set::ScheduleLabel> >,bevy_ecs::world::impl$3::run_schedule::closure_env$0<ref$<dyn$<bevy_ecs::schedule::set::ScheduleLabel> > > >
             at C:\Users\punks\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.11.2\src\world\mod.rs:1782
  32: bevy_ecs::world::World::schedule_scope<tuple$<>,ref$<dyn$<bevy_ecs::schedule::set::ScheduleLabel> >,bevy_ecs::world::impl$3::run_schedule::closure_env$0<ref$<dyn$<bevy_ecs::schedule::set::ScheduleLabel> > > >
             at C:\Users\punks\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.11.2\src\world\mod.rs:1836
  33: bevy_ecs::world::World::run_schedule<ref$<dyn$<bevy_ecs::schedule::set::ScheduleLabel> > >
             at C:\Users\punks\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.11.2\src\world\mod.rs:1865
  34: bevy_app::app::App::update
             at C:\Users\punks\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_app-0.11.2\src\app.rs:244
  35: bevy_app::app::run_once
             at C:\Users\punks\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_app-0.11.2\src\app.rs:973
  36: core::ops::function::FnOnce::call_once<void (*)(bevy_app::app::App),tuple$<bevy_app::app::App> >
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be\library\core\src\ops\function.rs:250
  37: core::ops::function::FnOnce::call_once<void (*)(bevy_app::app::App),tuple$<bevy_app::app::App> >
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be\library\core\src\ops\function.rs:250
  38: alloc::boxed::impl$47::call_once<tuple$<bevy_app::app::App>,dyn$<core::ops::function::FnOnce<tuple$<bevy_app::app::App>,assoc$<Output,tuple$<> > >,core::marker::Send>,alloc::alloc::Global>
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be\library\alloc\src\boxed.rs:1993
  39: bevy_app::app::App::run
             at C:\Users\punks\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_app-0.11.2\src\app.rs:292
  40: ashcraft_world_server::main
             at .\ashcraft_world_server\src\main.rs:47
  41: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be\library\core\src\ops\function.rs:250
```

**Comment by ItsDoot** [comment] 2023-08-31 16:58
The issue is that taking `&World` as a parameter blocks mutable access to anything in the world, as anything mutable would mutably alias with the `&World`. `EventWriter` does take a resource by mutable reference: https://github.com/bevyengine/bevy/blob/ee3cc8ca86a40cbfdad1883f29f1c4be975b8ac8/crates/bevy_ecs/src/event.rs#L513-L516

The error isn't irrelevant, but it also doesn't make it all that obvious that taking `&World` blocks all mutable access.

**Comment by SneakyBerry** [comment] 2023-08-31 17:02
I think that error should be on type level. Like it is with `&mut World`. You can't have ant params if World taken as mut. So can we do the same with &World, except checking that we don't have any mutable access there? Or at least make error more clear. It take me about two hours to determine the problem

**Comment by alice-i-cecile** [comment] 2023-08-31 17:03
We *could* automatically do what `resource_scope` does for `&World` + mutable accesses. Which would in theory allow other systems to run in parallel compared to `&mut World`.

But that's a very theoretical benefit, since only read-only systems could be parallelized, which are both very rare and not typically performance heavy.

I think we should close this out.

**Closed** 2023-08-31 20:22 UTC
Labels: C-Bug, A-ECS
