### ISSUE TITLE
`TextStyle::color` doesn't support alpha, always renders opaque

### ISSUE THREAD

**Issue by djeedai** [bevyengine/bevy#3204] opened 2021-11-27 11:12 UTC
## Bevy version

0.5.0

## Operating system & version

Windows 10

## What you did

```rust
TextStyle {
  font: font.clone(),
  font_size: 250.0,
  color: Color::NONE,
},
```

## What you expected to happen

Text is full transparent, doesn't render.

## What actually happened

Text renders black, which is (0,0,0,1) instead of `NONE`=(0,0,0,0)

## Additional information

This makes it impossible to fade texts in/out.

`TextStyle` has no documentation, so technically that's a bug.

**Comment by Davier** [comment] 2021-11-27 15:31
I can't reproduce the issue, using db55bf5 on Linux. Could someone else try it on Windows?

**Comment by rparrett** [comment] 2022-10-11 15:33
I can't reproduce with

Windows
```
AdapterInfo { name: "NVIDIA GeForce GTX 1660", vendor: 4318, device: 8580, device_type: DiscreteGpu, backend: Vulkan }
```

MacOS
```
AdapterInfo { name: "Apple M1 Max", vendor: 0, device: 0, device_type: IntegratedGpu, backend: Metal }
```

@djeedai are you still experiencing this?

**Comment by TimJentzsch** [comment] 2024-01-25 20:16
# Triage

I also can't reproduce the issue on Linux with Bevy 0.12.

Reproduction code: <https://github.com/TimJentzsch/bevy_triage/tree/main/issues/issue_3204>

The text fades in and out and the transparency works correctly:
![Red text at 0.33 alpha](https://github.com/bevyengine/bevy/assets/13908946/6650914a-580d-4436-8faf-f701d4b87c04)

Considering that others could also not reproduce the issue, I will close this one out.
@djeedai if you're still experiencing this, feel free to reopen!

**Closed by TimJentzsch** 2024-01-25 20:16 UTC
Labels: C-Bug, A-Rendering, A-UI
