### ISSUE TITLE
500% increase CPU usage when app goes to background

### ISSUE THREAD

**Issue by olegus199** [bevyengine/bevy#9040] opened 2023-07-04 11:37 UTC
## Bevy version

0.10.1

## \[Optional\] Relevant system information

iMac 27 late 2012, core i7, NVIDIA GeForce GTX 675MX 1GB, 24GB RAM, macOS Catalina 10.15.7

## What you did

I noticed that Bevy consumes massive amount of CPU when going to background when I focus on the another window (VS code, for instance)
This is normal load of 59% of CPU. Bevy window is focused
![Screenshot 2023-07-04 at 14 20 10](https://github.com/bevyengine/bevy/assets/128966780/6b472666-57df-4167-9a22-babc9d3c7e5b)
This is abnormal load of 284.8% of CPU. VS code is focused, Bevy on the background
![Screenshot 2023-07-04 at 14 22 22](https://github.com/bevyengine/bevy/assets/128966780/121cbc95-43e7-4cc9-adc6-db7e515189bd)

**Comment by mockersf** [comment] 2023-07-04 12:08
duplicate of #8080 and #5856

**Closed** 2023-08-03 00:03 UTC
Labels: C-Bug, A-Windowing, O-MacOS
