### ISSUE TITLE
Registering systems via world.register_system are unable to be excluded from despawn recursive patterns

### ISSUE THREAD

**Issue by alexparlett** [bevyengine/bevy#12890] opened 2024-04-06 15:29 UTC
## Bevy version

0.13.1

## What you did

Using a standard cleanup pattern between app states removes any dynamic systems registered with `world.register_system(...)`

````
pub fn cleanup_entities(
    mut commands: Commands,
    query: Query<(Entity, Option<&Name>), (Without<Persistent>, Without<Parent>, Without<Window>)>,
) {
    for (entity, name) in query.iter() {
        info!("Removing entity with name:{:?}, id: {:?}", name, commands.entity(entity).id());
        commands.entity(entity).despawn_recursive();
    }
}
````

## What went wrong

The system is registered using

````
pub fn register_boxed_system<I: 'static, O: 'static>(
        &mut self,
        system: BoxedSystem<I, O>,
    ) -> SystemId<I, O> {
        SystemId(
            self.spawn(RegisteredSystem {
                initialized: false,
                system,
            })
            .id(),
            std::marker::PhantomData,
        )
    }
````

This inserts a `RegisteredSystem`

However this struct is not public so I am unable to exlude it from my cleanup.

**Comment by alice-i-cecile** [comment] 2024-04-06 15:31
This is effectively a duplicate of #12852: I'm going to close this and encourage you to participate there :)

**Closed by alice-i-cecile** 2024-04-06 15:31 UTC
Labels: C-Bug, S-Duplicate, A-ECS
