### ISSUE TITLE
UI nodes using Val::Percent are positioned incorrectly when UI camera scale is not 1.0

### ISSUE THREAD

**Issue by forbjok** [bevyengine/bevy#3901] opened 2022-02-08 21:24 UTC
## Bevy version
0.6.0 and main branch

## Operating system & version
Windows 10

## What you did
Change UI camera scale to something other than 1.0.

## What you expected to happen
The UI to scale itself correctly according to the new scale (as happens when you do the same thing with the 2D camera)

## What actually happened
At 1.0 everything looks fine, but as soon as the scale is increased, nodes with their sizes specified with Val::Percent(100.0) in order to fill the entire screen (mostly in order to be able to center child nodes) stretch outside the window in the direction of the upper right corner, making only a small portion of them visible at 2.0 scale and pushing them completely off-screen at 3.0 or higher.

Example showing the problem.
Initially, the window is very small and the camera scale is at 1.0, but as I resize the window past a certain size my code changes the UI camera scale and the UI node used to center the title screen image ends up only partially visible in the top right corner.

https://user-images.githubusercontent.com/4687674/153076614-c8eda42d-21e3-413c-9549-d1dffd1a28ab.mp4

## Additional information
I did some investigation on this, and while I as able to fix the positioning issue by multiplying window.physical_width() and physical_height() with the camera scale in bevy_ui::flex::FlexSurface::update_window, that creates a different issue with fonts looking completely smudged and unreadable when scaled up, instead of crisp like they're supposed to be. I'm guessing this is caused by some sort of cached smaller-size glyphs being reused and stretched to a larger size even after the camera scale changes, but so far I haven't been able to find out how to actually fix that one.

(Attempted fix: https://github.com/forbjok/bevy/tree/fix-ui-camera-scale)

Example of smudged font:
![felix_31UNmgUHfa](https://user-images.githubusercontent.com/4687674/153077432-08ac15b2-6159-4a8c-9623-adfd78d89092.png)

What the font should actually look like:
![brave_UPziSwb5Yd](https://user-images.githubusercontent.com/4687674/153077654-48d306c6-0917-4c19-8aac-a3ff41efc232.png)

**Comment by TimJentzsch** [comment] 2024-01-25 21:25
# Triage

It looks like this works properly in Bevy 0.12.

Reproduction code: <https://github.com/TimJentzsch/bevy_triage/tree/main/issues/issue_3901>

In Bevy 0.12, the scale of the camera projection doesn't affect the UI anymore at all.
Instead, you can use the [`UiScale`](https://docs.rs/bevy_ui/latest/bevy_ui/struct.UiScale.html) resource to scale your UI. This will only change the absolute values, so your percentage scales remain in place.

In the code, I switch between 2.0 projection and 2.0 UI scale:
![A centered red rectangle and a centered red text saying "Projection Scale".](https://github.com/bevyengine/bevy/assets/13908946/7688091a-e338-4ca0-a04f-565481490053)
![A centered red rectangle and a centered red text saying "UI Scale". Everything is twice the size compared to the projection scale example.](https://github.com/bevyengine/bevy/assets/13908946/c58b246c-c5fb-473b-82b1-bc76a2764a09)

As you can see, both the rectangle and the text are centered in both examples, but only the UI scale actually increases the size.

Your smudged font example looks like the same issue as #1890.
But if you use `TextBundle` (UI) instead of `Text2dBundle` (2D rendering), you shouldn't have this problem with the current Bevy version. Just keep in mind that you need to use `UiScale` for scaling.

Considering this, I will close the issue. @forbjok if `UiScale` doesn't work for you, feel free to reopen this!

**Closed by TimJentzsch** 2024-01-25 21:25 UTC
Labels: C-Bug, A-UI

**Comment by pablo-lua** [comment] 2024-01-25 22:25
About this being closed, not exactly True. In fact, this problem exists (but in a less dramatic way) actually. This problem can be seen in #11207.
In fact, when you use a VERY high scale, you can see that the Ui node can be almost anywhere in the screen.

**Comment by rparrett** [comment] 2024-01-26 02:38
I think this is describing a bug that could not possibly exist anymore. Bevy hasn't had a separate UI camera since Bevy 0.8.

If there's some similar behavior in Bevy 0.12 with UiScale that's not covered b y #11207, we should open a new issue with a new repro.

**Comment by forbjok** [comment] 2024-02-16 15:52
Yes, I seem to recall this issue was fixed a long time ago, long before even 0.12. I had no idea this issue existed open for so long.
