### ISSUE TITLE
Some examples freeze after launch on macos. 

### ISSUE THREAD

**Issue by warycat** [bevyengine/bevy#107] opened 2020-08-11 06:26 UTC
```
cargo run --example ui
```

**Comment by tbillington** [comment] 2020-08-11 07:03
`ui` works on my mac, when I resize the window I can see it re-rendering.

**Comment by warycat** [comment] 2020-08-11 21:10
I switch to stable rust. The cpu is not running crazy in this time. The examples will be better if they respond to user interaction.

**Comment by StarArawn** [comment] 2020-08-17 13:26
The `ui` example works well for me too. I do agree I was initially confused by the ui example as it doesn't show any interactivity. I think it's mainly meant to showcase the rendering aspects of `bevy_ui`.

**Comment by Moxinilian** [comment] 2020-09-02 07:09
I'm closing this, as it seems to be expected behaviour.

**Closed by Moxinilian** 2020-09-02 07:09 UTC
Labels: bug, examples
