### ISSUE TITLE
cpu usage

### ISSUE THREAD

**Issue by coolit** [bevyengine/bevy#111] opened 2020-08-11 07:36 UTC
e.g. In the "button" example,  sometimes the cpu usage is about 10-20% in release mode, which is relatively high. 
Is there any plan for future improvement? Thanks.
edit: I used win10, Intel 2.40GHz.

**Comment by joseluis** [comment] 2020-08-11 08:05
CPU usage is between 300% and 400% for me with the simplest examples (button, sprite...)

**Comment by martin-fl** [comment] 2020-08-11 10:06
I confirm this. 
On a  i7-7700HQ CPU @ 2.80GHz × 8 and iGPU, htop outputs indicates that e.g the breakout example takes ~40% on all cores

**Comment by skreborn** [comment] 2020-08-11 10:07
@coolit @joseluis @martin-fl What operating systems, hardware, and render backend do you all use?

**Comment by martin-fl** [comment] 2020-08-11 10:12
@skreborn  
I'm using PopOS 20.04 with Linux 5.4 on a Intel® Core™ i7-7700HQ CPU @ 2.80GHz × 8 and Mesa Intel® HD Graphics 630 (KBL GT2). The render backend is Vulkan I suppose.

**Comment by coolit** [comment] 2020-08-11 10:31
@skreborn  win10, Intel 2.40GHz.

**Comment by skreborn** [comment] 2020-08-11 10:38
I have anywhere between 50% and 70% usage on Windows 10 with an *Intel® Core™ i7-9750H CPU @ 2.60GHz × 12* and an *NVIDIA GeForce RTX 2080 Max-Q* for `button`.

It's worth noting that release mode reduces that to slightly above 30%.

**Comment by MGlolenstine** [comment] 2020-08-11 10:44
It's not just low-end hardware


![image](https://user-images.githubusercontent.com/9406770/89888507-59883280-dbd0-11ea-9771-efe40fbdcca9.png)

**Comment by martin-fl** [comment] 2020-08-11 10:50
> It's worth noting that release mode reduces that to slightly above 30%.

Compiling in release mode does in fact reduce CPU usage to ~10% on the `button` and `breakout` example on my computer.

**Comment by Timidger** [comment] 2020-08-12 01:06
Release mode had the sprite example running at around 30% for me, based on htop. Bit disappointing such a simple example isn't performant, but the library looks like a great start so I feel silly even making the complaint. I figure this will be fixed quickly.

[here is a flamegraph](https://gist.github.com/Timidger/40d625f72be7a91223be8babfad9551a#file-flamegraph-svg), hopefully it's helpful

**Comment by cart** [comment] 2020-08-12 01:21
I expect there to be a _ton_ of low hanging fruit when it comes to optimization. So far the focus has been on api surface and building solid foundations. For example, right now Bevy is way more hash-ey per-frame than I would like it to be. We can fix most of the CPU getting eaten there by using the new "change detection" features in Bevy ECS.

On top of that, I think some persistent CPU usage is expected, as we (currently) use rayon under the hood and other projects have encountered similar behavior. I think the most important metric bevy can optimize is frame_time (which you can measure by adding the `FrameTimeDiagnosticsPlugin` and `PrintDiagnosticsPlugin` to your app).

This is the sort of issue that will never fully be resolved. There will always optimization work to do.

I am inclined to close this issue (and reference it whenever a new one comes up).  Feel free to open issues for specific cases where you have isolated slow parts of Bevy.

(also i wont close this for a small period of time. feel free to respond here with rationale if you think leaving this open is better)

**Comment by coolit** [comment] 2020-08-12 02:12
If I understand correctly, when the "change detention" feature is available, the cpu usage will be much lower. But by then, is it possible to set the frame_time manually, to suit different use cases?

**Comment by aclysma** [comment] 2020-08-16 08:21
This is a problem with rayon. The more cores you have, the more CPU you burn. My 3950x pins the CPU at 100% in the window_settings example. I've seen this behavior on several projects that use rayon.

https://github.com/rayon-rs/rayon/issues/642

**Comment by aclysma** [comment] 2020-08-17 01:24
As a workaround for anyone having an unpleasant time with this, you can use the environment variable RAYON_NUM_THREADS to limit the number of threads. I would recommend anyone with more than 8 cores set it to something <=8.

Just to be clear, this isn't "bevy is using a lot of CPU" it's "rayon doesn't properly idle threads that have no work to do". A 32 logical core CPU will pin at 100%, but when forced to use 8 logical cores, will run at about 13% utilization (despite that being 25% of the cores). That is still higher than it ought to be. I don't think bevy's examples generate enough workload to justify saturating multiple cores.

**Comment by tbillington** [comment] 2020-08-17 04:57
Would something like Unity's [`Application.targetFrameRate`](https://docs.unity3d.com/ScriptReference/Application-targetFrameRate.html) be related to this issue?

**Comment by multun** [comment] 2020-08-17 05:20
that's probably fixed by https://github.com/rayon-rs/rayon/pull/746

**Comment by WimbledonLabs** [comment] 2020-08-25 21:24
Rayon 1.4.0 has been released with the fix! https://github.com/rayon-rs/rayon/issues/784

[Release notes](https://github.com/rayon-rs/rayon/blob/master/RELEASES.md) - "Implemented a new thread scheduler, RFC 5, which uses targeted wakeups for new work and for notifications of completed stolen work, reducing wasteful CPU usage in idle threads."

**Comment by dseevr** [comment] 2020-08-28 20:10
I ran the breakout example on my old quadcore machine using master and also using master + rayon bumped to 1.4.  Both were run in release mode:

Master CPU usage:  220%
Master + rayon 1.4 CPU usage: 55%

Huge improvement but still _extremely_ high for only rendering a few rectangles. Hope to see even more improvements in the future! 🎉

**Comment by aclysma** [comment] 2020-08-29 05:58
The extreme CPU usage requires more than 4 cores to reproduce.

I roughly reproduce your results if forcing RAYON_NUM_THREADS=4
Debug 1.3 limited to 4 cores: 150%
Release 1.3 limited to 4 cores: 50%

On a 3950x (32 cores) using Bevy 0.1.3:
Debug Rayon 1.3: 900%
Release Rayon 1.3: 450%

I saw no difference with rayon 1.4:
Debug Rayon 1.4: 900%
Release Rayon 1.4: 450%

Moving to the new task system I get:
Debug Task system: 110%
Release Task system: 40%

(For whatever reason I'm not seeing the all-cores-100% I was seeing the other night but I've seen it in other projects using rayon.)

**Comment by CleanCut** [comment] 2020-08-29 19:53
The new task system (to replace Rayon) was just merged in https://github.com/bevyengine/bevy/pull/384

**Comment by Moxinilian** [comment] 2020-09-07 22:12
Can anybody experiencing high CPU usage previously testify the new task system fixes this issue?

**Comment by MGlolenstine** [comment] 2020-09-07 22:17
I will test it out on my work computer (the one I ran it on before) in about 9 hours.

**Comment by CleanCut** [comment] 2020-09-08 00:15
Examples no longer saturate all cores on my computer. The use far less than a single core now.  Seems good to me on mac. 👍

**Comment by MGlolenstine** [comment] 2020-09-08 06:27
The CPU usage while running the Button example has been fixed on my work computer as well.

![image](https://user-images.githubusercontent.com/9406770/92440582-055f7680-f1ad-11ea-824a-cfb10056b03e.png)

**Comment by cart** [comment] 2020-09-08 06:43
Alrighty I think that's enough evidence to close this out. CPU usage will always be a moving target and there's still plenty of optimization potential, but we've made enough progress here that I think we can move from "generic CPU usage issue" to "specific issues for specific optimization cases".

**Closed by cart** 2020-09-08 06:43 UTC
Labels: performance
