### ISSUE TITLE
Ui Editable TextBox

### ISSUE THREAD

**Issue by miketwenty1** [bevyengine/bevy#12109] opened 2024-02-25 15:12 UTC
## What problem does this solve or what need does it fill?
- Implementing an editable textbox in Bevy UI is currently very difficult.
- The best method I've devised appears quite involved, requiring a significant amount of boilerplate logic related to formatting and using the ButtonBundle.
- For now, the most practical method to obtain a textbox is through a third-party dependency. However, as Bevy is still rapidly evolving, relying on third-party support for a critical feature is challenging if you aim to keep up with the latest and greatest Bevy features.

## What solution would you like?
I'm proposing a textbox as a first-class UI element in Bevy.

Nice to have features: 
- Selectable.
- Blinking cursor location.
- Able to move cursor within string input.
- Able to handle and switch keyboard input to multiple textboxes
- Tab keyboard key moves cursor to "next textbox" location.
- Copy/Paste (Clipboard) magically work. (Including Wasm builds).

## What alternative(s) have you considered?
- UiButton with a bunch of love.

**Comment by alice-i-cecile** [comment] 2024-02-25 15:17
#12100 is very useful for this.

**Comment by rparrett** [comment] 2024-02-25 20:30
This is a duplicate of #6213. Some broad UI goals / issues for specific widgets have been tracked here: https://github.com/orgs/bevyengine/projects/10 in the past.

> The best method I've devised appears quite involved, requiring a significant amount of boilerplate logic related to formatting and using the ButtonBundle.

Could you elaborate on the challenges you've faced implementing this? Because the same challenges will exist in-engine and we will want to work towards improving that. We should identify specific issues and try to fix them. For example: <https://github.com/bevyengine/bevy/issues/11297>

Cursors / selection are definitely difficult at the moment, though probably not impossible. I can't recall if #10193 would actually help with that.

Doing this in-engine at this moment also seems difficult/blocked at the moment while we wait to see how <https://github.com/bevyengine/bevy/discussions/9538> turns out, which is a favored proposal for spawning widgets consisting of multiple entities.

**Comment by miketwenty1** [comment] 2024-02-25 21:27
@rparrett 

> This is a duplicate of #6213. Some broad UI goals / issues for specific widgets have been tracked here: 

I'm thinking this isn't quite a duplicate. I'm asking for more than just input unicode text, I'm asking for a fully functioning textbox that you could expect to see on a website.

> Could you elaborate on the challenges you've faced implementing this?

Trying to implement a Cursor as a blinking pipe within button text is not ideal. Using the button UI to help with selection. Keeping track in a nice neat way all the buffers for all the text boxes and switching between them was non-trivial for me. Adding keeping track of a cursor on top of that is additional complexity.

> Doing this in-engine at this moment also seems difficult/blocked at the moment while we wait to see how https://github.com/bevyengine/bevy/discussions/9538 turns out, which is a favored proposal for spawning widgets consisting of multiple entities.

It seems this issue is blocked until #9538 is done/merged?

**Closed** 2024-02-25 22:30 UTC
Labels: C-Enhancement, A-UI
