### ISSUE TITLE
Ray Tracing and Detecting Cursor Position.

### ISSUE THREAD

**Issue by iMplode-nZ** [bevyengine/bevy#922] opened 2020-11-24 02:49 UTC
**What problem does this solve or what need does it fill?**

Being able to project rays into the world.

**Describe the solution would you like?**

I would like an extension to MouseMotion that provides the current position of the mouse, as well as a function on a camera that takes a position in the window and converts it into a ray originating from the camera position. This should not do any colliding with objects within the scene, as I believe just having a ray may be more useful.

**Describe the alternative(s) you've considered?**

bevy_mod_picking is a bit too high-level for my needs; I would like to find where a user is clicking on the x-z plane, but that involves making two separate planes with PickableMesh and InteractiveMesh, facing in opposite directions.

**Comment by bonsairobo** [comment] 2020-12-04 07:35
This is a duplicate of https://github.com/bevyengine/bevy/issues/197

**Closed** 2020-12-04 09:13 UTC
Labels: enhancement
