### ISSUE TITLE
Fullscreen mode cannot be entered through KeyCode function.

### ISSUE THREAD

**Issue by HeavyRain266** [bevyengine/bevy#3311] opened 2021-12-12 19:43 UTC
## Bevy version

`0.5`

## Operating system & version

Windows 11

## What you did

Created a function `fullscreen` which takes uses `F` key to change WindowMode::Windowed into WindowMode::Fullscreen.

```rs
use bevy::{
    prelude::*,
    window::WindowMode,
    diagnostic::LogDiagnosticsPlugin
};

fn fullscreen(
    input: Res<Input<KeyCode>>,
    mut win_desc: ResMut<WindowDescriptor>
) {
    if input.pressed(KeyCode::F) {
        win_desc.mode =
            WindowMode::Fullscreen {
                use_size: false
	   }
   }
}

fn main() {
    App::build()
        .insert_resource
           (
               WindowDescriptor
                   {
                      title: "Fullscreen bug".into(),
                      mode: WindowMode::Windowed,
                      
                      ..Default::default()
                   }
           )
        // .add_startup_system(fullscreen.system()) doesn't change anything.
        .add_system(fullscreen.system())
        .add_plugins(DefaultPlugins)
        .add_plugin(LogDiagnosticsPlugin::default())
        .run();
}

```

## What you expected to happen

When user press `F` key, window should turn into fullscreen mode.

## What actually happened

When user press `F` key with this function enable fullscreen mode but it doesn't do anything.

## Additional information

Plugin `LogDiagnosticsPlugin::default()` doesn't log anything about it.

**Comment by DJMcNab** [comment] 2021-12-12 19:46
Duplicate of https://github.com/bevyengine/bevy/issues/2879

**Closed** 2021-12-12 19:57 UTC
Labels: A-Window, C-Usability
