### ISSUE TITLE
Bevy default plugins WindowPlugin creates a "Not Responding" window

### ISSUE THREAD

**Issue by Tofaa2** [bevyengine/bevy#2928] opened 2021-10-07 17:25 UTC
## Bevy version
0.5.0 (Latest)
The release number or commit hash of the version you're using.

## Operating system & version
Windows 10
Ex: Windows 10, Ubuntu 18.04, iOS 14.

## What you did
Started a new project and followed the tutorial available in the book. Got until the add_plugins() bit and this is where the crash started

Code: 

```
use bevy::prelude::*;

struct Person;
struct Name(String);

fn main() {
    App::build()
        .add_plugins(DefaultPlugins)
        .add_startup_system(add_people.system())
        .add_system(greet_people.system())
        .add_system(hello_world.system())
        .run();
}

fn hello_world() {
    println!("Hello World!");
}

fn add_people(mut commands: Commands) {
    commands
        .spawn()
        .insert(Person)
        .insert(Name("Elaina Proctor".to_string()));
    commands
        .spawn()
        .insert(Person)
        .insert(Name("Renzo Hume".to_string()));
    commands
        .spawn()
        .insert(Person)
        .insert(Name("Zayna Nieves".to_string()));
}
fn greet_people(query: Query<&Name, With<Person>>) {
    for name in query.iter() {
        println!("hello {}!", name.0);
    }
}
```

The steps you took to uncover this bug. Please list full reproduction steps if
feasible.

## What you expected to happen
Was supposed to create a default window and keep it there

What you think should've happened if everything was working properly.
Same thing as the example
## What actually happened

The actual result of the actions you described.

## Additional information

Any additional information you would like to add such as screenshots, logs, etc.
Log

```
PS C:\Users\Tofig\Desktop\Code work\blade_bound> cargo run
   Compiling blade_bound v0.1.0 (C:\Users\Tofig\Desktop\Code work\blade_bound)
    Finished dev [unoptimized + debuginfo] target(s) in 3.57s
     Running `target\debug\blade_bound.exe`
Hello World!
hello Elaina Proctor!
hello Renzo Hume!

hello Zayna Nieves!
error: process didn't exit successfully: `target\debug\blade_bound.exe` (exit code: 0xc000041d)
```

**Comment by DJMcNab** [comment] 2021-10-07 18:21
What's the contents of your `Cargo.toml`?

**Comment by KaOs1** [comment] 2021-10-11 11:55
Not sure if it can help, but I had a the same crashing issue while trying out bevy few days ago: It turned out that I had the LunarG Vulkan SDK installed and that was messing with the Vulkan validation layer somehow. I resolved it by uninstalling the Vulkan SDK.

**Comment by sebimoe** [comment] 2021-10-11 11:58
I had the same issue and solved it with 
```toml
[profile.dev.package.gfx-backend-vulkan]
opt-level = 3
debug-assertions = false
```

**Comment by alice-i-cecile** [comment] 2021-10-18 21:16
> Could you help him? I would love to know what happend so i can try some stuff.

Ultimately, not really. They swapped over to their Linux install and everything worked fine. Seemed like some sort of GPU driver issue to me. https://github.com/gfx-rs/wgpu/wiki/Known-Driver-Issues might give you clues!

**Comment by Tofaa2** [comment] 2021-10-18 21:25
> > Could you help him? I would love to know what happend so i can try some stuff.
> 
> Ultimately, not really. They swapped over to their Linux install and everything worked fine. Seemed like some sort of GPU driver issue to me. https://github.com/gfx-rs/wgpu/wiki/Known-Driver-Issues might give you clues!

aw rip. 8Unfortunately dont see anything like that that suits my issue or hardware. Thanks for the help regardless,  everyone!

**Comment by alice-i-cecile** [comment] 2023-01-06 05:37
I'm going to close this out due to age and difficulty reproducing; please comment and reopen if you run into this still.

**Closed by alice-i-cecile** 2023-01-06 05:37 UTC
Labels: C-Bug, C-Crash, C-Dependencies, S-Needs-Investigation, C-Startup
