### ISSUE TITLE
Lch color channels not matching expected semantics

### ISSUE THREAD

**Issue by IngmarBitter** [bevyengine/bevy#8125] opened 2023-03-18 19:34 UTC
## Bevy version
Release 0.10.0 (#7919), and same issue on main branch as of f255872c1e025421b9c94d1e0ab3dddc0dff51a6

## \[Optional\] Relevant system information
AdapterInfo { name: "NVIDIA GeForce RTX 3060", vendor: 4318, device: 9476, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "528.02", backend: Vulkan }

You should also consider testing the examples of our upstream dependencies to help isolate any setup-specific issue:

## What you did
Changed 2d_shapes example to this code: https://controlc.com/db7b150c
It creates a color swatch using the Lch color space.
Each row is the same lightness, each column the same hue.

## What went wrong

The lightness channel was expected to produce black when set to 0. 
It does so here: https://css.land/lch/
But in bevy it creates the bottom row, so black only when chroma is set to 0 as well.
.. but that means the row is not uniform lightness, since black is darker than any other color.
Similarly, at full lightness 1.0 I get white only if chroma is 0.0. And again, that's not the same lightness as the other colors in the same row.

![image](https://user-images.githubusercontent.com/4473591/226133535-9b3a5c1c-11dc-4b18-8522-b93b6bbf5a3c.png)

See also https://discord.com/channels/691052431525675048/1086709490520432690

**Comment by IngmarBitter** [comment] 2023-03-19 16:15
Update: 
The biggest problems seem to come from colors that are clipped when mapped to rgb. 
When I limit my Lch values to what is not clipped or just minor clipped then the resulting colors match the semantics better.
Here is a color swatch with Lch and Rgb that has 8 nameable hues at 5 lightness levels that looks perceptually uniform.
![image](https://user-images.githubusercontent.com/4473591/226188169-4e21dd27-126e-4996-8856-1eb2ccf6dd63.png)

Note however, that the hues are not evenly spaced in the h value of Lch. When I generate the color swatch with even hue spacing, then the hues do not appear evenly separated. There is no yellow and the green-cyan-blue area has an extra hue that's making the color differences in that hue range much smaller than in the red-orange-green range. I thought the point of Lch was to have perception uniformity? 
![image](https://user-images.githubusercontent.com/4473591/226188453-2fca8f09-0795-4968-8965-8e36d4cd98e2.png)

The 2d_shapes example modified to get these color swatches is here: https://controlc.com/1b5666cb

**Comment by IngmarBitter** [comment] 2023-03-19 17:05
One more observation that was unexpected:
On my uniform appearance color swatch blue is at hue 276.  But when I convert RGB 0,0,1 to Lch I get hue 306. So I set the blue column to that hue and got the chart below. Note that at the bottom it looks blue indeed, but going up to higher lightness values the appearance of hue in that column shifts a lot toward magenta. I expected with fixed hue value that there would be no shift in hue appearance.
![image](https://user-images.githubusercontent.com/4473591/226192460-ea64a1f1-e610-410a-815b-f9719a19c056.png)

**Comment by IngmarBitter** [comment] 2023-03-19 23:01
in case this color swatch is deemed useful, here is a patch file that adds it as a new example.
Ideally the 
[lch_color_swatch.patch](https://github.com/bevyengine/bevy/files/11012405/lch_color_swatch.patch)

**Comment by ldubos** [comment] 2023-03-24 21:59
Hi as the author of the implementation of LCH in bevy I can confirm that currently we are constrained by the sRGB color space ATM.

For the issue about the conversion of the "pure" blue color you can obtain the same result on the "CIE Calculator" of [Bruce Lindbloom's Web Site](http://www.brucelindbloom.com/) so it's "intended".

![image](https://user-images.githubusercontent.com/16986491/227647760-0d86911e-1ee4-47ab-ac2d-197eb16ef803.png)

Adding the Oklab version of LCH can fix the hue shift which exists in the Lab colorspace cf. [A perceptual color space for image processing](https://bottosson.github.io/posts/oklab/), I hesitated to use OkLCH instead of LCHab, on second thought it might have been better.

**Comment by IngmarBitter** [comment] 2023-03-25 05:36
Thanks for sharing the OKlab link. The [motivation section](https://bottosson.github.io/posts/oklab/#motivation-and-derivation-of-oklab) makes a lot of sense. I find it strange that there are so many color encoding systems, when really we need only two: 1) native mapping to display hardware (RGB) and 2) native mapping to human perception.  And for (2) the OKlab polar encoding OKlch seems to fit the requirement the best. All the other ones appear less useful to me. So for the purpose of having human perception matching colors, Bevy should implement OKlch. 
I'll be using it to create my color swatch again, and hopefully this time I do not need to bend the OKlch colors, but can space them evenly and get colors that look like they are perceptually evenly separated.

Either way, OKlch or the current Lch, a natural desire is to define a color in that space and then get the matching RGB. And the method of clamping RGB is no good, since that changes l, c, and h. What I'd want intuitively is the color with only chroma changed as little as possible to arrive at an RGB that is in the [0,1] range for all three components, so that no clamping is needed. That means we need maybe three methods:
a) OKlch_to_sRGB_unbounded() => RGB are not limited to [0,1]
b) OKlch_is_in_sRGB_01_cube() => bool(true) if a) would return RGB in the [0,1] range
c) OKlch_with_chroma_clamped_to_inside_sRGB_01_cube() => will return an OKlch color that differs only in the chroma channel from the input and has it with the minimal change such that a) will return RGB in the [0,1] range.

**Comment by IngmarBitter** [comment] 2023-03-25 05:51
I found this [nice OKLCH color picker](https://oklch.com/) that is explained [here](https://evilmartians.com/chronicles/oklch-a-color-picker-made-to-help-think-perceptively).

**Comment by IngmarBitter** [comment] 2023-03-25 05:58
Finally, if something needs to be redone, why are we using the OKLCH component names **Lightness**, **Chroma** and **Hue**? And in that order?

For me as an engineer / ordinary person, rather than color expert, I think of **Hue** as the primary aspect of a color, followed by **Brightness** and finally **Saturation**.   So could we adopt those names and call the color space **HuBiSa** as short form of (Hue, Brightness, Saturation) ? That's more intuitive and also more pronounceable.

**Comment by ldubos** [comment] 2023-03-25 13:55
I agree with you we probably need to provide functions which explicitly clip "correclty" the LCHab/OkLCH colorspace to RGB, but maybe a more "urgent" task is to support the DCI-P3/REC2020 colorspace to permit a wider range of color to display, but it will probably require a huge rework of the current "color workflow".

I don't know if a `HuBiSa` could be more understandable 😅 the advantage of using something which exists is the capacity to document it and give references to papers or documentation to explain how it works. Moreover it permit to users who already know it to quickly understand what it refer to, LCH/OkLCH will probably be the next standard for web (or at least be more known by peoples who work in this area).

**Comment by IngmarBitter** [comment] 2023-03-25 23:46
Hmm, I converted my color swatch code to OKLAB (renamed to HuBiSa) and the hue is indeed much more stable, as can be seen here.
![image](https://user-images.githubusercontent.com/4473591/227747125-2871b6cf-8178-4da7-a710-a03a6f543dc2.png)

However, there are a few problems:
When using the math from [Björn Ottosson](https://bottosson.github.io/) I do not get the same rgb values as shown in the [color picker](https://oklch.com/), but darker ones, especially for dark red, such as oklch(16.61% 0.068 29.23). When I interpret the Ottonson conversion not as final result, but in addition use your (Idubos) linear to nonlinear rgb conversion, then it gets brighter. Still not the same numbers as in the color picker, but something quite reasonable.  The color swatch in this post is with  that additional conversion. What is nonetheless a little concerning is that the brightness values that are everly spaced in the brightness/lightness channel do not get converted to evenly spaced values in the gray column. In particular 50% brightness does not get converted to r==g==b==50%.

I also implemented a binary search for the max saturation/chroma that will still keep the color inside the rgb cube. It's what's used for each tile of the swatch.

And looking at the evenly spaced hue columns, one every 45 degrees, they do not look perceptually evenly separated to me.

I'll experiment a little more to get something more perceptually uniform ...

**Comment by IngmarBitter** [comment] 2023-03-26 00:35
with a gamma exponent of 3.2 the brightness values and the gray intensity values line up much better.
And for the hue columns I picked red, yellow, green, cyan, blue, and red again by converting rgb to OKLCH and then derived orange as middle between red and yellow, and purple and magenta as 1/3 and 2/3 between blue and red. That makes for nameable colors that are better distributed than the 45 degree stops of OKLCH. 
![image](https://user-images.githubusercontent.com/4473591/227748848-4ac2a5e6-1de5-4bb4-8d97-f7ae7aaebd9f.png)
So for my HuBiSa color I'll make those 8 colors the evenly spaced hues at hue == 0/8, 1/8, 2/8, ..., 7/8 for red, orange, yellow, green, cyan, blue, purple and magenta.

**Comment by ldubos** [comment] 2023-03-26 02:29
I just tested with the current LCH implementation with a different setup, just to test a different approach and better understand/feel how color "moves" inside the LCHab colorspace. And for me theres is only two issues the sRGB constraint and the hue shift which exists in the Lab colorspace, maybe I am wrong and honestly it's hard to say by only displaying color in this way but I don't think it's necessary to adopt another way to represents colors other than LCH/OkLCH.

I purposely used the range [0, 1] rather than [0, 1.5] for lightness/chroma to reduce clipping issues in the sRGB colorspace (in theory chroma can be infinite).

#### Only Lightness/Chroma (x: Lightness, y: Chroma)

![image](https://user-images.githubusercontent.com/16986491/227751813-df2637b7-8047-402c-bbc2-19e2266eff66.png)

#### Only Lightness/Hue (x: Lightness, y: Hue)

![image](https://user-images.githubusercontent.com/16986491/227751847-ec2a6b2a-b0c6-41da-bc48-72a486c5534e.png)

#### Only Chroma/Hue (x: Chroma, y: Hue)

![image](https://user-images.githubusercontent.com/16986491/227751897-9e7507ff-ec37-4363-a833-37e1cb8cb89c.png)

#### All Lightness/Chroma/Hue (x: Lightness, y: Chroma & Hue)

![image](https://user-images.githubusercontent.com/16986491/227751911-3f59d116-3840-4a6a-9f43-1e2be13f0362.png)

**Comment by IngmarBitter** [comment] 2023-03-26 04:11
Hi Idubos,
I fine your swatches have too many colors. I can't think of unique names for them and if there was a chart with a color legend for them I could not match the legend color to items with equal color in the chart.
Here is my current code: https://controlc.com/1c08707c
It makes the two swatches below. They are now better in having more similar saturation in each row; orange is derived from the web's most frequent RGB value 255,165,0; purple and magenta are better visually spaced from blue and red; cyan most bright has saturation dimmed because it was sticking out.
With that there is one swatch as vivid/saturated an possible while keeping uniformity, and a second distinguishably duller. That's pretty much all the colors I need in a color picker when I want to use colors to classify/label something.
And all colors are nameable and therefore a legend can have visual correspondence to items in a chart.
The hues are gray, red, orange, yellow, green, cyan, blue, purple, magenta
The for the middle row, that's the color name, going up we can modify to red medium bright, red brightest and down to red medium dark and red darkest, and for the second chart the extra modifier dull, so something like red dull medium bright.

Now I just need a good mechanism to smoothly interpolate between those for gradients.

![image](https://user-images.githubusercontent.com/4473591/227754611-e7dc3233-c2c8-4f35-9f56-a304a207d1ec.png)
![image](https://user-images.githubusercontent.com/4473591/227754617-2fc04632-68ca-42ab-9d07-931c36ccfbb9.png)

**Comment by bemyak** [comment] 2023-09-01 09:04
I'd also like to have OKLCH support in Bevy for better gradients. [This post](https://evilmartians.com/chronicles/oklch-in-css-why-quit-rgb-hsl#oklch-vs-lch) mentions how OKLCH compares to LCH, pointing to [W3 recommendation](https://www.w3.org/TR/css-color-4/#css-gamut-mapping) to use OKLCH for gamut mapping.

**Comment by alice-i-cecile** [comment] 2024-02-29 20:12
This should be fixed now, with the addition of bevy_color.

**Closed by alice-i-cecile** 2024-02-29 20:12 UTC
Labels: C-Bug, A-Rendering
