### ISSUE TITLE
Window is unresponsive

### ISSUE THREAD

**Issue by Keithcat1** [bevyengine/bevy#1147] opened 2020-12-24 20:04 UTC
** Bevy version **
Bevy 0.4

Windows 10, stable-x86_64-pc-windows-msvc
Ran any Bevy example / program that shows a window

**What you expected to happen**
It works normally

**What actually happened**
The window becomes unresponsive. The window_settings example doesn't update the window title every second as it seems to be supposed to, and keyboard input doesn't work either.
** Extra information**

Any additional information you would like to add such as screenshots, logs, etc.

**Comment by DJMcNab** [comment] 2020-12-24 21:40
Can't reproduce with the same toolchain, operating system and on `master`. We probably need more information about your environment.

**Comment by Keithcat1** [comment] 2020-12-26 20:17
I'm using Rustc 1.48.0
I just cloned Bevy and built one of the examples and it still didn't work.
It seems that the entire application stops, it's not just the window that's not working.
I also built the Winit examples and ran them without a problem, so I don't think the problem is there.
When I run the Breakout example, I get this:
     Running `target\debug\examples\breakout.exe`
thread 'Compute Task Pool (0)' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `-2005270523`', C:\Users\Keith\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-backend-dx12-0.6.13\src\device.rs:2634:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'task has failed', C:\Users\Keith\.cargo\registry\src\github.com-1ecc6299db9ec823\async-task-4.0.3\src\task.rs:368:45

I'm using a laptop, I wonder if something about my screen is causing part of Bevy to blow sparks and quit?
SO far I've compiled the examples in debug mode. Wonder if it matters?
Would it help if I sent my binary? If it also crashes on your system then we know it's something to do with my Rust setup and not my computer.

**Comment by DJMcNab** [comment] 2020-12-26 20:22
It's almost certainly your GPU driver, are you sure it's all up-to-date.

**Comment by Keithcat1** [comment] 2021-01-09 19:33
Even if they aren't, it should still show a dialog box and exit instead of just sitting there.

**Comment by MinerSebas** [comment] 2021-05-07 15:06
Duplicate of #320

**Comment by alice-i-cecile** [comment] 2022-03-21 01:03
Closing as "cannot reproduce".

**Closed by alice-i-cecile** 2022-03-21 01:03 UTC
Labels: C-Bug, C-Dependencies
