### ISSUE TITLE
Bevy 0.5.0 crash with 0xc000041d when using DefaultPlugins on Windows 10

### ISSUE THREAD

**Issue by demmel** [bevyengine/bevy#1877] opened 2021-04-11 01:55 UTC
## Bevy version

0.5.0

## Operating system & version

Windows 10

## What you did
src/main.rs
```
use bevy::prelude::*;

#[bevy_main]
fn main() {
  App::build()
    .insert_resource(WindowDescriptor {
      title: "Test".into(),
      width: 800.0,
      height: 600.0,
      ..Default::default()
    })
    .add_plugins(DefaultPlugins)
    .run();
}
```

Build command
```
cargo run
```

## What you expected to happen

Expected the blank window to render indefinitely

## What actually happened

The window background color was never filled and just stayed white.
Process crashed after a few seconds with exit code 0xc000041d 

## Additional information

Window before crash
![Screenshot 2021-04-10 185429](https://user-images.githubusercontent.com/1518620/114289615-4616bb00-9a2e-11eb-8ad6-422aadcfccc3.png)

The same minimal example (adapted to 0.4.0 APIs of course) using Bevy 0.4.0 works as expected.

**Comment by alice-i-cecile** [comment] 2021-04-11 02:03
Just to confirm: we need all of the fast compile settings, anti-aliasing and to set the window for this to crash?

This is a good find, and that being the minimal set should help narrow this down.

**Comment by demmel** [comment] 2021-04-11 20:29
Sorry, I think the anti-aliasing isn't needed for this.  I forgot to remove that.  I haven't tried without fast-compile yet.  I'll also give that a shot.

**Comment by demmel** [comment] 2021-04-11 20:34
Looks like this repros without fast-compile as well.  I've update the example to reflect this.

**Comment by MrCuddle** [comment] 2021-04-11 20:39
Probably seen the same issue on Ubuntu.

`use bevy::prelude::*;

fn main() {
    App::build().add_plugins(DefaultPlugins).run();
}`

Gives me a segfault. 0.4.0 works as expected.

**Comment by alice-i-cecile** [comment] 2021-04-11 20:51
Okay: I can't reproduce on Windows 10 on my machine. I suspect this is an issue with one of the low-level dependencies, probably GPU-related.

Two questions for both of you:
1. Which graphics back-end are you using?
2. Is it fixed if you swap the order of the resource insertion and default plugins? See #1255, which makes a large number of bugs extra flaky.

**Comment by MrCuddle** [comment] 2021-04-11 21:10
I've made no active choice regarding the graphics back-end.

Output from valgrind below.

```
   1   │ ==239976== Memcheck, a memory error detector
   2   │ ==239976== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
   3   │ ==239976== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
   4   │ ==239976== Command: ./target/debug/bevy_pg
   5   │ ==239976== 
   6   │ ==239976== Conditional jump or move depends on uninitialised value(s)
   7   │ ==239976==    at 0x7FFA565: pa_shm_cleanup (in /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-13.99.so)
   8   │ ==239976==    by 0x7FFA7A1: pa_shm_create_rw (in /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-13.99.so)
   9   │ ==239976==    by 0x7FEA4B6: pa_mempool_new (in /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-13.99.so)
  10   │ ==239976==    by 0x7F6F9B1: pa_context_new_with_proplist (in /usr/lib/x86_64-linux-gnu/libpulse.so.0.21.2)
  11   │ ==239976==    by 0x7F3F2B6: conf_pulse_hook_load_if_running (in /usr/lib/x86_64-linux-gnu/alsa-lib/libasound_module_conf_pulse.so)
  12   │ ==239976==    by 0x4AAC0DD: ??? (in /usr/lib/x86_64-linux-gnu/libasound.so.2.0.0)
  13   │ ==239976==    by 0x4AAC544: ??? (in /usr/lib/x86_64-linux-gnu/libasound.so.2.0.0)
  14   │ ==239976==    by 0x4AACF21: snd_config_searcha_hooks (in /usr/lib/x86_64-linux-gnu/libasound.so.2.0.0)
  15   │ ==239976==    by 0x4AAD010: snd_config_searchva_hooks (in /usr/lib/x86_64-linux-gnu/libasound.so.2.0.0)
  16   │ ==239976==    by 0x4AAD11A: ??? (in /usr/lib/x86_64-linux-gnu/libasound.so.2.0.0)
  17   │ ==239976==    by 0x4AAB8F5: snd_config_search_definition (in /usr/lib/x86_64-linux-gnu/libasound.so.2.0.0)
  18   │ ==239976==    by 0x4AC83D5: ??? (in /usr/lib/x86_64-linux-gnu/libasound.so.2.0.0)
  19   │ ==239976== 
  20   │ ==239976== Conditional jump or move depends on uninitialised value(s)
  21   │ ==239976==    at 0x24DF77F5: ??? (in /usr/lib/x86_64-linux-gnu/libVkLayer_khronos_validation.so)
  22   │ ==239976==    by 0x24DD8441: ??? (in /usr/lib/x86_64-linux-gnu/libVkLayer_khronos_validation.so)
  23   │ ==239976==    by 0x24CE84E0: ??? (in /usr/lib/x86_64-linux-gnu/libVkLayer_khronos_validation.so)
  24   │ ==239976==    by 0xDAC265: ash::vk::features::DeviceFnV1_0::bind_buffer_memory (/home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/ash-0.31.0/src/vk/features.rs:4731)
  25   │ ==239976==    by 0xD69145: ash::device::DeviceV1_0::bind_buffer_memory (device.rs:2104)
  26   │ ==239976==    by 0xD1DBD2: gfx_backend_vulkan::device::<impl gfx_hal::device::Device<gfx_backend_vulkan::Backend> for gfx_backend_vulkan::Device>::bind_buffer_memory (/home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-backend-vulkan-0.7.0/src/device.rs:1063)
  27   │ ==239976==    by 0x74B564: wgpu_core::device::alloc::MemoryBlock<B>::bind_buffer (alloc.rs:98)
  28   │ ==239976==    by 0x6F3AF3: wgpu_core::device::Device<B>::create_buffer (mod.rs:535)
  29   │ ==239976==    by 0x61617D: wgpu_core::device::<impl wgpu_core::hub::Global<G>>::device_create_buffer (mod.rs:2496)
  30   │ ==239976==    by 0x78C981: <wgpu::backend::direct::Context as wgpu::Context>::device_create_buffer (/home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.7.1/src/backend/direct.rs:1100)
  31   │ ==239976==    by 0x923CCB: wgpu::Device::create_buffer (/home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.7.1/src/lib.rs:1579)
  32   │ ==239976==    by 0x9227BD: <wgpu::Device as wgpu::util::device::DeviceExt>::create_buffer_init (/home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.7.1/src/util/device.rs:54)
  33   │ ==239976== 
  34   │ ==239976== Conditional jump or move depends on uninitialised value(s)
  35   │ ==239976==    at 0x24DF77F5: ??? (in /usr/lib/x86_64-linux-gnu/libVkLayer_khronos_validation.so)
  36   │ ==239976==    by 0x24DD89A1: ??? (in /usr/lib/x86_64-linux-gnu/libVkLayer_khronos_validation.so)
  37   │ ==239976==    by 0x24DD8AB0: ??? (in /usr/lib/x86_64-linux-gnu/libVkLayer_khronos_validation.so)
  38   │ ==239976==    by 0x24CE8890: ??? (in /usr/lib/x86_64-linux-gnu/libVkLayer_khronos_validation.so)
  39   │ ==239976==    by 0xDAC2B5: ash::vk::features::DeviceFnV1_0::bind_image_memory (/home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/ash-0.31.0/src/vk/features.rs:4741)
  40   │ ==239976==    by 0xD68EA5: ash::device::DeviceV1_0::bind_image_memory (device.rs:2120)
  41   │ ==239976==    by 0xD1E392: gfx_backend_vulkan::device::<impl gfx_hal::device::Device<gfx_backend_vulkan::Backend> for gfx_backend_vulkan::Device>::bind_image_memory (/home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-backend-vulkan-0.7.0/src/device.rs:1180)
  42   │ ==239976==    by 0x74B444: wgpu_core::device::alloc::MemoryBlock<B>::bind_image (alloc.rs:107)
  43   │ ==239976==    by 0x6F83BC: wgpu_core::device::Device<B>::create_texture (mod.rs:653)
  44   │ ==239976==    by 0x61E09D: wgpu_core::device::<impl wgpu_core::hub::Global<G>>::device_create_texture (mod.rs:2811)
  45   │ ==239976==    by 0x78CD91: <wgpu::backend::direct::Context as wgpu::Context>::device_create_texture (/home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.7.1/src/backend/direct.rs:1126)
  46   │ ==239976==    by 0x923EA9: wgpu::Device::create_texture (/home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.7.1/src/lib.rs:1591)
  47   │ ==239976== 
  48   │ ==239976== Invalid read of size 8
  49   │ ==239976==    at 0x24E3419D: ??? (in /usr/lib/x86_64-linux-gnu/libVkLayer_khronos_validation.so)
  50   │ ==239976==    by 0x24E3551F: ??? (in /usr/lib/x86_64-linux-gnu/libVkLayer_khronos_validation.so)
  51   │ ==239976==    by 0x24CFDC7D: ??? (in /usr/lib/x86_64-linux-gnu/libVkLayer_khronos_validation.so)
  52   │ ==239976==    by 0xDAD74E: ash::vk::features::DeviceFnV1_0::cmd_begin_render_pass (/home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/ash-0.31.0/src/vk/features.rs:5932)
  53   │ ==239976==    by 0x72D2C8: ash::device::DeviceV1_0::cmd_begin_render_pass (device.rs:1241)
  54   │ ==239976==    by 0x8FB753: <gfx_backend_vulkan::command::CommandBuffer as gfx_hal::command::CommandBuffer<gfx_backend_vulkan::Backend>>::begin_render_pass (command.rs:289)
  55   │ ==239976==    by 0x8AA6ED: wgpu_core::command::render::RenderPassInfo<B>::start (render.rs:931)
  56   │ ==239976==    by 0x633365: wgpu_core::command::render::<impl wgpu_core::hub::Global<G>>::command_encoder_run_render_pass_impl (render.rs:1059)
  57   │ ==239976==    by 0x632292: wgpu_core::command::render::<impl wgpu_core::hub::Global<G>>::command_encoder_run_render_pass (render.rs:1005)
  58   │ ==239976==    by 0x791791: <wgpu::backend::direct::Context as wgpu::Context>::command_encoder_end_render_pass (/home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.7.1/src/backend/direct.rs:1736)
  59   │ ==239976==    by 0x925AEE: <wgpu::RenderPass as core::ops::drop::Drop>::drop (/home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.7.1/src/lib.rs:2486)
  60   │ ==239976==    by 0x55FC25: core::ptr::drop_in_place (mod.rs:179)
  61   │ ==239976==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
  62   │ ==239976== 
  63   │ ==239976== 
  64   │ ==239976== Process terminating with default action of signal 11 (SIGSEGV)
  65   │ ==239976==  Access not within mapped region at address 0x0
  66   │ ==239976==    at 0x24E3419D: ??? (in /usr/lib/x86_64-linux-gnu/libVkLayer_khronos_validation.so)
  67   │ ==239976==    by 0x24E3551F: ??? (in /usr/lib/x86_64-linux-gnu/libVkLayer_khronos_validation.so)
  68   │ ==239976==    by 0x24CFDC7D: ??? (in /usr/lib/x86_64-linux-gnu/libVkLayer_khronos_validation.so)
  69   │ ==239976==    by 0xDAD74E: ash::vk::features::DeviceFnV1_0::cmd_begin_render_pass (/home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/ash-0.31.0/src/vk/features.rs:5932)
  70   │ ==239976==    by 0x72D2C8: ash::device::DeviceV1_0::cmd_begin_render_pass (device.rs:1241)
  71   │ ==239976==    by 0x8FB753: <gfx_backend_vulkan::command::CommandBuffer as gfx_hal::command::CommandBuffer<gfx_backend_vulkan::Backend>>::begin_render_pass (command.rs:289)
  72   │ ==239976==    by 0x8AA6ED: wgpu_core::command::render::RenderPassInfo<B>::start (render.rs:931)
  73   │ ==239976==    by 0x633365: wgpu_core::command::render::<impl wgpu_core::hub::Global<G>>::command_encoder_run_render_pass_impl (render.rs:1059)
  74   │ ==239976==    by 0x632292: wgpu_core::command::render::<impl wgpu_core::hub::Global<G>>::command_encoder_run_render_pass (render.rs:1005)
  75   │ ==239976==    by 0x791791: <wgpu::backend::direct::Context as wgpu::Context>::command_encoder_end_render_pass (/home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.7.1/src/backend/direct.rs:1736)
  76   │ ==239976==    by 0x925AEE: <wgpu::RenderPass as core::ops::drop::Drop>::drop (/home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.7.1/src/lib.rs:2486)
  77   │ ==239976==    by 0x55FC25: core::ptr::drop_in_place (mod.rs:179)
  78   │ ==239976==  If you believe this happened as a result of a stack
  79   │ ==239976==  overflow in your program's main thread (unlikely but
  80   │ ==239976==  possible), you can try to increase the size of the
  81   │ ==239976==  main thread stack using the --main-stacksize= flag.
  82   │ ==239976==  The main thread stack size used in this run was 8388608.
  83   │ ==239976== 
  84   │ ==239976== HEAP SUMMARY:
  85   │ ==239976==     in use at exit: 13,533,089 bytes in 37,761 blocks
  86   │ ==239976==   total heap usage: 155,046 allocs, 117,285 frees, 4,803,281,544 bytes allocated
  87   │ ==239976== 
  88   │ ==239976== LEAK SUMMARY:
  89   │ ==239976==    definitely lost: 41,992 bytes in 26 blocks
  90   │ ==239976==    indirectly lost: 0 bytes in 0 blocks
  91   │ ==239976==      possibly lost: 1,166,866 bytes in 5,596 blocks
  92   │ ==239976==    still reachable: 12,324,231 bytes in 32,139 blocks
  93   │ ==239976==                       of which reachable via heuristic:
  94   │ ==239976==                         newarray           : 25,096 bytes in 8 blocks
  95   │ ==239976==                         multipleinheritance: 208 bytes in 2 blocks
  96   │ ==239976==         suppressed: 0 bytes in 0 blocks
  97   │ ==239976== Rerun with --leak-check=full to see details of leaked memory
  98   │ ==239976== 
  99   │ ==239976== Use --track-origins=yes to see where uninitialised values come from
 100   │ ==239976== For lists of detected and suppressed errors, rerun with: -s
 101   │ ==239976== ERROR SUMMARY: 20 errors from 4 contexts (suppressed: 0 from 0)

```

**Comment by demmel** [comment] 2021-04-11 21:15
> Which graphics back-end are you using?

I'm not sure.  I didn't change explicitly define anything about graphics backend.  I have an nvidia gtx 1080 card if that's important in some way 

> Is it fixed if you swap the order of the resource insertion and default plugins? See #1255, which makes a large number of bugs extra flaky.

Swapping resource insertion and DefaultPlugins ordering did not fix it.

**Comment by MrCuddle** [comment] 2021-04-11 21:21
Installed the latest version of the Vulkan SDK from here: https://vulkan.lunarg.com/sdk/home

No more segfaults :)

**Comment by demmel** [comment] 2021-04-11 21:44
Updating to latest version of the Vulkan SDK also resolved this for me.

**Comment by alice-i-cecile** [comment] 2021-04-11 23:44
Fantastic. Closing as resolved :)

**Closed by alice-i-cecile** 2021-04-11 23:44 UTC
Labels: crash, platform windows, regression, third party / dependencies

**Comment by sebimoe** [comment] 2021-10-11 11:56
I had the same issue and the following Cargo.toml configuration fixes it without updating the SDK:

```toml
[profile.dev.package.gfx-backend-vulkan]
opt-level = 3
debug-assertions = false
```
