### ISSUE TITLE
iOS example crashes in 0.15-rc.3 and in main

### ISSUE THREAD

**Issue by ferama** [bevyengine/bevy#16363] opened 2024-11-12 20:40 UTC
## Bevy version

I attempted to run the iOS example using 0.15-rc.3 and from the latest commit in main (4225848b0aa08519e2715070b9e617813e3ac6ad)

## Relevant system information

I'm using Rust v1.82.0 on MacOS Sonoma

## What you did

Attempting to run the iOS example crashes with:

```
fatal runtime error: Rust cannot catch foreign exceptions
Can't show file for stack frame : <DBGLLDBStackFrame: 0x3396a8160> - stackNumber:3 - name:std::sys::pal::unix::abort_internal::hffa17df7d2f273a1. The file path does not exist on the file system: /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/sys/pal/unix/mod.rs
```

It works in bevy 0.14.2

I also attemped to reduce the example removing almost everything.
This one crashes too:

```rust
//! A 3d Scene with a button and playing sound.

use bevy::prelude::*;

// the `bevy_main` proc_macro generates the required boilerplate for iOS and Android
#[bevy_main]
fn main() {
    let mut app = App::new();
    app.add_plugins(DefaultPlugins).run();
}

```

**Comment by alice-i-cecile** [comment] 2024-11-12 20:48
Can you please check 0.15.rc-2? There's a wgpu upgrade between them that is a very plausible candidate.

**Comment by ferama** [comment] 2024-11-12 21:16
Confirming that reverting the wgpu upgrade commit (4b05d2f4d8a627b9cc74ac77954e3e4cc9e672ed) makes the iOS example run again

**Comment by alice-i-cecile** [comment] 2024-11-12 22:51
Thanks a ton for checking that. I've brought it to the awareness of the relevant experts.

**Comment by Wumpf** [comment] 2024-11-12 23:01
There's not a whole lot of changes in that [wgpu version](https://github.com/gfx-rs/wgpu/releases/tag/v23.0.0) on Metal/Mac/Apple specific things. But the linked upgrade commit also does changes to xcode projects, could those be relevant? https://github.com/bevyengine/bevy/commit/4b05d2f4d8a627b9cc74ac77954e3e4cc9e672ed#diff-10e1daed39805d49f29b77cec041a235e4c8a8795169b84bdb28df24af5d6c0c
Otherwise I'd suspect it's third party crate updates that may have caused this.

**Comment by tychedelia** [comment] 2024-11-12 23:10
> But the linked upgrade commit also does changes to xcode projects, could those be relevant? [4b05d2f#diff-10e1daed39805d49f29b77cec041a235e4c8a8795169b84bdb28df24af5d6c0c](https://github.com/bevyengine/bevy/commit/4b05d2f4d8a627b9cc74ac77954e3e4cc9e672ed#diff-10e1daed39805d49f29b77cec041a235e4c8a8795169b84bdb28df24af5d6c0c)

That was due to changes in https://github.com/gfx-rs/wgpu/pull/6107.

**Comment by mockersf** [comment] 2024-11-13 00:58
fixed by https://github.com/gfx-rs/wgpu/pull/6535 on wgpu side

**Comment by mnmaita** [comment] 2024-11-25 10:17
wgpu 23.0.1 was just released, @ferama would you be able to test this again and confirm that the issue is no longer there? Thanks!

**Comment by ferama** [comment] 2024-11-25 11:45
Cloning...

```bash
git clone git@github.com:bevyengine/bevy.git
git checkout release-0.15.0
```

Patching wgpu version...

```patch
diff --git a/crates/bevy_image/Cargo.toml b/crates/bevy_image/Cargo.toml
index 7b317a521..4346ee0d8 100644
--- a/crates/bevy_image/Cargo.toml
+++ b/crates/bevy_image/Cargo.toml
@@ -49,7 +49,7 @@ image = { version = "0.25.2", default-features = false }
 # misc
 bitflags = { version = "2.3", features = ["serde"] }
 bytemuck = { version = "1.5" }
-wgpu = { version = "23", default-features = false }
+wgpu = { version = "23.0.1", default-features = false }
 serde = { version = "1", features = ["derive"] }
 derive_more = { version = "1", default-features = false, features = [
   "error",
diff --git a/crates/bevy_mesh/Cargo.toml b/crates/bevy_mesh/Cargo.toml
index 85e7c1503..8a2fda119 100644
--- a/crates/bevy_mesh/Cargo.toml
+++ b/crates/bevy_mesh/Cargo.toml
@@ -24,7 +24,7 @@ bevy_utils = { path = "../bevy_utils", version = "0.15.0-rc.3" }
 # misc
 bitflags = { version = "2.3", features = ["serde"] }
 bytemuck = { version = "1.5" }
-wgpu = { version = "23", default-features = false }
+wgpu = { version = "23.0.1", default-features = false }
 serde = { version = "1", features = ["derive"] }
 hexasphere = "15.0"
 derive_more = { version = "1", default-features = false, features = [
diff --git a/crates/bevy_render/Cargo.toml b/crates/bevy_render/Cargo.toml
index 9535fb61e..559a56946 100644
--- a/crates/bevy_render/Cargo.toml
+++ b/crates/bevy_render/Cargo.toml
@@ -68,7 +68,7 @@ codespan-reporting = "0.11.0"
 # It is enabled for now to avoid having to do a significant overhaul of the renderer just for wasm.
 # When the 'atomics' feature is enabled `fragile-send-sync-non-atomic` does nothing
 # and Bevy instead wraps `wgpu` types to verify they are not used off their origin thread.
-wgpu = { version = "23", default-features = false, features = [
+wgpu = { version = "23.0.1", default-features = false, features = [
   "wgsl",
   "dx12",
   "metal",

```

Launching...

```sh
cd examples/mobile && make run
```

It works now :) Thanks guys

**Closed** 2024-11-25 12:12 UTC
Labels: C-Bug, A-Rendering, P-High, O-iOS, S-Blocked, P-Regression

**Comment by ferama** [comment] 2024-11-25 13:12
Mmm why the issue is closed? There is not any commit with the new version of wgpu on bevy repo, I only applied the patch manually and tested it locally. Do I misunderstood something?

**Comment by tim-blackbird** [comment] 2024-11-25 13:35
The versions specified in `Cargo.toml` match any SemVer compatible updates, so there is no need to update them. Running `cargo update` is enough.
See [Cargo's docs](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html) for more info

**Comment by mockersf** [comment] 2024-11-25 22:32
I still think we should correctly specify the patch to not allow an invalid combination

**Comment by ferama** [comment] 2024-11-26 06:24
Guys unfortunately it seems there is another issue. The app launches and run with wgpu 23.0.1 but the interaction with the button doesn’t work.

I noticed that the same happens if I run a wasm build .

To be more specific running the wasm build, ui button interactions works until you open the browser developer console and enable phone screen simulator (tested with chrome) You can test it using the button example from bevy example ui folder

It works in 0.14.2, maybe I should test with 0.15rc2 this too but it seems more ui related.

**Comment by mockersf** [comment] 2024-11-27 08:23
@ferama touch interaction should now work on iOS if you try the `release-0.15.0` branch.

I couldn't reproduce in wasm. my fix was about touch, maybe this "phone screen emulator" replaces click by touches input. Could you also try?

**Comment by ferama** [comment] 2024-11-27 15:14
Now works properly on mobile, thanks again for the effort.

Still there is a regression on wasm build (works on 0.14.2, do not with release-0.15.0 branch)
Maybe this should become a separate issue.

How I tested:
```
$ cargo build --target wasm32-unknown-unknown --example button
$ wasm-server-runner target/wasm32-unknown-unknown/debug/examples/button.wasm
```

Point the chrome browser at http://127.0.0.1:1334. Interactions with the button works properly. 
Now from chrome enable developer tools, click on the button to Toggle the device toolbar. Now the button doesn't work anymore

Another proof that in 0.14.2 works is that if you point your phone mobile browser at https://bevyengine.org/examples/ui-user-interface/button/ it works as expected.

**Comment by mockersf** [comment] 2024-11-27 17:36
works for me on chromium. there's no hover but I guess that's normal as there isn't a touch equivalent, but press/release works correctly

https://github.com/user-attachments/assets/0df6d1ce-f484-4ec5-9c38-74e330ab3140

**Comment by ferama** [comment] 2024-11-28 06:56
I agree with you about the hover event. 
Anyway I have more details: If I choose iPhone SE or iPhone XR from the list it works. 
iPhone 12 pro, iPhone 14 pro max and so on it doesn't.
iPad mini it starts to work again. Maybe it is resolution related?

Repeating the steps above on 0.14.2, it always works
