### ISSUE TITLE
app.add_startup_stage_after() not working or documentation incorrect

### ISSUE THREAD

**Issue by MouseProducedGames** [bevyengine/bevy#3424] opened 2021-12-23 19:12 UTC
## Bevy version

bevy main, as of `commit 0936f4ca9d64f15f51e4d7e1b6e20b01128f1257`.

## Operating system & version

Windows 10, 19043.1415

## What you did

```rust
App:::new()
    // other `App` setup.
    .add_plugins(DefaultPlugins)
    // other `App` setup.
    .add_startup_stage_after(
        StartupStage::Startup,
        GameState::SetupAssets,
        SystemStage::parallel(),
    )
    // other `App` setup.
    .run()
```

## What you expected to happen

The stage `GameState::SetupAssets` would be scheduled for after the stage `StartupStage::Startup`.

## What actually happened

thread 'main' panicked at 'stage 'Startup' does not exist or is the wrong type'

## Additional information

From the docs:

> /// # use bevy_app::prelude::*;
> /// # use bevy_ecs::prelude::*;
> /// # let mut app = App::new();
> /// #
> /// app.add_startup_stage_after(
> ///     StartupStage::Startup,
> ///     "my_startup_stage",
> ///     SystemStage::parallel()
> /// );
> ///

**Comment by alice-i-cecile** [comment] 2021-12-23 19:17
So there are two distinct problems here:
1. The guidance is wrong.
2. CI didn't catch that!

I suspect the doc tests are just being compile checked for some reason; we need to ensure that they're actually run to catch the runtime panics.

**Comment by jakobhellermann** [comment] 2021-12-23 19:27
I tried reproducing it but for me the code
```rust
use bevy::prelude::*;

fn main() {
    App::new()
        // other `App` setup.
        .add_plugins(DefaultPlugins)
        // other `App` setup.
        .add_startup_stage_after(
            StartupStage::Startup,
            GameState::SetupAssets,
            SystemStage::parallel(),
        )
        // other `App` setup.
        .run()
}

#[derive(StageLabel, Clone, Debug, PartialEq, Eq, Hash)]
pub enum GameState {
    SetupAssets,
}
```

works without any errors.

**Comment by mockersf** [comment] 2021-12-23 20:52
> I suspect the doc tests are just being compile checked for some reason; we need to ensure that they're actually run to catch the runtime panics.

This doc test is executed during tests, and it should work... doc tests that are not run begin with a `no_run`

**Comment by alice-i-cecile** [comment] 2021-12-24 03:16
Okay, so this isn't reproducing for me either:

```rust
use bevy::app::prelude::*;
use bevy::ecs::prelude::*;

fn main() {
    let mut app = App::new();

    app.add_startup_stage_after(
        StartupStage::Startup,
        "my_startup_stage",
        SystemStage::parallel(),
    );
}
```

I was surprised that this didn't crash, but it looks like we now add default stages in `App::new`, which didn't used to be the case.

I'm going to close this out; we can reopen with a more exact cause if it arises.

**Closed by alice-i-cecile** 2021-12-24 03:16 UTC
Labels: C-Bug, C-Docs, A-ECS

**Comment by MouseProducedGames** [comment] 2021-12-24 03:31
Problem fixed by fixing the variable name elsewhere, as the listed line was no longer the problem, but the error returned was the same.
