### ISSUE TITLE
Memory error with wgpu on macOS

### ISSUE THREAD

**Issue by Be3y4uu-K0T** [bevyengine/bevy#11102] opened 2023-12-27 16:25 UTC
## Bevy version

```ignore
# Cargo.toml
[package]
name = "my_project"
version = "1.0.0"
edition = "2021"

[workspace]
resolver = "2"

[profile.release]
strip = true
opt-level = 3
codegen-units = 1

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = "0.12.1"
```

## Relevant system information

```ignore
% uname -a
Darwin MacBook-Air-*.local 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:34 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T8103 arm64
% rustc -V
rustc 1.77.0-nightly (2df6406b8 2023-12-26)
% cargo -V
cargo 1.77.0-nightly (363a2d113 2023-12-22)
```

Adapter info:
```ignore
2023-12-27T15:56:35.613130Z  INFO bevy_render::renderer: AdapterInfo { name: "Apple M1", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
```

## What you did

Run simple code:
```rust
pub use bevy::prelude::*;

fn main() {
    App::new()
        .add_plugins(DefaultPlugins) // <-- Error: exc_bad_access
        .run();
}
```

### What were you expecting?

No error.

### What actually happened?
Various errors on each starts:
* `zsh: bus error`
* `zsh: segmentation fault`
* `-[_MTLCommandEncoder dealloc]:131: failed assertion 'Command encoder released without endEncoding'`
* `AddInstanceForFactory: No factory registered for id <CFUUID 0x147612cd0>`

## Additional information

I used lldb from VScode and found this:
```rust
pub fn required_features(&self) -> Features {
    match *self { // <-- Error: exc_bad_access
```
```
/Users/*/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-types-0.17.0/src/lib.rs:2662
/Users/*/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-core-0.17.1/src/device/resource.rs:3023
/Users/*/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-core-0.17.1/src/device/resource.rs:596
/Users/*/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-core-0.17.1/src/device/global.rs:597
...
```
I didn't save the full trace because I was looking for a solution and saved only this part. `RUST_BACKTRACE=full` did not give a result (just empty). <ins>**The solution to the problem was to reboot the system.**</ins> I think this bug may not be worth attention, but it made me suffer for a long time until I came to a simple solution.

P.S.: Sorry for my bad English.

**Comment by BD103** [comment] 2024-01-14 17:46
I was unable to reproduce this on my M1 Macbook. I'm guessing this was an unrelated issue with your Mac that was fixed by restarting it. You can probably close this issue as "not planned".

_If it ever happens to you again, though, feel free to re-open the issue!_

**Comment by Be3y4uu-K0T** [comment] 2024-01-20 12:45
Okay, thanks!

**Closed** 2024-01-20 12:45 UTC
Labels: C-Crash, C-Startup
