### ISSUE TITLE
Input not getting captured on hyprland with wayland feature

### ISSUE THREAD

**Issue by AndrewDanial** [bevyengine/bevy#13082] opened 2024-04-23 23:34 UTC
## Bevy version

Bevy 0.13.2

## \[Optional\] Relevant system information

Hyprland version 0.32.3

## What you did

Using the `wayland` feature. Created this basic started app with default plugins, a system that runs every update to print "Hello!" and included a system to close the window on escape.

```rust
use bevy::prelude::*;

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_systems(Update, (hello, mouse_test, key_test))
        .run();
}

fn hello() {
    info!("Hello!");
}

fn mouse_test(mouse: Res<ButtonInput<MouseButton>>) {
    if mouse.just_pressed(MouseButton::Left) {
        info!("Mouse pressed!");
    }
}

fn key_test(keyboard: Res<ButtonInput<KeyCode>>) {
    if keyboard.just_pressed(KeyCode::KeyA) {
        info!("A pressed!");
    }
}
```

## What went wrong

Neither the mouse button press nor the keyboard press get triggered. Additionally, the `hello()` system only triggers a few times before stopping completely. The number of times it triggers changes on each run.

## Additional information

This issue does not occur if the `wayland` feature is not included.

**Comment by AndrewDanial** [comment] 2024-04-24 00:31
> > Additionally, the `hello()` system only triggers a few times before stopping completely.
> 
> This makes me suspect that this is #10546. Can you run an example that moves on its own like `animated_transform` to confirm this?
> 
> ```shell
> cargo run --features wayland --example animated_transform
> ```

I get the same result as the user from the linked issue.

**Comment by Friz64** [comment] 2024-04-24 00:31
Okay, then we can close this as a duplicate.

**Comment by james7132** [comment] 2024-04-24 01:58
Closing as a duplicate of #10546.

**Closed by james7132** 2024-04-24 01:58 UTC
Labels: C-Bug, S-Needs-Triage
