### ISSUE TITLE
`loading_screen` example panics after switching twice

### ISSUE THREAD

**Issue by cryscan** [bevyengine/bevy#15007] opened 2024-09-01 16:06 UTC
## Bevy version

Main ([4147422](https://github.com/bevyengine/bevy/commit/41474226c3b8efa1c4515a3a39e79dcb127ea5c6))

## What you did

Run the example

```
cargo run --release --example loading_screen
```

And press "1", "2" and then press "1", to load the first scene back.

## What went wrong

The program panics with

```
     Running `target\release\examples\loading_screen.exe`
2024-09-01T16:06:13.368716Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "Windows 11 Home China", kernel: "22631", cpu: "AMD Ryzen 7 7840HS w/ Radeon 780M Graphics", core_count: "8", memory: "15.2 GiB" }
2024-09-01T16:06:13.751715Z  INFO bevy_render::renderer: AdapterInfo { name: "AMD Radeon 780M Graphics", vendor: 4098, device: 5567, device_type: IntegratedGpu, driver: "AMD proprietary driver", driver_info: "24.8.1 (LLPC)", backend: Vulkan }
2024-09-01T16:06:14.298432Z  INFO bevy_winit::system: Creating new window "App" (0v1#4294967296)
thread 'Compute Task Pool (6)' panicked at crates\bevy_render\src\mesh\allocator.rs:674:21:
internal error: entered unreachable code: Slab not found
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\std\src\panicking.rs:652
   1: core::panicking::panic_fmt
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\core\src\panicking.rs:72
   2: bevy_render::mesh::allocator::MeshAllocator::mesh_index_slice
   3: bevy_render::mesh::allocator::allocate_and_free_meshes
   4: <bevy_ecs::system::function_system::FunctionSystem<Marker,F> as bevy_ecs::system::system::System>::initialize
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Encountered a panic in system `bevy_render::mesh::allocator::allocate_and_free_meshes`!
 *  Terminal will be reused by tasks, press any key to close it. 
```

**Comment by alice-i-cecile** [comment] 2024-09-01 18:53
Duplicate of #14845 :)

**Closed by alice-i-cecile** 2024-09-01 18:53 UTC
Labels: C-Bug, S-Needs-Triage
