### ISSUE TITLE
STATUS_STACK_BUFFER_OVERRUN

### ISSUE THREAD

**Issue by 7flash** [bevyengine/bevy#5640] opened 2022-08-10 03:09 UTC
## Relevant system information

Windows 11
cargo 1.65.0-nightly (4fd148c47 2022-08-03)

## What you did

```
cargo run --features bevy/dynamic
```

## What went wrong

```ignore
    Finished dev [unoptimized + debuginfo] target(s) in 1m 28s
     Running `target\debug\seven-two.exe`
error: process didn't exit successfully: `target\debug\seven-two.exe` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)
```

## Additional information

It works well without "dynamic" feature, but fails when dynamic flag added.

./cargo/config.toml

```
[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
rustflags = ["-Zshare-generics=n"]
```

Cargo.toml

```
[package]
name = "seven-two"
version = "0.1.0"
edition = "2021"

[dependencies.bevy]
version = "0.8"
default-features = true
```

src/main.rs

```
use bevy::prelude::*;

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_startup_system(setup)
        .run();
}

fn setup() {}
```

**Comment by alice-i-cecile** [comment] 2022-08-10 04:41
Duplicate of #2921. Thanks for the reproduction all the same :)

**Closed by alice-i-cecile** 2022-08-10 04:41 UTC
Labels: C-Bug, O-Windows, C-Startup
