### ISSUE TITLE
The lifetime of Events seems to have changed in 0.12

### ISSUE THREAD

**Issue by MJohnson459** [bevyengine/bevy#11026] opened 2023-12-19 14:40 UTC
## Bevy version

0.12.1

## What you did

I just upgraded to 0.12.1 and I noticed that this code no longer works for panning the camera with a mouse drag:
```rust
fn pan_camera(
    mut ev_motion: EventReader<MouseMotion>,
    input_mouse: Res<Input<MouseButton>>,
) {
...
    if input_mouse.pressed(pan_button) {
        for ev in ev_motion.read() {
            pan += ev.delta;
        }
    }
```

Previously the `ev_motion` reader would only contain events from the last frame. Now it seems that there is a backlog of events stored and so clicking the mouse results in a large pan happening.

I believe previously bevy used to only store the delta for [two frames](https://bevy-cheatbook.github.io/programming/events.html#how-it-all-works) but now it is unbounded? I didn't see anything in the release or migration notes about this but I am guessing it might be related to https://github.com/bevyengine/bevy/pull/7728 (@james7132 )?

The workaround for now is to just clean the events every frame. This will fix the symptoms for one system but doesn't fix the underlying change which has implications for memory usage etc.
```rust
    if input_mouse.pressed(pan_button) {
        for ev in ev_motion.read() {
            pan += ev.delta;
        }
    } else {
        ev_motion.clear();
    }
```

**Comment by mockersf** [comment] 2023-12-19 23:00
seems related to https://github.com/bevyengine/bevy/issues/10877

**Comment by alice-i-cecile** [comment] 2023-12-21 14:32
Closing as duplicate.

**Closed by alice-i-cecile** 2023-12-21 14:32 UTC
Labels: C-Bug, A-ECS

**Comment by james7132** [comment] 2024-02-09 22:55
> I believe previously bevy used to only store the delta for [two frames](https://bevy-cheatbook.github.io/programming/events.html#how-it-all-works) but now it is unbounded? I didn't see anything in the release or migration notes about this but I am guessing it might be related to https://github.com/bevyengine/bevy/pull/7728 (@james7132 )?

#7728 will only stop running the update if *both* internal stores are empty. I don't think this is the cause of this issue.
