### ISSUE TITLE
code panicked due to a bug

### ISSUE THREAD

**Issue by RK33DV** [bevyengine/bevy#5412] opened 2022-07-21 07:22 UTC
## Bevy version

0.7

## \[Optional\] Relevant system information

If you cannot get Bevy to build or run on your machine, please include:

- cargo 1.62.1 (a748cf5a3 2022-06-08)
- the operating system or browser used, including its version
  - windows 10

If your bug is rendering-related, copy the adapter info that appears when you run Bevy.

```ignore
`not a rendering issue}`
```

You should also consider testing the examples of our upstream dependencies to help isolate any setup-specific issue:

- [`wgpu`](https://github.com/gfx-rs/wgpu) for rendering problems
- [`winit`](https://github.com/rust-windowing/winit) for input and window management
- [`gilrs`](https://docs.rs/gilrs/latest/gilrs/) for gamepad inputs

## What you did

was learning bevy 2d, just drawing a sprite on the screen
code : https://pastebin.com/nUsy96iq

## What went wrong
```
`
Compiling projectname v0.1.0 (drive:\folder\folder\projectfolder\projectname) Finished dev [unoptimized + debuginfo] target(s) in 48.03s Running `target\debug\fckyusjd.exe` 2022-07-20T14:54:34.761906Z INFO bevy_render::renderer: AdapterInfo { name: "Microsoft Basic Render Driver", vendor: 5140, device: 140, device_type: Cpu, backend: Dx12 } thread 'main' panicked at 'view entity should exist: QueryDoesNotMatch(0v0)', C:\Users\usernamde\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_core_pipeline-0.7.0\src\main_pass_2d.rs:45:14 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace error: process didn't exit successfully: `target\debug\fckyusjd.exe` (exit code: 101)`

```
code panicked in the line 45 of this file https://github.com/bevyengine/bevy/blob/v0.7.0/crates/bevy_core_pipeline/src/main_pass_2d.rs
it appers to be a bevy bug, the expect() method is used, which i think is used when the dev knows that it will never fail, so if it does, its a bug

**Comment by DJMcNab** [comment] 2022-07-21 08:01
Can you reproduce this on main? This appears to be a duplicate of https://github.com/bevyengine/bevy/issues/5412

**Closed** 2022-07-21 08:03 UTC
Labels: C-Bug, S-Duplicate, A-Rendering
