### ISSUE TITLE
Failed to parse shader SPIR-V code Warning

### ISSUE THREAD

**Issue by MinerSebas** [bevyengine/bevy#860] opened 2020-11-13 13:15 UTC
**Bevy version**

43aac1a78480e196f9b8b29339a34d78bc44b663

**Operating system & version**

Windows 10 64bit

**What you did**

Ran the command `cargo run --example ui`

**What you expected to happen**

No warnings in the Console.

**What actually happened**

The console shows this: 
```
Nov 13 13:59:10.247  WARN wgpu_core::device: Failed to parse shader SPIR-V code: UnsupportedBuiltIn(4)
Nov 13 13:59:10.248  WARN wgpu_core::device: Shader module will not be validated
Nov 13 13:59:10.445  WARN wgpu_core::device: Failed to parse shader SPIR-V code: UnsupportedBuiltIn(4)
Nov 13 13:59:10.445  WARN wgpu_core::device: Shader module will not be validated
Nov 13 13:59:10.612  WARN wgpu_core::device: Failed to parse shader SPIR-V code: UnsupportedBuiltIn(4)
Nov 13 13:59:10.613  WARN wgpu_core::device: Shader module will not be validated
```
Though, the Example itslef isn't broken.

**Additional information**
The warnings also appear for other Examples, but here the Examples themselves also work correctly.

Bisceting the Repo, these Warnings appeared after the Merge of #836

**Comment by karroffel** [comment] 2020-11-13 17:56
Thanks for the report! Nice that you did a bisect too, unfortunately that PR just adds logging, meaning that the underlying issue probably has been there for longer and was caused by another commit.

**Comment by cart** [comment] 2020-11-13 22:00
Yup its definitely a result of the new logging / these warnings have been silently there for awhile. I'm planning on trying to address the warnings (if possible) and if thats not possible (because its a result of wgpu's still-in-progress naga shader validation) I might suppress wgpu warnings until naga validation has full coverage.

**Comment by RedlineTriad** [comment] 2021-05-02 11:34
This doesn't seem to be an issue anymore:
```
❯ cargo run --example ui
    Finished dev [unoptimized + debuginfo] target(s) in 0.09s
     Running `target/debug/examples/ui`

bevy on  main [!] is 📦 v0.5.0 via 🦀 v1.51.0 took 2s 
❯ 
```
but I don't know which commit fixed it.

**Comment by alice-i-cecile** [comment] 2021-05-02 18:04
Closing as resolved <3

**Closed by alice-i-cecile** 2021-05-02 18:04 UTC
Labels: bug, rendering
