### ISSUE TITLE
The compiler complains that the WorldQuery trait isn't implemented when using the WithBundle<> filter

### ISSUE THREAD

**Issue by TheSylex** [bevyengine/bevy#2616] opened 2021-08-07 04:07 UTC
## Bevy version

Release 0.5.0

## Operating system & version

Windows 11

## What you did

Simply create a function with a query that uses the WithBundle<> filter, for example:
```
pub fn example_withbundle_error(
    mut example_query: Query<Entity, WithBundle<SpriteBundle>>
) {

}
```

## What you expected to happen

The compiler shouldn't complain for using the WithBundle<> filter

## What actually happened

The compiler complains that I cannot use the filter because the WorldQuery trait isn't implemented:
> the trait bound `WithBundle<bevy::prelude::SpriteBundle>: WorldQuery` is not satisfied
> the trait `WorldQuery` is not implemented for `WithBundle<bevy::prelude::SpriteBundle>` (rustc E0277)

**Comment by DJMcNab** [comment] 2021-08-07 06:16
Duplicate of https://github.com/bevyengine/bevy/pull/2024

**Closed** 2021-08-07 06:17 UTC
Labels: C-Bug, S-Duplicate, A-ECS
