### ISSUE TITLE
Creating a bundle complains about mem::forget

### ISSUE THREAD

**Issue by SUPERCILEX** [bevyengine/bevy#4601] opened 2022-04-26 01:26 UTC
## Bevy version

0.7.0

## What you did

```rust
#[derive(Component, Default)]
pub struct NominoMarker;

#[derive(Component, Deref)]
pub struct BoundingBoxes(&'static [Rect<f32>]);

#[derive(Bundle)]
pub struct NominoBundle {
    #[bundle]
    shape: bevy_prototype_lyon::entity::ShapeBundle,
    bounding_boxes: BoundingBoxes,
    _marker: NominoMarker,
}
```

## What you expected to happen

No warnings

## What actually happened

```
warning: call to `std::mem::forget` with a value that does not implement `Drop`. Forgetting such a type is the same as dropping it
   --> src/nominos.rs:106:10
    |
106 | #[derive(Bundle)]
    |          ^^^^^^
    |
    = note: `#[warn(clippy::forget_non_drop)]` on by default
note: argument has type `nominos::BoundingBoxes`
   --> src/nominos.rs:106:10
    |
106 | #[derive(Bundle)]
    |          ^^^^^^
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#forget_non_drop
    = note: this warning originates in the derive macro `Bundle` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by alice-i-cecile** [comment] 2022-04-26 01:29
Are you on Rust nightly? Can you reproduce this with a simpler bundle?

**Comment by SUPERCILEX** [comment] 2022-04-26 02:05
Yeah: `rustc 1.62.0-nightly (4ca19e09d 2022-04-19)`. Simpler:
```rust
#[derive(Component, Default)]
pub struct NominoMarker;

#[derive(Bundle)]
pub struct TestBundle {
    _marker: NominoMarker,
}
```

**Comment by DJMcNab** [comment] 2022-04-26 06:05
The `std::mem::forget` version of the bundle code is slightly suspect anyway; we need to migrate it to `MaybeUninit` (maybe `ManuallyDrop` is sufficient). (I suspect there are at least 2 open PRs which make this change.)

A temporary workaround is just to allow that lint for your entire crate.

**Comment by SUPERCILEX** [comment] 2022-04-26 22:29
Seems like these two: https://github.com/bevyengine/bevy/pull/3634 and https://github.com/bevyengine/bevy/pull/2975

**Comment by alice-i-cecile** [comment] 2022-05-01 20:49
Running into this on nightly too for my own projects, which breaks my clippy-checking CI. For those looking for a workaround, add `#![allow(clippy::forget_non_drop)]` to the top of your `main.rs` to silence the warning for now.

**Comment by KDecay** [comment] 2022-07-25 04:43
This problem seems to be fixed in `main` by https://github.com/bevyengine/bevy/pull/3001 because of the removal of the `std::mem::forget` call in `bevy_ecs/src/bundle.rs` (see https://github.com/bevyengine/bevy/pull/3001/files#diff-0e94997025571f709abd7cac97f03bb4e8ec8bf29650068a7e5ec07170011892L121-R126).

This code generates a warning when running `cargo clippy` with  `bevy 0.7`but doesn't in `bevy main`:

```rust
use bevy::prelude::*;

#[derive(Bundle)]
pub struct Foo {
    bar: Bar,
}

#[derive(Component)]
struct Bar;

fn main() {}
```

**Closed** 2022-07-25 05:37 UTC
Labels: A-ECS, C-Code-Quality
