### ISSUE TITLE
derive(SystemParam) fails when generic over P: SystemParam

### ISSUE THREAD

**Issue by SamPruden** [bevyengine/bevy#4783] opened 2022-05-17 13:34 UTC
## Bevy version

0.7 and master.

## What you did
```rust
#[derive(SystemParam)]
struct GenericParam<'w, 's, P: SystemParam + 'static> {
  // This breaks
  param: P,

  // Yuck, but #2711
  #[system_param(ignore)]
  _marker: PhantomData<(&'w(), &'s())>
}
```

## What you expected to happen

This should work. The docs claim:
> This trait can be derived with the [super::SystemParam](https://docs.rs/bevy/latest/bevy/ecs/system/derive.SystemParam.html) macro. The only requirement is that every struct field must also implement SystemParam.

This meets that requirement.

## What actually happened
This doesn't compile on either 0.7 or master.

Master:
```
 9 | #[derive(SystemParam)]
   |          ^^^^^^^^^^^ expected type parameter `P`, found associated type
10 | struct GenericParam<'w, 's, P: SystemParam + 'static> {
   |                             - this type parameter
   |
   = note: expected type parameter `P`
              found associated type `<<P as SystemParam>::Fetch as SystemParamFetch<'_, '_>>::Item`
```

## Additional information
Running `cargo expand` let's us track this down a little. This is the version from master.

<details>
  <summary>Long code hidden.</summary>
  
```rust
use std::marker::PhantomData;

use bevy::ecs::{
  archetype::Archetype,
  system::{ReadOnlySystemParamFetch, SystemMeta, SystemParam, SystemParamFetch, SystemParamState},
  world::World,
};

struct GenericParam<'w, 's, P: SystemParam + 'static> {
  param: P,
  _marker: PhantomData<(&'w (), &'s ())>,
}

const _: () = {
  impl<'w, 's, P: SystemParam + 'static> SystemParam for GenericParam<'w, 's, P> {
    type Fetch = FetchState<(<P as SystemParam>::Fetch,), P>;
  }

  #[doc(hidden)]
  struct FetchState<TSystemParamState, P> {
    state: TSystemParamState,
    marker: PhantomData<fn() -> (P)>,
  }

  unsafe impl<TSystemParamState: SystemParamState, P: SystemParam + 'static> SystemParamState
    for FetchState<TSystemParamState, P>
  {
    fn init(world: &mut World, system_meta: &mut SystemMeta) -> Self {
      Self {
        state: TSystemParamState::init(world, system_meta),
        marker: PhantomData,
      }
    }

    fn new_archetype(&mut self, archetype: &Archetype, system_meta: &mut SystemMeta) {
      self.state.new_archetype(archetype, system_meta)
    }

    fn apply(&mut self, world: &mut World) {
      self.state.apply(world)
    }
  }

  impl<'w, 's, P: SystemParam + 'static> SystemParamFetch<'w, 's>
    for FetchState<(<P as SystemParam>::Fetch,), P>
  {
    type Item = GenericParam<'w, 's, P>;

    unsafe fn get_param(
      state: &'s mut Self,
      system_meta: &SystemMeta,
      world: &'w World,
      change_tick: u32,
    ) -> Self::Item {
      GenericParam {
        param: <<P as SystemParam>::Fetch as SystemParamFetch>::get_param(
          &mut state.state.0,
          system_meta,
          world,
          change_tick,
        ),
        _marker: <PhantomData<(&'w (), &'s ())>>::default(),
      }
    }
  }

  unsafe impl<TSystemParamState: SystemParamState + ReadOnlySystemParamFetch, P: SystemParam + 'static>
    ReadOnlySystemParamFetch for FetchState<TSystemParamState, P>
  {
  }
};
```
</details>

```
45 |     impl<'w, 's, P: SystemParam + 'static> SystemParamFetch<'w, 's>
   |                  - this type parameter
...
57 |           param: <<P as SystemParam>::Fetch as SystemParamFetch>::get_param(      
   |  ________________^
58 | |           &mut state.state.0,
59 | |           system_meta,
60 | |           world,
61 | |           change_tick,
62 | |         ),
   | |_________^ expected type parameter `P`, found associated type
   |
   = note: expected type parameter `P`
             found associated type `<<P as SystemParam>::Fetch as SystemParamFetch<'_, 
'_>>::Item`
```

I've had a little go at manually patching the expanded code to work, but haven't managed it yet. I think `P` and `<<P as SystemParam>::Fetch as SystemParamFetch<'_, 
'_>>::Item` actually are equal, but the compiler isn't working that out. But don't quote me on that. Perhaps somebody more experianced with tricky Rust types than I am can work out the fix here.

**Comment by DJMcNab** [comment] 2022-05-17 14:35
Duplicate of https://github.com/bevyengine/bevy/issues/3300

But you're right, we should point to [`StaticSystemParam`](https://docs.rs/bevy/latest/bevy/ecs/system/struct.StaticSystemParam.html) in the docs for [`SystemParam`](https://docs.rs/bevy/latest/bevy/ecs/system/trait.SystemParam.html).

**Comment by DJMcNab** [comment] 2022-05-17 14:48
Hmm, I don't think we can reasonably detect this, unfortunately.

Or well, we could add a heuristic for just using a generic argument as one of the fields, but we can't do any better for:
```rust
type Identity<P> = P;
#[derive(SystemParam)]
struct GenericParam<'w, 's, P: SystemParam + 'static> {
  // This breaks
  param: Identity<P>,

  // Yuck, but #2711
  #[system_param(ignore)]
  _marker: PhantomData<(&'w(), &'s())>
}
```

I'm hesistant to special case too much diagnostics into our derives, since the code already requires a lot of bookkeeping.

**Comment by SamPruden** [comment] 2022-05-17 14:57
You make a strong argument, but it's a shame that the error message when getting this wrong is so inscrutable. I can't see any way to improve that.

This is obviously out of scope and off topic, but it's also a shame that Rust's procedural macro system is so weak in this regard. I'm spoiled by C#'s Anaylyzers giving me full access to the compiler state (including all type information, data flow, etc) for use in custom diagnostics.

**Closed** 2022-05-17 22:37 UTC
Labels: C-Bug, C-Docs, S-Duplicate, A-ECS
