### ISSUE TITLE
Run bevy_ecs in miri on CI

### ISSUE THREAD

**Issue by bjorn3** [bevyengine/bevy#1529] opened 2021-02-27 14:29 UTC
## What problem does this solve or what need does it fill?

Bevy_ecs contains a lot of unsafe code. Unsafe code in Bevy has been proven to be unsound on multiple occasions.

## What solution would you like?

Run the bevy_ecs test suite in miri to detect UB. Preferably miri would also manually be run on #1525 before it is merged.

## What alternative(s) have you considered?

<dl>
<dt>Remove all unsafe code.</dt>
<dd>Will regress performance by a lot.</dd>
<dt>Formally verify all unsafe code.</dt>
<dd>Way too much work.</dd>
<dt>Manually verify all unsafe code.</dt>
<dd>Takes a lot of time and will miss some unsoundness.</dd>
</dl>

**Comment by cart** [comment] 2021-02-27 18:38
Makes sense to me! Given that miri is pretty slow and the change frequency of bevy_ecs internals is also low, I'm thinking this should probably be a periodic test (daily?). I ran miri prior to creating #1525. I'll do it again before merging.

On `main` (and #1525), the parallel executor's async-channel usage fails with:
![image](https://user-images.githubusercontent.com/2694663/109396574-25aff880-78e7-11eb-8165-be55520c6f31.png)

A few days ago I also ran miri on the async-channel crate's tests, which passed. So it's unclear if this is a bevy-call-context issue that exposes a problem in async-channel, a bevy issue, or a miri bug (the error says the rule is experimental).

Additionally, if the test above is commented out, miri has an internal compiler error on another test (which seems to be an indicator that bevy's Future code can't be tested by miri yet):
![image](https://user-images.githubusercontent.com/2694663/109396664-82abae80-78e7-11eb-96e9-3f3b49f6ac75.png)

**Comment by bjorn3** [comment] 2021-02-27 19:20
Could you report an issue on rust-lang/rust for the ICE?

**Comment by cart** [comment] 2021-02-27 20:02
Sure thing!

**Comment by cart** [comment] 2021-02-27 20:06
Looks like a dupe of https://github.com/rust-lang/miri/issues/1038

**Comment by RalfJung** [comment] 2022-03-20 18:39
https://github.com/rust-lang/miri/issues/1038  is fixed now, btw. :)
Once https://github.com/rust-lang/rust/pull/95144 lands, this will be in the next nightly.

**Closed** 2022-03-25 00:47 UTC
Labels: A-ECS, A-Build-System, C-Code-Quality
