### ISSUE TITLE
Premature dropping of asset handles stored in components

### ISSUE THREAD

**Issue by viridia** [bevyengine/bevy#9501] opened 2023-08-19 19:48 UTC
## Bevy version

0.11.0, 0.11.1, and 0.11.2

## What you did

I'm loading a labeled asset from a custom asset loader, and storing the handle in a component. The handle is generated via `load()` so I'm assuming that's a strong handle.

Actually, the scenario is a bit more complex: the asset is an XML file that contains both templates and styles, where each template and each style is a labeled asset. (There is no default asset). There's a system that loads a template and creates a view element tree; there's another system that loads the styles, and stores the resulting asset handles in components that are associated with the view element entities.

There are additional systems that process the loaded styles and update the scene graph.

## What went wrong

The system as I have described is highly non-deterministic, and frequently fails to load styles. I can see this in a number of ways:

* Polling the status of a style handle often returns "Unloaded".
* Listening to asset events, I sometimes get "Removed" events for the stylesheets.

Neither of these things should be happening, since I never release or drop any of the asset handles. That is, the assets should never be in a state of "unloaded".

One thing I have observed is that putting "apply_deferred" immediately after the system that creates the asset handles reduces the occurrence of the problems (by a large amount), but does not entirely make them go away.

My conclusion is that there is some kind of race condition caused by the fact that the components containing the asset handles are not immediately inserted into the world. Unfortunately, I don't know enough about the internal details of strong handles to speculate. If strong handles were based on reference-counting, then I can't think of how this could possibly happen. OTOH, if they are based on mark-and-sweep, then it's possible that the command queue is not being considered as a GC root.

It's possible that I am doing something wrong, or that I don't completely understand the "rules of handles". I should note that when I store the handle into the component I am explicitly calling "handle.clone()".

**Comment by alice-i-cecile** [comment] 2023-08-19 22:22
A reproduction, whether minimal or not, would be really helpful for further investigation.

**Comment by alice-i-cecile** [comment] 2023-08-19 22:24
My initial hypothesis is that:

1. Assets are initialized into loading.
2. The strong handle is created by cloning.
3. The system ends.
4. The asset finishes loading.
5. The commands are applied.

If asset handles aren't being kept alive in commands then it would match the behavior you're seeing. Can you reproduce this if you swap to an exclusive system?

**Comment by viridia** [comment] 2023-08-19 23:27
> A reproduction, whether minimal or not, would be really helpful for further investigation.

All right, I'll spend some time on this. Note that even a minimal example is likely to be non-deterministic, so you may need to run it multiple times.

**Comment by viridia** [comment] 2023-08-20 00:53
OK so here's what I have - it's not minimal, but it can point you to where the problems are happening. (I haven't tried the exclusive system thing yet).

Code is on a branch: https://github.com/viridia/panoply/tree/asset-loading-bug

You should only need to `cargo run`.

The main action happens in `src/guise/view.rs`. The system that loads the templates is `create_views`.

There are two systems that poll for style resources, one which uses asset events (`update_view_styles`), and one which uses change events on the component containing the style handle: (`update_view_styles_poll`). The reason for having two listeners is that I don't know which one will fire: the event-based one only fires the first time the asset is loaded, so any additional components that depend on that asset which are created after the asset is loaded need to use the other one. The second listener will poll until it finds the asset, but can't detect a hot replacement. (I wish there was a simpler approach - for example, if the asset event was per-handle rather than per-asset, so that even if an asset is already in memory it generates a load event for a newly-created handle.)

The log output will vary from one run to the next, but you should see one of the following two messages:

```
Updating node 'test-button' style handle status: 'Unloaded'
```
This is produced by the code that is polling based on a marker component.

```
2023-08-20T00:48:22.308844Z  WARN panoply::guise::view: Asset Removed: Template AssetPath { path: "editor/ui/test.guise.xml", label: Some("button") }
```
This line is produced by the listener that is checking for asset events, it means that it saw a "removed" event.

**Comment by viridia** [comment] 2023-08-20 17:59
I tried making the system exclusive, and while it did run, it introduced other anomalies which makes it unsuitable as a reproducible example. I'm going to try and come up with a simpler example case, expect something in a day or two.

**Comment by viridia** [comment] 2023-08-20 18:52
Actually, I have two additional questions:

1) Are we sure that `AssetServer.load()` produces a strong handle? The documentation doesn't say.

2) Would it make sense to hold off on debugging this until Asset V2 lands? I know handles are being significantly reworked. Once V2 stabilizes a bit more I can migrate my work to it.

**Comment by alice-i-cecile** [comment] 2023-08-20 19:18
I'm reasonably confident it does, but not 100% sure.

If this isn't urgent for you, I'd definitely encourage waiting until after Assets v2 to see if you can still reproduce.

**Comment by viridia** [comment] 2023-08-20 22:54
Urgent? Well, I don't have a deadline, but it's definitely a blocker for the work I am doing. I might try and see if I can come up with a temporary workaround - like storing a copy of all the handles in a resource or something.

**Comment by viridia** [comment] 2023-08-21 06:00
I've whittled down the reproduction case by about 80%. More importantly, I've removed a lot of the complexity and indirection in the code that polls asset handles, so that part should be quite a bit easier to read.

The code is now in a GH repo of its own:

https://github.com/viridia/bevy-asset-unload

Running the program produces one of two different log streams, both of which are wrong, depending on a race condition. It depends on which of the two polling systems gets run first - the one that listens for asset events, or the one that just checks the load state directly. In either case, you'll get a log output saying that the resource is in an unloaded state, which should not happen since we never drop the handles.

**Comment by viridia** [comment] 2023-08-22 07:56
I also want to mention a number of potential red herrings. By this, I mean there are some alternate hypotheses as to why this might be happening, and I want to enumerate these up front so as to avoid having you waste your time.

The first has to do with the fact that the asset loader is fairly complex and doesn't resemble the typical asset loader. It's reading an XML file, and it's using an event-based reader (not serde, for reasons I won't go into), and it is inserting the labeled assets during the traversal. Also, there's no default asset, only labeled ones. So the hypothesis is that some quirk of the asset loader is causing this behavior.

However, I don't think any of this is relevant, because asset loaders don't "commit" their results until processing is finished - in other words, the loading of a complex asset is still "atomic" as far as the rest of the world is concerned.

A counter-argument to this is the fact that the asset loader is being invoked twice. That is, if you place a println() call in `visit`, you'll see two printed log lines. This should not happen, because the asset should be cached the first time it is loaded, there should be no need to deserialize it a second time.

The second red herring has to do with the way that my handles are stored: there's a "root" component which contains a handle to a "root" asset (the template) - this entity is the root of a tree which has children, each of which also contains an asset handle that points to a different labeled asset (the stylesheet) loaded from the same file. The tree is not built until the root asset has finished loading, so there are multiple phases of construction, each managed by a different system. So the alternate hypothesis is that there's some bug in the way that assets handles are being managed.

Again, I don't think this is the case. The fact that a handle even exists provides some strong guarantees, regardless of how or where it is stored, and it seems like those guarantees are being violated. But, I could be wrong...

**Comment by mockersf** [comment] 2023-08-22 12:08
with a very quick look at your code, it seems you're trying to load the asset with label `main`, but not such label is created. so it loads everything, and then unloads because you're holding an handle to an asset that doesn't exists

**Comment by viridia** [comment] 2023-08-22 16:13
Correct. The template handle seems to work correctly, the style handles get unloaded. But neither should be unloaded, as I am keeping around both kinds of handles, stored within components.

If I understand correctly, a strong handle should never report a status of "unloaded", because the fact that the strong handle even exists should prevent the asset from becoming unloaded. (This invariant does not apply to the handle you get from an asset event reader.)

One thing you can play around with is commenting out the calls to `apply_deferred` within src/guise/plugin.rs. This was an attempt to work around the problem, but should not be needed.

**Comment by mockersf** [comment] 2023-08-22 16:32
It looks like you're hitting a known bug https://github.com/bevyengine/bevy/issues/9337

For `Style`, you're actually not holding strong handles from the first time the asset is loaded, but reloading them when you receive an handle for a `Template`. So you load the file, the templates are kept around because you have a strong handle but the styles are unloaded as you don't, then you try to reload the styles after receiving the event for the template, and that's where you're hitting that bug. You can either keep the handles from the first load, or wait for https://github.com/bevyengine/bevy/pull/8624

**Comment by viridia** [comment] 2023-08-22 16:44
Oh, interesting. That does explain it. It also explains why the asset loader is being called twice.

I kind of assumed that the caching was happening on a per-file, not a per-asset level: that is, when I load a catalog of assets, I want to keep around the entire catalog in memory because I plan on accessing multiple assets within the next few frames.

So it sounds like what I need to do is figure out how to iterate through all of the assets in the file and store those in the ViewRoot.

I wonder if it would make sense to add a feature to the asset server to optionally indicate that a bunch of assets from the same file should be cached as a group? I don't know how complicated that would be, but it might make sense for other kinds of "atlas" assets.

**Comment by alice-i-cecile** [comment] 2023-08-22 18:57
This was really helpful investigation, thank you both. Let's close this as a duplicate.

**Closed by alice-i-cecile** 2023-08-22 18:57 UTC
Labels: C-Bug, A-Assets, S-Needs-Investigation

**Comment by viridia** [comment] 2023-08-23 02:25
@mockersf @alice-i-cecile I just have one follow up question, which is - what can I use as a temporary workaround? All of the approaches I have tried do not work.

For example, it has been suggested that I load all of the stylesheet assets at the same time as the template - but there's no way to do this. I don't know what the style asset paths are until I load the template, and this cannot be done synchronously. Similarly, there's no way to iterate through all of the asset paths until at least one asset is loaded.

I also tried to modify the asset loader code to add all of the stylesheets as "dependent assets" to the template asset while parsing the file. I figured that this would force them to stay in memory and not be unloaded. Unfortunately, this doesn't get past the bug - the stylesheets still have a status of "Unloaded" on the next frame.

I've also played around with storing the asset handle in a resource. No dice. The problem is not about how I am storing the handle, it's the sequence of loading a bunch of assets coming from the same file but spread out in time.

I'm out of ideas at this point.

**Comment by alice-i-cecile** [comment] 2023-08-24 01:43
When dealing with similar "staged asset loading" problems in the past, I've found using `States` and a "poll until ready, then advance" quite effective, if tedious. I'm not entirely sure the best way to do that if they *share* a file though: you may need to construct a dependency graph by parsing the file, and then block until all dependents are loaded.

**Comment by mockersf** [comment] 2023-08-24 06:52
Have your asset loader create a "meta" asset, something like
```
struct Meta {
    templates: HashMap<String, Handle<Template>>,
    styles: HashMap<String, Handle<Style>>,
}
```
And load it and keep a reference to it in something like a resource. Then either load your labelled assets from file, they should stay alive as you will keep a strong handle to everything, or get the handles from that resource.
