### ISSUE TITLE
SystemParam with only ignored parameters

### ISSUE THREAD

**Issue by CGMossa** [bevyengine/bevy#2125] opened 2021-05-06 21:09 UTC
I wanted to add a system parameter that contains to fields that should not be part of the ECS.
The `SystemParam`-macro has an option to mark fields as `#[system_param(ignore)]` to do this.

But then the `SystemParam` requires a lifetime. Find, so I got a tip that the equivalent to
`PhantomData` but for lifetimes is `PhantomData<&'a ()>`, e.g.

```rust
#[derive(SystemParam)]
pub struct ActiveSurveillance<'a> {
    _secret: PhantomData<&'a ()>,
    #[system_param(ignore)]
    detection_rate: f64,
}
```

Anyways, this doesn't work at all:

```rust
error[E0277]: the trait bound `PhantomData<&'a ()>: SystemParam` is not satisfied
  --> src\regulator_active_surveillance.rs:19:10
   |
19 | #[derive(SystemParam)]
   |          ^^^^^^^^^^^ the trait `SystemParam` is not implemented for `PhantomData<&'a ()>`
   |
```

So anyways, anyone got a tip for this?

By the way, I still think that `SytemParam` from `bevy::ecs::system` should be included in the `prelude`-module.

**Comment by mockersf** [comment] 2021-05-06 21:15
didn't try, but the `#[system_param(ignore)]` go over the param to ignore, not under

**Comment by alice-i-cecile** [comment] 2021-12-12 22:36
The following snippet fails:

```rust
use bevy::ecs::system::SystemParam;
use std::marker::PhantomData;

fn main() {}

#[derive(SystemParam)]
pub struct ActiveSurveillance<'a> {
    #[system_param(ignore)]
    _secret: PhantomData<&'a ()>,
    #[system_param(ignore)]
    detection_rate: f64,
}
```

The errors are:

> use of undeclared lifetime name `'w`
> use of undeclared lifetime name `'s`

**Comment by alice-i-cecile** [comment] 2021-12-12 22:37
Closing as a duplicate of #2711 now that it's been reproduced and investigated.

**Closed by alice-i-cecile** 2021-12-12 22:37 UTC
Labels: C-Enhancement, A-ECS, S-Needs-Investigation
