### ISSUE TITLE
Methods on `Entity` should be `const`

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#6548] opened 2022-11-11 16:23 UTC
These [methods](https://docs.rs/bevy/latest/bevy/ecs/entity/struct.Entity.html#method.from_bits) are useful for tests, but are not `const`.

This makes it harder to create dummy entities to use to populate data structures.

**Comment by james7132** [comment] 2022-11-12 15:21
This seems to be a duplicate of #5687, which was resolved in #5688, but `Entity::to_bits` was the only remaining method that wasn't changed to be `const`.

**Closed** 2022-11-12 16:33 UTC
Labels: D-Good-First-Issue, A-ECS, C-Usability, C-Testing
