### ISSUE TITLE
Converting Color from Hsla to Rgba (and vice versa) produce the wrong channel values

### ISSUE THREAD

**Issue by thmxv** [bevyengine/bevy#8838] opened 2023-06-14 02:46 UTC
## Bevy version

0.10.1

## What you did

Using `Color::hsl(0.0, 1.0, 1.0).as_rgba()` returns white 

## What went wrong

I would expect to be red. The issue is the same for any hue. 

## Additional information

Converting a `Color::Rgba` to `Color::Hsla` and back yields the correct results, so I suspect the bug might be replicated simetricaly somehow.

Using `Color::hsl(0.0, 1.0, 0.5).as_rgba()` (note the 0.5 in place of the 1.0 for the lightness) produce the result I was expecting with a lightness of 1.0.

This seem to also affects the conversions to/from `Color::RgbaLinear`.

**Comment by helvieq499** [comment] 2023-06-14 03:27
This probably is not a bug
In HSL, 100% lightness is meant to be completely white
In HSV, 100% value is the pure red you expected

**Comment by thmxv** [comment] 2023-06-14 03:33
OK, that make sense, an inattention mistake of me. Sorry for that, and thank you very much.

**Comment by helvieq499** [comment] 2023-06-14 03:35
There is no HSV version in the Color struct and the documentation does not specify the impact of lightness.
Those changes may be helpful to prevent confusion from other users in the future.

**Comment by alice-i-cecile** [comment] 2024-02-29 20:13
This should be fixed now, with the addition of bevy_color.

**Closed by alice-i-cecile** 2024-02-29 20:13 UTC
Labels: C-Bug, A-Rendering
