### ISSUE TITLE
game_menu example took 93% of cpu

### ISSUE THREAD

**Issue by adals** [bevyengine/bevy#13314] opened 2024-05-10 14:12 UTC
## Bevy version

main branch

## OS version
Apple M1 Max
macos sonoma 14.4.1 (23E224)

## What you did

cargo run --example game_menu

## What went wrong

when clicking close it did not respond and it took 5-10 seconds to close and it took 93% of cpu

![Screenshot 2024-05-10 at 5 07 07 PM](https://github.com/bevyengine/bevy/assets/169691/84dab205-7d2a-48b1-a10e-9fee52acb290)

**Comment by alice-i-cecile** [comment] 2024-05-10 14:13
What OS are you on?

**Comment by mockersf** [comment] 2024-05-10 14:53
probably related to https://github.com/bevyengine/bevy/issues/13208

**Comment by adals** [comment] 2024-05-10 16:37
> probably related to #13208

FYI even if I did not touch close button it took around 93% of cpu

**Comment by JMS55** [comment] 2024-05-10 16:46
Try running in release mode.

**Comment by adals** [comment] 2024-05-10 17:04
> Try running in release mode.

it decreased to 50% of cpu and also hang after pressing close button

**Comment by adals** [comment] 2024-06-07 14:27
FYI hello-triangle wgpu example. maybe it could help
 
![Screenshot 2024-06-07 at 5 23 47 PM](https://github.com/bevyengine/bevy/assets/169691/b508dfb4-92e3-462f-b353-cda8f5c34bba)

**Comment by alice-i-cecile** [comment] 2024-06-07 20:46
Closing as a duplicate of #10261. That *was* very helpful :)

**Closed by alice-i-cecile** 2024-06-07 20:46 UTC
Labels: C-Bug, C-Performance, A-UI, S-Needs-Investigation
