### ISSUE TITLE
Doctests for bevy_gizmos run for too long

### ISSUE THREAD

**Issue by doonv** [bevyengine/bevy#11034] opened 2023-12-20 14:15 UTC
## Bevy version

https://github.com/bevyengine/bevy/commit/dc8fc6cb34d6064530c698f30445cd69d1c79682 (Latest as of writing)

## \[Optional\] Relevant system information

- Rust Version: `rustc 1.74.1 (a28077b28 2023-12-04)`
- System Info:
  > Operating System: Kubuntu 23.10
  > KDE Plasma Version: 5.27.8
  > KDE Frameworks Version: 5.110.0
  > Qt Version: 5.15.10
  > Kernel Version: 6.5.0-14-generic (64-bit)
  > Graphics Platform: X11
  > Processors: 16 × 13th Gen Intel® Core™ i5-13400
  > Memory: 15.4 GiB of RAM
  > Graphics Processor: NVIDIA GeForce RTX 3060/PCIe/SSE2
  > Manufacturer: Gigabyte Technology Co., Ltd.
  > Product Name: B760M DS3H AX DDR4

## What you did

Running `cargo test --doc` on `bevy_gizmos` 

## What went wrong

The doctests are extremely long. Lasting for over 60 seconds. It appears running `assert_is_system` on a system with `Gizmos` causes massive lag. Removing `assert_is_system` makes the tests run much quicker.
```rs
# use bevy_gizmos::prelude::*;
# use bevy_render::prelude::*;
# use bevy_math::prelude::*;
# use std::f32::consts::PI;
fn system(mut gizmos: Gizmos) {
    gizmos.arc_2d(Vec2::ZERO, 0., PI / 4., 1., Color::GREEN);

    // Arcs have 32 line-segments by default.
    // You may want to increase this for larger arcs.
    gizmos
        .arc_2d(Vec2::ZERO, 0., PI / 4., 5., Color::RED)
        .segments(64);
}
# bevy_ecs::system::assert_is_system(system);
```

## Additional information

I created a project that does a similar test, it ran instantly. Which is weird.

**Comment by doonv** [comment] 2023-12-20 14:31
I was able to reproduce the issue! For some reason its only laggy on doctests. Unit tests work perfectly fine.
```rs
/// ```
/// use bevy::gizmos::gizmos::Gizmos;
/// 
/// fn system(mut _gizmos: Gizmos) {}
/// 
/// bevy::ecs::system::assert_is_system(system);
/// ```
pub struct A;
```
I was able to use a few nightly compiler flags to show the performance of the tests, so here are the benchmarks:
- Doctest, without `assert_is_system`: ~0.55s
- Doctest, with `assert_is_system`: ~2.9s
- Unit test, with/without `assert_is_system`: 0.0s

**Comment by doonv** [comment] 2023-12-20 14:36
Another thing to add: It appears `Gizmos` in particular is much laggier than normal. Other configurations take around ~1.1s to run.

**Comment by doonv** [comment] 2023-12-20 17:18
This appears to also happen in other bevy crates such as `bevy_ui` and `error` for some reason.

**Comment by mockersf** [comment] 2023-12-21 22:05
running those test seems fast enough on my computer:
```
> cargo test --doc -p bevy_gizmos
    Finished test [unoptimized + debuginfo] target(s) in 0.32s
   Doc-tests bevy_gizmos

running 23 tests
test crates/bevy_gizmos/src/gizmos.rs - gizmos::Gizmos<'s>::cuboid (line 266) ... ok
test crates/bevy_gizmos/src/arcs.rs - arcs::Gizmos<'s>::arc_2d (line 25) ... ok
test crates/bevy_gizmos/src/arrows.rs - arrows::Gizmos<'s>::arrow_2d (line 97) ... ok
test crates/bevy_gizmos/src/arrows.rs - arrows::Gizmos<'s>::arrow (line 72) ... ok
test crates/bevy_gizmos/src/gizmos.rs - gizmos::Gizmos<'s>::line_gradient (line 79) ... ok
test crates/bevy_gizmos/src/circles.rs - circles::Gizmos<'s>::circle_2d (line 64) ... ok
test crates/bevy_gizmos/src/circles.rs - circles::Gizmos<'s>::circle (line 26) ... ok
test crates/bevy_gizmos/src/arrows.rs - arrows::ArrowBuilder<'_,'_>::with_tip_length (line 24) ... ok
test crates/bevy_gizmos/src/gizmos.rs - gizmos::Gizmos<'s>::line_2d (line 301) ... ok
test crates/bevy_gizmos/src/gizmos.rs - gizmos::Gizmos<'s>::line (line 59) ... ok
test crates/bevy_gizmos/src/gizmos.rs - gizmos::Gizmos<'s>::linestrip_2d (line 345) ... ok
test crates/bevy_gizmos/src/gizmos.rs - gizmos::Gizmos<'s>::line_gradient_2d (line 320) ... ok
test crates/bevy_gizmos/src/gizmos.rs - gizmos::Gizmos<'s>::linestrip_gradient (line 167) ... ok
test crates/bevy_gizmos/src/gizmos.rs - gizmos::Gizmos<'s>::ray (line 99) ... ok
test crates/bevy_gizmos/src/gizmos.rs - gizmos::Gizmos<'s>::linestrip (line 143) ... ok
test crates/bevy_gizmos/src/gizmos.rs - gizmos::Gizmos<'s>::ray_gradient (line 118) ... ok
test crates/bevy_gizmos/src/gizmos.rs - gizmos::Gizmos<'s>::ray_2d (line 391) ... ok
test crates/bevy_gizmos/src/gizmos.rs - gizmos::Gizmos<'s>::linestrip_gradient_2d (line 364) ... ok
test crates/bevy_gizmos/src/gizmos.rs - gizmos::Gizmos<'s>::ray_gradient_2d (line 410) ... ok
test crates/bevy_gizmos/src/gizmos.rs - gizmos::Gizmos<'s>::rect (line 246) ... ok
test crates/bevy_gizmos/src/gizmos.rs - gizmos::Gizmos<'s>::rect_2d (line 435) ... ok
test crates/bevy_gizmos/src/lib.rs - (line 6) ... ok
test crates/bevy_gizmos/src/gizmos.rs - gizmos::Gizmos<'s>::sphere (line 208) ... ok

test result: ok. 23 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 2.62s
```

**Comment by doonv** [comment] 2023-12-21 22:16
> running those test seems fast enough on my computer:
> 
> ```
> > cargo test --doc -p bevy_gizmos
>     Finished test [unoptimized + debuginfo] target(s) in 0.32s
>    Doc-tests bevy_gizmos
> 
> running 23 tests
> test crates/bevy_gizmos/src/gizmos.rs - gizmos::Gizmos<'s>::cuboid (line 266) ... ok
> test crates/bevy_gizmos/src/arcs.rs - arcs::Gizmos<'s>::arc_2d (line 25) ... ok
> test crates/bevy_gizmos/src/arrows.rs - arrows::Gizmos<'s>::arrow_2d (line 97) ... ok
> test crates/bevy_gizmos/src/arrows.rs - arrows::Gizmos<'s>::arrow (line 72) ... ok
> test crates/bevy_gizmos/src/gizmos.rs - gizmos::Gizmos<'s>::line_gradient (line 79) ... ok
> test crates/bevy_gizmos/src/circles.rs - circles::Gizmos<'s>::circle_2d (line 64) ... ok
> test crates/bevy_gizmos/src/circles.rs - circles::Gizmos<'s>::circle (line 26) ... ok
> test crates/bevy_gizmos/src/arrows.rs - arrows::ArrowBuilder<'_,'_>::with_tip_length (line 24) ... ok
> test crates/bevy_gizmos/src/gizmos.rs - gizmos::Gizmos<'s>::line_2d (line 301) ... ok
> test crates/bevy_gizmos/src/gizmos.rs - gizmos::Gizmos<'s>::line (line 59) ... ok
> test crates/bevy_gizmos/src/gizmos.rs - gizmos::Gizmos<'s>::linestrip_2d (line 345) ... ok
> test crates/bevy_gizmos/src/gizmos.rs - gizmos::Gizmos<'s>::line_gradient_2d (line 320) ... ok
> test crates/bevy_gizmos/src/gizmos.rs - gizmos::Gizmos<'s>::linestrip_gradient (line 167) ... ok
> test crates/bevy_gizmos/src/gizmos.rs - gizmos::Gizmos<'s>::ray (line 99) ... ok
> test crates/bevy_gizmos/src/gizmos.rs - gizmos::Gizmos<'s>::linestrip (line 143) ... ok
> test crates/bevy_gizmos/src/gizmos.rs - gizmos::Gizmos<'s>::ray_gradient (line 118) ... ok
> test crates/bevy_gizmos/src/gizmos.rs - gizmos::Gizmos<'s>::ray_2d (line 391) ... ok
> test crates/bevy_gizmos/src/gizmos.rs - gizmos::Gizmos<'s>::linestrip_gradient_2d (line 364) ... ok
> test crates/bevy_gizmos/src/gizmos.rs - gizmos::Gizmos<'s>::ray_gradient_2d (line 410) ... ok
> test crates/bevy_gizmos/src/gizmos.rs - gizmos::Gizmos<'s>::rect (line 246) ... ok
> test crates/bevy_gizmos/src/gizmos.rs - gizmos::Gizmos<'s>::rect_2d (line 435) ... ok
> test crates/bevy_gizmos/src/lib.rs - (line 6) ... ok
> test crates/bevy_gizmos/src/gizmos.rs - gizmos::Gizmos<'s>::sphere (line 208) ... ok
> 
> test result: ok. 23 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 2.62s
> ```

That is really weird. What compiler are you using and what OS?

**Comment by doonv** [comment] 2023-12-21 22:22
Another weird thing: Running in `--release` mode causes the doctests to finish in only 1.14s

**Comment by mockersf** [comment] 2023-12-21 22:31
> That is really weird. What compiler are you using and what OS?

On an apple m1 max, with rust 1.74.1

**Comment by BenjaminBrienen** [comment] 2024-10-28 22:18
12th Gen Intel(R) Core(TM) i7-12700H
```
test result: ok. 45 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 17.96s
```

**Comment by BenjaminBrienen** [comment] 2024-10-28 22:18
@doonv Can you check whether you are still experiencing this issue?

**Comment by BenjaminBrienen** [comment] 2024-10-28 22:35
With `cargo run -p ci -- doc` there is an entirely different story. A whole bunch of crates pass and then...
```
   Doc-tests bevy_gizmos

running 45 tests
test crates\bevy_gizmos\src\arcs.rs - arcs::Gizmos<'w,'s,Config,Clear>::arc_2d (line 34) has been running for over 60 seconds
test crates\bevy_gizmos\src\arcs.rs - arcs::Gizmos<'w,'s,Config,Clear>::arc_3d (line 154) has been running for over 60 seconds
test crates\bevy_gizmos\src\arcs.rs - arcs::Gizmos<'w,'s,Config,Clear>::long_arc_2d_between (line 386) has been running for over 60 seconds
test crates\bevy_gizmos\src\arcs.rs - arcs::Gizmos<'w,'s,Config,Clear>::long_arc_3d_between (line 253) has been running for over 60 seconds
test crates\bevy_gizmos\src\arcs.rs - arcs::Gizmos<'w,'s,Config,Clear>::short_arc_2d_between (line 340) has been running for over 60 seconds
test crates\bevy_gizmos\src\arcs.rs - arcs::Gizmos<'w,'s,Config,Clear>::short_arc_3d_between (line 207) has been running for over 60 seconds
test crates\bevy_gizmos\src\arrows.rs - arrows::ArrowBuilder<'_,'_,'_,Config,Clear>::with_tip_length (line 37) has been running for over 60 seconds
test crates\bevy_gizmos\src\arrows.rs - arrows::Gizmos<'w,'s,Config,Clear>::arrow (line 114) has been running for over 60 seconds
test crates\bevy_gizmos\src\arrows.rs - arrows::Gizmos<'w,'s,Config,Clear>::arrow_2d (line 145) has been running for over 60 seconds
test crates\bevy_gizmos\src\arrows.rs - arrows::Gizmos<'w,'s,Config,Clear>::axes (line 175) has been running for over 60 seconds
test crates\bevy_gizmos\src\arrows.rs - arrows::Gizmos<'w,'s,Config,Clear>::axes_2d (line 208) has been running for over 60 seconds
test crates\bevy_gizmos\src\circles.rs - circles::Gizmos<'w,'s,Config,Clear>::circle (line 116) has been running for over 60 seconds
test crates\bevy_gizmos\src\circles.rs - circles::Gizmos<'w,'s,Config,Clear>::circle_2d (line 157) has been running for over 60 seconds
test crates\bevy_gizmos\src\circles.rs - circles::Gizmos<'w,'s,Config,Clear>::ellipse (line 36) has been running for over 60 seconds
test crates\bevy_gizmos\src\circles.rs - circles::Gizmos<'w,'s,Config,Clear>::ellipse_2d (line 77) has been running for over 60 seconds
test crates\bevy_gizmos\src\circles.rs - circles::Gizmos<'w,'s,Config,Clear>::sphere (line 199) has been running for over 60 seconds
test crates\bevy_gizmos\src\cross.rs - cross::Gizmos<'_,'_,Config>::cross (line 24) has been running for over 60 seconds
test crates\bevy_gizmos\src\cross.rs - cross::Gizmos<'_,'_,Config>::cross_2d (line 59) has been running for over 60 seconds
test crates\bevy_gizmos\src\curves.rs - curves::Gizmos<'w,'s,Config,Clear>::curve_2d (line 30) has been running for over 60 seconds
test crates\bevy_gizmos\src\curves.rs - curves::Gizmos<'w,'s,Config,Clear>::curve_3d (line 64) has been running for over 60 seconds
```
It uses all 32 GB of RAM and causes the system to freeze up/soft crash after about 5-10 minutes.

**Comment by alice-i-cecile** [comment] 2024-10-28 23:32
Closing as duplicate.

**Closed by alice-i-cecile** 2024-10-28 23:32 UTC
Labels: C-Bug, C-Docs, A-Gizmos, S-Waiting-on-Author

**Comment by targrub** [comment] 2024-10-29 02:28
What issue is this a duplicate of?
IIRC, there was a `cargo` issue that causes a ballooning of memory use for certain doc tests, and the gizmos are a prime example thereof.

**Comment by BenjaminBrienen** [comment] 2024-10-29 02:31
> What issue is this a duplicate of?
> IIRC, there was a `cargo` issue that causes a ballooning of memory use for certain doc tests, and the gizmos are a prime example thereof.

https://github.com/bevyengine/bevy/issues/12207

We decided to keep the one with more info, even though it is technically newer
