### ISSUE TITLE
Transparent UI nodes block Picking

### ISSUE THREAD

**Issue by Hexorg** [bevyengine/bevy#16587] opened 2024-12-01 17:34 UTC
## Bevy version

0.15

## What you did

Add 
```rust
commands.spawn(Node{left:Val::Px(0.0),top:Val::Px(0.0),width:Val::Percent(100.0),height:Val::Percent(100.0),..default()});
```
to the `setup_scene` in the `examples/picking/simple_picking.rs` example.

## What went wrong

I expected picking to still work, because I see the text, but the text stops triggering events. 

## Additional information

I'm not sure if that's a "bug" or not. This setup technically breaks the layout engine because there are effectively now 2 UI root nodes. 

Maybe the solution is to add a warning on there being more than one UI node?

**Comment by BenjaminBrienen** [comment] 2024-12-02 00:05
You need to set the picking behavior of the invisible node.

**Comment by BenjaminBrienen** [comment] 2024-12-02 00:07
Duplicate of https://github.com/bevyengine/bevy/issues/16342

**Closed** 2024-12-02 00:08 UTC
Labels: C-Bug, S-Duplicate
